const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={tools:[],projects:[],snapshot:null,selectedTool:null,route:null,sessionId:null,token:null,connecting:false};
const KEY={token:"gameshop.console.token",client:"gameshop.console.client",verifier:"gameshop.console.verifier",state:"gameshop.console.state",resource:"gameshop.console.resource"};
const DEFAULT_SCOPES=["gameshop.read","gameshop.plan","gameshop.qa","offline_access"];
const CLIENT_NAME="Game Shop Console";
const redirectUri=()=>`${location.origin}/console`;
const mcpUrl=()=>`${location.origin}/mcp`;
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className="toast",2600)}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function pretty(value){try{return JSON.stringify(value,null,2)}catch{return String(value)}}
function copy(value){navigator.clipboard?.writeText(String(value)).then(()=>toast("Copied"),()=>toast("Copy failed",true))}
function parseStoredToken(){try{const raw=sessionStorage.getItem(KEY.token);return raw?JSON.parse(raw):null}catch{return null}}
function saveToken(token){const next={...token,expires_at:Date.now()+Number(token.expires_in||3600)*1000};sessionStorage.setItem(KEY.token,JSON.stringify(next));store.token=next;return next}
function clearAuth(){for(const key of [KEY.token,KEY.verifier,KEY.state,KEY.resource])sessionStorage.removeItem(key);store.token=null;store.sessionId=null;store.tools=[];store.projects=[];store.snapshot=null;setConnected(false);renderTools();renderProjects();renderOverview()}
function base64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function sha256(text){return new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text)))}
function randomString(bytes=32){return base64url(crypto.getRandomValues(new Uint8Array(bytes)))}
async function discovery(){const [auth,resource]=await Promise.all([fetch("/.well-known/oauth-authorization-server",{cache:"no-store"}),fetch("/.well-known/oauth-protected-resource",{cache:"no-store"})]);if(!auth.ok||!resource.ok)throw new Error("OAuth discovery is unavailable.");return{auth:await auth.json(),resource:await resource.json()}}
function selectedScopes(){const scopes=$$("[data-scope]").filter(x=>x.checked).map(x=>x.dataset.scope);if(!scopes.includes("gameshop.read"))scopes.unshift("gameshop.read");scopes.push("offline_access");return[...new Set(scopes)]}
async function registerConsole(scopes,registrationEndpoint){const cached=localStorage.getItem(KEY.client);if(cached)return cached;const response=await fetch(registrationEndpoint||"/oauth/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({client_name:CLIENT_NAME,redirect_uris:[redirectUri()],token_endpoint_auth_method:"none",grant_types:["authorization_code","refresh_token"],response_types:["code"],scope:scopes.join(" ")})});const body=await response.json().catch(()=>({}));if(!response.ok||!body.client_id)throw new Error(body.error_description||"Could not register this browser.");localStorage.setItem(KEY.client,body.client_id);return body.client_id}
async function authorizeBrowser(){if(store.connecting)return;store.connecting=true;try{const d=await discovery();const scopes=selectedScopes();const verifier=randomString(48),challenge=base64url(await sha256(verifier)),state=randomString(18);const registrationEndpoint=d.auth.registration_endpoint?new URL(d.auth.registration_endpoint).pathname:"/oauth/register";const clientId=await registerConsole(scopes,registrationEndpoint);sessionStorage.setItem(KEY.verifier,verifier);sessionStorage.setItem(KEY.state,state);sessionStorage.setItem(KEY.resource,d.resource.resource);const authEndpoint=d.auth.authorization_endpoint||"/oauth/authorize";const url=new URL(authEndpoint,location.origin);url.searchParams.set("response_type","code");url.searchParams.set("client_id",clientId);url.searchParams.set("redirect_uri",redirectUri());url.searchParams.set("scope",scopes.join(" "));url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("resource",d.resource.resource);location.assign(url.toString())}catch(error){store.connecting=false;toast(error.message||"Authorization failed",true)}}
async function handleOAuthCallback(){const url=new URL(location.href),code=url.searchParams.get("code");if(!code)return false;const state=url.searchParams.get("state")||"",expected=sessionStorage.getItem(KEY.state)||"";if(!expected||state!==expected)throw new Error("OAuth state verification failed.");const verifier=sessionStorage.getItem(KEY.verifier),resource=sessionStorage.getItem(KEY.resource),clientId=localStorage.getItem(KEY.client);if(!verifier||!resource||!clientId)throw new Error("OAuth session data is missing. Please reconnect.");const form=new URLSearchParams({grant_type:"authorization_code",code,client_id:clientId,redirect_uri:redirectUri(),code_verifier:verifier,resource});const response=await fetch("/oauth/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token)throw new Error(body.error_description||"Token exchange failed.");saveToken(body);sessionStorage.removeItem(KEY.verifier);sessionStorage.removeItem(KEY.state);history.replaceState({},"","/console");toast("Game Shop authorized");return true}
async function ensureToken(){let token=store.token||parseStoredToken();if(!token)throw new Error("Connect Game Shop first.");if(Number(token.expires_at||0)>Date.now()+30000){store.token=token;return token.access_token}if(!token.refresh_token)throw new Error("Session expired. Reconnect Game Shop.");const clientId=localStorage.getItem(KEY.client),resource=sessionStorage.getItem(KEY.resource);if(!clientId||!resource)throw new Error("OAuth refresh context is missing.");const form=new URLSearchParams({grant_type:"refresh_token",refresh_token:token.refresh_token,client_id:clientId,resource});const response=await fetch("/oauth/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token)throw new Error(body.error_description||"Refresh failed.");if(!body.refresh_token)body.refresh_token=token.refresh_token;token=saveToken(body);return token.access_token}
function parseRpc(text){const trimmed=text.trim();if(!trimmed)return null;if(trimmed.startsWith("{"))return JSON.parse(trimmed);const data=trimmed.split("\n").filter(line=>line.startsWith("data:"));if(!data.length)throw new Error(`Unexpected MCP response: ${trimmed.slice(0,140)}`);return JSON.parse(data.at(-1).slice(5).trim())}
async function rpc(payload,retry=true){const token=await ensureToken();const headers={authorization:`Bearer ${token}`,accept:"application/json, text/event-stream","content-type":"application/json"};if(store.sessionId)headers["mcp-session-id"]=store.sessionId;const response=await fetch(mcpUrl(),{method:"POST",headers,body:JSON.stringify(payload)});const text=await response.text();let body=null;try{body=parseRpc(text)}catch(error){if(!response.ok)throw new Error(text||response.statusText);throw error}if(response.status===401&&retry){store.token={...(store.token||parseStoredToken()),expires_at:0};await ensureToken();return rpc(payload,false)}if(!response.ok){const required=body?.requiredScopes?.join?.(" ");throw new Error(required?`Additional authorization required: ${required}`:(body?.error||`MCP request failed (${response.status})`))}const sid=response.headers.get("mcp-session-id");if(sid)store.sessionId=sid;if(body?.error)throw new Error(body.error.message||body.error);return body}
async function initializeMcp(){store.sessionId=null;const initialized=await rpc({jsonrpc:"2.0",id:1,method:"initialize",params:{protocolVersion:"2025-11-25",capabilities:{},clientInfo:{name:"game-shop-web-console",version:"1.0.0"}});if(!initialized?.result)throw new Error("Game Shop MCP initialization failed.");await rpc({jsonrpc:"2.0",method:"notifications/initialized",params:{}});const listed=await rpc({jsonrpc:"2.0",id:2,method:"tools/list",params:{}});store.tools=listed?.result?.tools||[];setConnected(true);renderTools();return initialized.result}
let rpcId=20;async function callTool(name,args={}){const response=await rpc({jsonrpc:"2.0",id:++rpcId,method:"tools/call",params:{name,arguments:args}});const result=response?.result;if(result?.isError){const text=result.content?.map?.(x=>x.text).filter(Boolean).join("\n")||"Tool returned an error.";throw new Error(text)}return result}
function structured(result){return result?.structuredContent??result?.content?.find?.(x=>x.type==="text")?.text??result}
function setConnected(on){$("#railDot").classList.toggle("online",on);$("#railStatus").textContent=on?"Connected":"Disconnected";$("#refreshBtn").disabled=!on;$("#connectBtn").textContent=on?"Connected":"Connect Game Shop";$("#connectBtn").disabled=on;const scopes=(store.token||parseStoredToken())?.scope||"";$("#scopeMini").textContent=on?(scopes||"Authorized session"):"No active session";$("#posturePill").textContent=on?"Live":"Offline";$("#posturePill").style.color=on?"var(--green)":""}
async function loadOverview(){const [center,projects]=await Promise.allSettled([callTool("gameshop_control_center_v2",{}),callTool("gameshop_list_projects",{})]);if(center.status==="fulfilled")store.snapshot=structured(center.value);if(projects.status==="fulfilled")store.projects=normalizeProjects(structured(projects.value));renderOverview();renderProjects()}
function normalizeProjects(value){if(Array.isArray(value))return value;if(Array.isArray(value?.projects))return value.projects;if(Array.isArray(value?.snapshot?.projects))return value.snapshot.projects;if(Array.isArray(value?.registry))return value.registry;return[]}
function renderOverview(){const root=$("#metrics");if(!store.snapshot&&!store.projects.length){root.innerHTML=['Projects','Executions','Artifacts','Tools'].map(x=>`<article class="metric"><span>${x}</span><strong>—</strong><small>Connect to load</small></article>`).join("");$("#systemList").innerHTML='<div class="empty">Authorize the console to inspect Game Shop.</div>';$("#eventList").innerHTML='<div class="empty">No live events loaded.</div>';return}const s=store.snapshot?.snapshot||store.snapshot||{},base=s.base||{},summary=base.summary||s.summary||{},sup=s.supervision||{},systems=s.systems||{},events=sup.events||s.events||[];const metrics=[["Projects",store.projects.length||sup.projects?.length||0,"Registered source roots"],["Executions",summary.executions||0,"Governed runs"],["Artifacts",summary.artifacts||0,"Captured outputs"],["Tools",store.tools.length,"Live MCP inventory"]];root.innerHTML=metrics.map(([a,b,c])=>`<article class="metric"><span>${esc(a)}</span><strong>${esc(b)}</strong><small>${esc(c)}</small></article>`).join("");const entries=Object.entries(systems).slice(0,8);$("#systemList").innerHTML=entries.length?entries.map(([k,v])=>`<div class="system-row"><b>${esc(k)}</b><span>${esc(typeof v==="string"?v:JSON.stringify(v))}</span></div>`).join(""):'<div class="empty">System snapshot is healthy but contains no detailed subsystem rows.</div>';$("#eventCount").textContent=`${events.length} events`;$("#eventList").innerHTML=events.length?events.slice(0,12).map(x=>`<div class="event"><i></i><b>${esc(x.type||x.action||"event")}</b><time>${esc(formatTime(x.created_at||x.createdAt))}</time></div>`).join(""):'<div class="empty">No recent events.</div>';const posture=summary.platformPosture||s.posture||"live";$("#posturePill").textContent=String(posture)}
function formatTime(value){if(!value)return"";try{return new Date(value).toLocaleString()}catch{return String(value)}}
function renderProjects(){const q=$("#projectSearch")?.value?.toLowerCase()||"";const rows=store.projects.filter(p=>!q||pretty(p).toLowerCase().includes(q));$("#projectGrid").innerHTML=rows.length?rows.map(p=>{const id=p.id||p.projectId||p.slug||p.name||"project",name=p.title||p.name||id,type=p.product||p.kind||p.type||"project",root=p.root||p.path||p.repo||p.repository||"Registered with Game Shop";const tags=[p.runtime,p.framework,p.status].filter(Boolean);return`<article class="project-card"><span class="type">${esc(type)}</span><h3 title="${esc(name)}">${esc(name)}</h3><p>${esc(root)}</p><div class="project-meta">${tags.map(x=>`<span>${esc(x)}</span>`).join("")}</div></article>`}).join(""):'<div class="empty panel">No matching projects.</div>'}
function renderTools(){const q=$("#toolSearch")?.value?.toLowerCase()||"",tools=store.tools.filter(t=>!q||`${t.name} ${t.description||""} ${t.title||""}`.toLowerCase().includes(q));$("#toolCount").textContent=store.tools.length;$("#toolList").innerHTML=tools.length?tools.map(t=>`<button class="tool-item${store.selectedTool?.name===t.name?" active":""}" data-tool="${esc(t.name)}"><b>${esc(t.title||t.name)}</b><span>${esc(t.name)}</span></button>`).join(""):'<div class="empty">No tools found.</div>';$$('[data-tool]').forEach(btn=>btn.addEventListener('click',()=>selectTool(store.tools.find(t=>t.name===btn.dataset.tool))))}
function selectTool(tool){if(!tool)return;store.selectedTool=tool;$("#runnerTitle").textContent=tool.title||tool.name;$("#runnerDescription").textContent=tool.description||tool.name;const schema=tool.inputSchema||tool.input_schema||{};$("#toolArgs").value=exampleForSchema(schema);$("#runToolBtn").disabled=false;$("#toolResult").textContent=pretty({name:tool.name,annotations:tool.annotations||{},inputSchema:schema});renderTools()}
function exampleForSchema(schema){const props=schema?.properties||{},obj={};for(const [key,p] of Object.entries(props)){if(p.default!==undefined)obj[key]=p.default;else if(Array.isArray(p.enum)&&p.enum.length)obj[key]=p.enum[0];else if(p.type==="boolean")obj[key]=false;else if(p.type==="array")obj[key]=[];else if(p.type==="number"||p.type==="integer")obj[key]=0;else if((schema.required||[]).includes(key))obj[key]=""}return pretty(obj)}
async function runSelectedTool(){const tool=store.selectedTool;if(!tool)return;let args;try{args=JSON.parse($("#toolArgs").value||"{}") }catch{toast("Arguments must be valid JSON",true);return}const risky=tool.annotations?.destructiveHint||tool.annotations?.openWorldHint||tool.annotations?.readOnlyHint===false;if(risky&&!confirm(`Run ${tool.name}?\n\nThis tool may change external or project state. Game Shop scope and policy gates still apply.`))return;$("#runToolBtn").disabled=true;$("#toolResult").textContent="Running…";try{const result=await callTool(tool.name,args);$("#toolResult").textContent=pretty(structured(result));toast("Tool completed");await loadOverview().catch(()=>{})}catch(error){$("#toolResult").textContent=error.message||String(error);toast(error.message||"Tool failed",true)}finally{$("#runToolBtn").disabled=false}}
async function routeMission(brief,lane){if(!brief.trim())throw new Error("Add a mission brief first.");const phase=$("#missionPhase").value,existingProject=$("#existingProject").checked;let result;if(lane==="website")result=await callTool("gameshop_route_website_workflow",{brief:brief.trim(),phase,kind:$("#siteKind").value,framework:$("#siteFramework").value,preference:$("#missionPreference")?.value||"balanced",existingProject});else result=await callTool("gameshop_route_game_workflow",{brief:brief.trim(),phase,runtime:$("#gameRuntime").value,preference:$("#missionPreference").value,existingProject});store.route=structured(result);renderRoute();return store.route}
function renderRoute(){const d=store.route;if(!d){$("#routeResult").innerHTML='<div class="empty tall">Your routed workflow will appear here.</div>';$("#copyRouteBtn").disabled=true;return}const stages=d.stages||[],gates=d.gates||[],cautions=d.cautions||[];$("#copyRouteBtn").disabled=false;$("#routeResult").innerHTML=`<div class="route-summary"><div class="route-chip"><span>TYPE / RUNTIME</span><b>${esc(d.selectedKind||d.selectedRuntime||d.kind||"auto")}</b></div><div class="route-chip"><span>PRIMARY LANE</span><b>${esc(d.primaryLane||"Game Shop")}</b></div><div class="route-chip"><span>PHASE</span><b>${esc(d.phase||"plan")}</b></div></div><div class="stage-list">${stages.map((s,i)=>`<article class="stage"><div class="stage-num">${esc(s.order||i+1)}</div><div><h4>${esc(s.lane||s.owner||"Stage")}</h4><p><b>${esc(s.owner||"")}</b>${s.owner?" · ":""}${esc(s.purpose||"")}</p>${s.gate?`<div class="gate">Gate: ${esc(s.gate)}</div>`:""}</div></article>`).join("")}</div>${gates.length?`<div class="note"><b>Blocking gates</b><p>${gates.map(esc).join("<br>")}</p></div>`:""}${cautions.length?`<div class="note"><b>Routing cautions</b><p>${cautions.map(esc).join("<br>")}</p></div>`:""}`}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$("#viewTitle").textContent=({overview:"Control Room",mission:"Mission Router",projects:"Projects",tools:"Tool Deck",connect:"Connections"})[name]||"Game Shop";if(innerWidth<760)scrollTo({top:0,behavior:"smooth"})}
function bind(){$$('.nav-item').forEach(x=>x.addEventListener('click',()=>showView(x.dataset.view)));$$('[data-jump]').forEach(x=>x.addEventListener('click',()=>showView(x.dataset.jump)));$("#connectBtn").addEventListener('click',()=>showView('connect'));$("#authorizeBtn").addEventListener('click',authorizeBrowser);$("#disconnectBtn").addEventListener('click',()=>{clearAuth();toast("Browser session cleared")});$("#refreshBtn").addEventListener('click',async()=>{try{await initializeMcp();await loadOverview();toast("Refreshed")}catch(e){toast(e.message,true)}});$("#projectSearch").addEventListener('input',renderProjects);$("#toolSearch").addEventListener('input',renderTools);$("#runToolBtn").addEventListener('click',runSelectedTool);$("#copyResultBtn").addEventListener('click',()=>copy($("#toolResult").textContent));$("#copyRouteBtn").addEventListener('click',()=>copy(pretty(store.route)));$$('[data-copy]').forEach(btn=>btn.addEventListener('click',()=>copy($(btn.dataset.copy).textContent)));$("#missionLane").addEventListener('change',()=>{const web=$("#missionLane").value==="website";$("#websiteOptions").classList.toggle('hidden',!web);$("#gameOptions").classList.toggle('hidden',web)});$("#missionForm").addEventListener('submit',async e=>{e.preventDefault();try{await routeMission($("#missionBrief").value,$("#missionLane").value);toast("Mission routed")}catch(error){toast(error.message,true)}});$("#quickMission").addEventListener('submit',async e=>{e.preventDefault();const brief=$("#quickBrief").value,lane=$("#quickLane").value;$("#missionBrief").value=brief;$("#missionLane").value=lane;$("#missionLane").dispatchEvent(new Event('change'));showView('mission');try{await routeMission(brief,lane);toast("Mission routed")}catch(error){toast(error.message,true)}})}
async function boot(){bind();store.token=parseStoredToken();try{await handleOAuthCallback();store.token=parseStoredToken()}catch(error){clearAuth();toast(error.message,true)}if(store.token){try{await initializeMcp();await loadOverview()}catch(error){setConnected(false);toast(error.message||"Could not connect to Game Shop",true)}}else setConnected(false)}
boot();
