export type ArtifactKind = "image"|"sprite"|"spritesheet"|"3d"|"video"|"audio"|"rive"|"document"|"code"|"archive"|"data"|"other";
export type ArtifactPurpose = "game"|"website"|"web-app"|"mobile-app"|"interactive-experience"|"digital-product"|"media"|"general";
export type ArtifactStatus = "pending"|"ready"|"failed"|"archived";
export type GameShopArtifact = {artifactId:string;executionId:string;projectId?:string;kind:ArtifactKind;purpose:ArtifactPurpose;status:ArtifactStatus;name:string;provider?:string;providerJobId?:string;mimeType?:string;sourceUrl?:string;storageUrl?:string;metadata:Record<string,unknown>;createdAt:string;updatedAt:string};
const memory=new Map<string,GameShopArtifact>();
function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
function id(){return `art_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;}
async function request(path:string,init?:RequestInit){const c=config();if(!c)return null;const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init?.headers||{})},signal:AbortSignal.timeout(12000)});const text=await r.text();if(!r.ok)throw new Error(`Artifact store request failed (${r.status}).`);return text?JSON.parse(text):null;}
function row(a:GameShopArtifact){return{artifact_id:a.artifactId,execution_id:a.executionId,project_id:a.projectId??null,kind:a.kind,purpose:a.purpose,status:a.status,name:a.name,provider:a.provider??null,provider_job_id:a.providerJobId??null,mime_type:a.mimeType??null,source_url:a.sourceUrl??null,storage_url:a.storageUrl??null,metadata:a.metadata,created_at:a.createdAt,updated_at:a.updatedAt};}
function artifact(r:Record<string,unknown>):GameShopArtifact{return{artifactId:String(r.artifact_id),executionId:String(r.execution_id),projectId:r.project_id?String(r.project_id):undefined,kind:r.kind as ArtifactKind,purpose:r.purpose as ArtifactPurpose,status:r.status as ArtifactStatus,name:String(r.name),provider:r.provider?String(r.provider):undefined,providerJobId:r.provider_job_id?String(r.provider_job_id):undefined,mimeType:r.mime_type?String(r.mime_type):undefined,sourceUrl:r.source_url?String(r.source_url):undefined,storageUrl:r.storage_url?String(r.storage_url):undefined,metadata:(r.metadata??{}) as Record<string,unknown>,createdAt:String(r.created_at),updatedAt:String(r.updated_at)};}
export async function createArtifact(input:Omit<GameShopArtifact,"artifactId"|"createdAt"|"updatedAt">){const now=new Date().toISOString();const a:GameShopArtifact={...input,artifactId:id(),createdAt:now,updatedAt:now};memory.set(a.artifactId,a);const data=await request("game_shop_artifacts",{method:"POST",body:JSON.stringify(row(a))});if(Array.isArray(data)&&data[0])return artifact(data[0]);return a;}
export async function getArtifact(artifactId:string){if(memory.has(artifactId))return memory.get(artifactId)!;const data=await request(`game_shop_artifacts?artifact_id=eq.${encodeURIComponent(artifactId)}&limit=1`);return Array.isArray(data)&&data[0]?artifact(data[0]):null;}
export async function listArtifacts(input:{executionId?:string;projectId?:string;kind?:ArtifactKind}={}){const params=new URLSearchParams({order:"created_at.desc",limit:"100"});if(input.executionId)params.set("execution_id",`eq.${input.executionId}`);if(input.projectId)params.set("project_id",`eq.${input.projectId}`);if(input.kind)params.set("kind",`eq.${input.kind}`);const data=await request(`game_shop_artifacts?${params}`);if(Array.isArray(data))return data.map(artifact);return [...memory.values()].filter(a=>(!input.executionId||a.executionId===input.executionId)&&(!input.projectId||a.projectId===input.projectId)&&(!input.kind||a.kind===input.kind)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export async function updateArtifact(artifactId:string,patch:Partial<Pick<GameShopArtifact,"status"|"sourceUrl"|"storageUrl"|"mimeType"|"providerJobId"|"metadata">>){const current=await getArtifact(artifactId);if(!current)return null;const next:GameShopArtifact={...current,...patch,metadata:patch.metadata?{...current.metadata,...patch.metadata}:current.metadata,updatedAt:new Date().toISOString()};memory.set(artifactId,next);const data=await request(`game_shop_artifacts?artifact_id=eq.${encodeURIComponent(artifactId)}`,{method:"PATCH",body:JSON.stringify(row(next))});return Array.isArray(data)&&data[0]?artifact(data[0]):next;}
export function artifactStoreInfo(){return{backend:config()?"supabase-postgres":"process-memory-fallback",durableAcrossColdStarts:Boolean(config()),table:"game_shop_artifacts",scope:"Universal artifacts for games, websites, web apps, mobile apps, interactive experiences, digital products and media."};}
export const ARTIFACT_STORE_SQL=`create table if not exists public.game_shop_artifacts (artifact_id text primary key,execution_id text not null,project_id text,kind text not null,purpose text not null,status text not null,name text not null,provider text,provider_job_id text,mime_type text,source_url text,storage_url text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null,updated_at timestamptz not null); create index if not exists game_shop_artifacts_execution_idx on public.game_shop_artifacts(execution_id); create index if not exists game_shop_artifacts_project_idx on public.game_shop_artifacts(project_id);`;
