import { mcpCallTool,mcpInitialize,mcpListTools } from "./mcp-http-client.js";
export type BrowserQaProvider="browserbase"|"playwright-mcp";
export type BrowserAssertion=
 | {kind:"selector-visible";selector:string}
 | {kind:"selector-text";selector:string;includes:string}
 | {kind:"title-includes";includes:string}
 | {kind:"url-includes";includes:string}
 | {kind:"body-min-text";min:number}
 | {kind:"element-count";selector:string;min:number}
 | {kind:"canvas-ready";selector?:string};
export type BrowserJudgement={authoritative:boolean;passed:boolean;assertions:number;errors:string[];challengeTransientIgnored?:boolean};
export type BrowserEvidence={provider:BrowserQaProvider;url:string;sessionId?:string;tools:string[];steps:Array<Record<string,unknown>>;console:Array<Record<string,unknown>>;network:Array<Record<string,unknown>>;screenshots:Array<Record<string,unknown>>;snapshot?:unknown;navigation?:unknown;performance?:unknown;assertions?:unknown;judgement?:BrowserJudgement;errors:string[]};
function configuredProvider(preferred?:BrowserQaProvider):BrowserQaProvider{if(preferred)return preferred;if(process.env.BROWSERBASE_API_KEY)return"browserbase";return"playwright-mcp";}
function browserbaseUrl(){const key=process.env.BROWSERBASE_API_KEY;if(!key)throw new Error("BROWSERBASE_API_KEY is not configured.");const url=new URL("https://mcp.browserbase.com/mcp");url.searchParams.set("browserbaseApiKey",key);url.searchParams.set("keepAlive","false");return url.toString();}
function playwrightUrl(){const url=process.env.GAME_SHOP_PLAYWRIGHT_MCP_URL;if(!url)throw new Error("GAME_SHOP_PLAYWRIGHT_MCP_URL is not configured.");return url;}
function stringifyEvidence(data:unknown){try{const value=JSON.stringify(data);return value===undefined?String(data??""):value;}catch{return String(data??"");}}
function evidenceText(data:unknown){return stringifyEvidence(data).toLowerCase();}
function toolResult(data:unknown){const root=data as Record<string,unknown>|null;const result=(root?.result??root) as Record<string,unknown>|undefined;return{data:result?.structuredContent??result?.content??result??data,isError:result?.isError===true};}
async function call(url:string,name:string,args:Record<string,unknown>,sessionId?:string){const r=await mcpCallTool({url,name,arguments:args,sessionId,timeoutMs:30000});const parsed=toolResult(r.data);return{sessionId:r.sessionId,data:parsed.data,isError:parsed.isError};}
function assertionCode(assertions:BrowserAssertion[]){return assertions.map((assertion,index)=>{const fail=(message:string)=>`failures.push(${JSON.stringify(`assertion-${index+1}: ${message}`)});`;switch(assertion.kind){case"selector-visible":return`{const el=document.querySelector(${JSON.stringify(assertion.selector)});if(!el||!(el instanceof HTMLElement)||el.hidden||getComputedStyle(el).display==='none'||getComputedStyle(el).visibility==='hidden')${fail(`selector not visible: ${assertion.selector}`)}}`;case"selector-text":return`{const el=document.querySelector(${JSON.stringify(assertion.selector)});if(!el||!(el.textContent||'').includes(${JSON.stringify(assertion.includes)}))${fail(`selector text missing '${assertion.includes}': ${assertion.selector}`)}}`;case"title-includes":return`if(!document.title.includes(${JSON.stringify(assertion.includes)}))${fail(`title missing '${assertion.includes}'`)}`;case"url-includes":return`if(!location.href.includes(${JSON.stringify(assertion.includes)}))${fail(`url missing '${assertion.includes}'`)}`;case"body-min-text":return`if((document.body?.innerText||'').trim().length<${Math.max(0,assertion.min)})${fail(`body text shorter than ${assertion.min}`)}`;case"element-count":return`if(document.querySelectorAll(${JSON.stringify(assertion.selector)}).length<${Math.max(0,assertion.min)})${fail(`element count below ${assertion.min}: ${assertion.selector}`)}`;case"canvas-ready":return`{const canvas=document.querySelector(${JSON.stringify(assertion.selector??"canvas")});if(!(canvas instanceof HTMLCanvasElement)||canvas.width<1||canvas.height<1)${fail(`canvas not ready: ${assertion.selector??"canvas"}`)}}`;}}).join("\n");}
function interactionCode(action:string){const trimmed=action.trim();if(trimmed.startsWith("click:")){const selector=trimmed.slice(6).trim();return`async (page)=>{const target=page.locator(${JSON.stringify(selector)}).first();await target.waitFor({state:'visible',timeout:5000});await target.click({timeout:5000});return{action:'click',selector:${JSON.stringify(selector)},url:page.url()};}`;}if(trimmed.startsWith("press:")){const key=trimmed.slice(6).trim();return`async (page)=>{await page.keyboard.press(${JSON.stringify(key)});return{action:'press',key:${JSON.stringify(key)},url:page.url()};}`;}if(trimmed.startsWith("wait:")){const ms=Math.max(0,Math.min(5000,Number(trimmed.slice(5))||0));return`async (page)=>{await page.waitForTimeout(${ms});return{action:'wait',ms:${ms},url:page.url()};}`;}if(trimmed.startsWith("fill:")){const body=trimmed.slice(5),split=body.indexOf("=");if(split>0){const selector=body.slice(0,split).trim(),value=body.slice(split+1);return`async (page)=>{const target=page.locator(${JSON.stringify(selector)}).first();await target.fill(${JSON.stringify(value)},{timeout:5000});return{action:'fill',selector:${JSON.stringify(selector)},url:page.url()};}`;}}return`async (page)=>({action:'intent-only',intent:${JSON.stringify(trimmed.slice(0,300))},url:page.url(),title:await page.title()})`;}
function networkStatuses(text:string){return[...text.matchAll(/=>\s*\[(\d{3})\]/g)].map(match=>Number(match[1])).filter(Number.isFinite);}
export async function executeBrowserQa(input:{url:string;provider?:BrowserQaProvider;interactions?:string[];assertions?:BrowserAssertion[]}){const provider=configuredProvider(input.provider);const endpoint=provider==="browserbase"?browserbaseUrl():playwrightUrl();const init=await mcpInitialize({url:endpoint,timeoutMs:15000});const listed=await mcpListTools({url:endpoint,sessionId:init.sessionId,timeoutMs:15000});let sessionId=listed.sessionId;const names=new Set(listed.tools.map(t=>t.name));const assertions=(input.assertions??[]).slice(0,20);const evidence:BrowserEvidence={provider,url:input.url,sessionId,tools:[...names],steps:[],console:[],network:[],screenshots:[],errors:[]};
 const invoke=async(name:string,args:Record<string,unknown>={})=>{if(!names.has(name))return null;try{const r=await call(endpoint,name,args,sessionId);sessionId=r.sessionId??sessionId;evidence.sessionId=sessionId;if(r.isError){const message=`${name}: ${stringifyEvidence(r.data).slice(0,2000)}`;evidence.errors.push(message);evidence.steps.push({tool:name,ok:false,error:message});return null;}evidence.steps.push({tool:name,ok:true});return r.data}catch(error){const message=error instanceof Error?error.message:String(error);evidence.errors.push(`${name}: ${message}`);evidence.steps.push({tool:name,ok:false,error:message});return null}};
 if(provider==="browserbase"){await invoke("start");await invoke("navigate",{url:input.url});const extracted=await invoke("extract",{instruction:"Inspect the page for visible error messages, broken or blank sections, missing primary content, obvious layout failures, and summarize the main interactive controls."});if(extracted)evidence.snapshot=extracted;for(const action of(input.interactions??[]).slice(0,8))await invoke("act",{action});const final=await invoke("extract",{instruction:"Return the current page title, main visible content, any error states, and whether primary controls appear usable."});if(final)evidence.snapshot=final;evidence.judgement={authoritative:false,passed:evidence.errors.length===0,assertions:0,errors:[...evidence.errors]};await invoke("end");return evidence;}
 if(names.has("browser_run_code")){const code=`async (page)=>{const consoleErrors=[];const failedRequests=[];const badResponses=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('requestfailed',r=>failedRequests.push({url:r.url(),failure:r.failure()?.errorText||'failed'}));page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()})});await page.goto(${JSON.stringify(input.url)},{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(750);return{passed:consoleErrors.length===0&&failedRequests.length===0&&badResponses.length===0,consoleErrors,failedRequests,badResponses,title:await page.title(),url:page.url()};}`;const navigation=await invoke("browser_run_code",{code});if(navigation)evidence.navigation=navigation;}else await invoke("browser_navigate",{url:input.url});
 const snap=await invoke("browser_snapshot");if(snap)evidence.snapshot=snap;
 for(const action of(input.interactions??[]).slice(0,8))if(names.has("browser_run_code"))await invoke("browser_run_code",{code:interactionCode(action)});
 let assertionsPassed=assertions.length===0;if(names.has("browser_run_code")){const finalCode=`async (page)=>{await page.waitForTimeout(250);const assertions=await page.evaluate(()=>{const failures=[];${assertionCode(assertions)}return{passed:failures.length===0,failures,title:document.title,url:location.href,readyState:document.readyState,bodyTextLength:(document.body?.innerText||'').length};});if(!assertions.passed)throw new Error('GAME_SHOP_BROWSER_JUDGE:'+JSON.stringify({hard:assertions.failures.map(message=>({kind:'assertion',message})),assertions}));return assertions;}`;const judged=await invoke("browser_run_code",{code:finalCode});if(judged){evidence.assertions=judged;assertionsPassed=true;}}
 const consoleData=await invoke("browser_console_messages",{level:"error"})??await invoke("browser_console_messages",{});let consoleText="";if(consoleData){evidence.console.push({data:consoleData});consoleText=evidenceText(consoleData);}
 const networkData=await invoke("browser_network_requests",{includeStatic:true})??await invoke("browser_network_requests",{});let networkText="";if(networkData){evidence.network.push({data:networkData});networkText=evidenceText(networkData);}
 const statuses=networkStatuses(networkText);const hardStatuses=statuses.filter(status=>status>=400);const challengeSeen=/cdn-cgi\/challenge-platform/.test(networkText);const challengeOnly=challengeSeen&&assertionsPassed&&hardStatuses.length>0&&hardStatuses.every(status=>status===403);const consoleHasHard=!/(total messages[:= ]+0|no console|\[\]|"messages":\[\])/.test(consoleText)&&/(\[error\]|uncaught|exception|failed to load resource)/.test(consoleText);if(consoleHasHard&&!(challengeOnly&&/failed to load resource[^]*403/.test(consoleText)))evidence.errors.push("console: browser console reported runtime errors");const networkHasHard=hardStatuses.length>0||/requestfailed|net::err|failed to fetch/.test(networkText);if(networkHasHard&&!challengeOnly)evidence.errors.push("network: failed request or HTTP error detected");
 const shot=await invoke("browser_take_screenshot",{type:"png",fullPage:true})??await invoke("browser_screenshot",{});if(shot)evidence.screenshots.push({data:shot});const perf=await invoke("browser_evaluate",{function:"() => ({href:location.href,title:document.title,readyState:document.readyState,bodyTextLength:(document.body?.innerText||'').length,canvasCount:document.querySelectorAll('canvas').length,performance:performance.getEntriesByType('navigation').map((e)=>({duration:e.duration,domContentLoadedEventEnd:e.domContentLoadedEventEnd,loadEventEnd:e.loadEventEnd}))})"});if(perf)evidence.performance=perf;evidence.judgement={authoritative:true,passed:evidence.errors.length===0&&assertionsPassed,assertions:assertions.length,errors:[...evidence.errors],challengeTransientIgnored:challengeOnly};return evidence;
}
export function browserAdapterInfo(){return{browserbase:{configured:Boolean(process.env.BROWSERBASE_API_KEY),endpoint:"https://mcp.browserbase.com/mcp",mode:"hosted-stagehand-mcp",authoritative:false},playwright:{configured:Boolean(process.env.GAME_SHOP_PLAYWRIGHT_MCP_URL),mode:"streamable-http-mcp",authoritative:true,recommendedCommand:"npm run playwright:mcp",interactionSyntax:["click:<selector>","press:<key>","wait:<ms>","fill:<selector>=<value>"]}};}
