import { discoverCapabilities } from "./capability-discovery.js";
import { mcpInitialize,mcpListTools } from "./mcp-http-client.js";

export type TrustState="discovered"|"inspected"|"sandbox_passed"|"sandbox_failed"|"approved"|"rejected";
export type TrustedCapability={id:string;name:string;description?:string;endpoint?:string;state:TrustState;score:number;tools:string[];reasons:string[];source:string;approvedAt?:string;createdAt:string;updatedAt:string};
const memory=new Map<string,TrustedCapability>();
function storeConfig(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
async function persist(item:TrustedCapability){memory.set(item.id,item);const c=storeConfig();if(!c)return item;const row={capability_id:item.id,name:item.name,description:item.description??null,endpoint:item.endpoint??null,state:item.state,score:item.score,tools:item.tools,reasons:item.reasons,source:item.source,approved_at:item.approvedAt??null,created_at:item.createdAt,updated_at:item.updatedAt};const r=await fetch(`${c.url}/rest/v1/game_shop_capability_trust?on_conflict=capability_id`,{method:"POST",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Capability trust store failed (${r.status}).`);return item;}
function id(name:string){return `cap_${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48)}`;}
function safeEndpoint(endpoint:string){const url=new URL(endpoint);if(url.protocol!=="https:")throw new Error("Only HTTPS remote MCP endpoints can enter the trust pipeline.");if(/localhost|127\.0\.0\.1|\.local$/i.test(url.hostname))throw new Error("Private/local endpoints are not eligible for remote trust promotion.");return url.toString();}
function scoreCandidate(input:{endpoint?:string;tools:string[];description?:string;source:string}){let score=0;const reasons:string[]=[];if(input.source==="official-mcp-registry"){score+=30;reasons.push("official-registry-source");}if(input.endpoint?.startsWith("https://")){score+=20;reasons.push("https-remote-endpoint");}if(input.tools.length){score+=Math.min(30,input.tools.length*3);reasons.push(`${input.tools.length}-tools-introspected`);}if(input.description){score+=10;reasons.push("documented-description");}const risky=input.tools.filter(t=>/shell|exec|terminal|filesystem|delete|payment|wallet|secret|credential/i.test(t));if(risky.length){score-=Math.min(40,risky.length*10);reasons.push(`sensitive-tools:${risky.join(",")}`);}else{score+=10;reasons.push("no-obvious-sensitive-tools");}return{score:Math.max(0,Math.min(100,score)),reasons};}
export function capabilityTrustInfo(){return{pipeline:["discover","inspect","sandbox-test","score","approve","promote"],sandbox:"initialize + tools/list only; no candidate tools are executed before approval",approvalRequired:true,promotionThreshold:70,dynamicArsenal:true,store:storeConfig()?"supabase+memory":"memory"};}
export async function inspectCapability(input:{name:string;description?:string;endpoint:string;source?:string}){const endpoint=safeEndpoint(input.endpoint);const now=new Date().toISOString();const item:TrustedCapability={id:id(input.name),name:input.name,description:input.description,endpoint,state:"inspected",score:0,tools:[],reasons:["endpoint-syntax-validated"],source:input.source??"manual",createdAt:now,updatedAt:now};return persist(item);}
export async function sandboxCapability(input:{name:string;description?:string;endpoint:string;source?:string}){const endpoint=safeEndpoint(input.endpoint);const now=new Date().toISOString();let tools:string[]=[];let state:TrustState="sandbox_failed";let error:string|undefined;try{const init=await mcpInitialize({url:endpoint,timeoutMs:8000});const listed=await mcpListTools({url:endpoint,sessionId:init.sessionId,timeoutMs:8000});tools=listed.tools.map(t=>t.name).slice(0,100);state="sandbox_passed";}catch(e){error=e instanceof Error?e.message:String(e);}const scored=scoreCandidate({endpoint,tools,description:input.description,source:input.source??"manual"});const reasons=error?[...scored.reasons,`sandbox-error:${error}`]:scored.reasons;const existing=memory.get(id(input.name));const item:TrustedCapability={id:id(input.name),name:input.name,description:input.description,endpoint,state,score:state==="sandbox_passed"?scored.score:Math.min(scored.score,40),tools,reasons,source:input.source??"manual",createdAt:existing?.createdAt??now,updatedAt:now};return persist(item);}
export async function approveCapability(input:{name:string;approved:boolean}){const item=memory.get(id(input.name));if(!item)throw new Error("Capability has not been sandbox-tested in this process.");if(input.approved&&item.state!=="sandbox_passed")throw new Error("Only sandbox-passed capabilities can be approved.");if(input.approved&&item.score<70)throw new Error("Capability score is below the 70-point promotion threshold.");const now=new Date().toISOString();const next={...item,state:(input.approved?"approved":"rejected") as TrustState,approvedAt:input.approved?now:undefined,updatedAt:now};await persist(next);return{status:input.approved?"promoted":"rejected",capability:next};}
export function trustedCapabilities(){return[...memory.values()].filter(v=>v.state==="approved").sort((a,b)=>b.score-a.score);}
export async function discoverForTrust(input:{query:string;limit?:number}){const discovery=await discoverCapabilities(input);return{...discovery,trust:capabilityTrustInfo(),next:"Choose a candidate with an HTTPS remote endpoint, inspect it, sandbox-test initialize/tools-list, then explicitly approve promotion."};}
export const CAPABILITY_TRUST_SQL=`create table if not exists public.game_shop_capability_trust (capability_id text primary key,name text not null,description text,endpoint text,state text not null,score int not null default 0,tools jsonb not null default '[]'::jsonb,reasons jsonb not null default '[]'::jsonb,source text not null,approved_at timestamptz,created_at timestamptz not null,updated_at timestamptz not null);`;
