import { githubCreateProjectBranch,githubReadProjectFile,githubUpsertProjectFile,githubVerifyProjectBranch } from "./github-execution.js";
import { getProject } from "./projects.js";

export type PatchOperation={path:string;content:string;expectedSha?:string;reason?:string};
function safeText(content:string){if(Buffer.byteLength(content,"utf8")>120_000)throw new Error("Patch file exceeds 120 KB limit.");return content;}
export function patchWorkerInfo(){return{mode:"constrained-replacement",approvalRequired:true,maxFiles:8,maxTotalBytes:400_000,branchPrefix:"gameshop/",prohibited:["path escape","default-branch writes","binary replacement","secret injection","more than 8 files"],writeGate:"GAME_SHOP_ALLOW_GITHUB_WRITES"};}
export async function applyApprovedPatch(input:{projectId:string;branch:string;baseRef?:string;approved:boolean;operations:PatchOperation[];title?:string}){if(!input.approved)throw new Error("Patch approval is required.");if(!/^gameshop\/[a-z0-9._/-]+$/i.test(input.branch))throw new Error("Patch branch must start with gameshop/.");if(!input.operations.length||input.operations.length>8)throw new Error("Patch must contain between 1 and 8 files.");const project=getProject(input.projectId);let total=0;for(const op of input.operations){if(op.path.includes("..")||op.path.startsWith("/"))throw new Error("Invalid patch path.");total+=Buffer.byteLength(op.content,"utf8");safeText(op.content);}if(total>400_000)throw new Error("Patch exceeds total size limit.");
 try{await githubCreateProjectBranch({projectId:input.projectId,branch:input.branch,fromRef:input.baseRef??project.defaultBranch})}catch(error){const message=error instanceof Error?error.message:String(error);if(!/422|reference already exists|already exists/i.test(message))throw error;}
 const applied=[] as Array<Record<string,unknown>>;for(const op of input.operations){let currentSha:string|undefined;try{const current=await githubReadProjectFile({projectId:input.projectId,path:op.path,ref:input.branch});currentSha=current.sha as string;if(op.expectedSha&&op.expectedSha!==currentSha)throw new Error(`Patch precondition failed for ${op.path}.`);}catch(error){if(op.expectedSha)throw error;}
  const result=await githubUpsertProjectFile({projectId:input.projectId,path:op.path,content:safeText(op.content),message:input.title??`Game Shop repair: ${op.reason??op.path}`,branch:input.branch,sha:currentSha});applied.push({path:op.path,reason:op.reason??null,commitSha:result.commitSha});}
 const verification=await githubVerifyProjectBranch({projectId:input.projectId,branch:input.branch});if(!verification.scopeSafe)throw new Error("Patch escaped the registered project scope.");return{status:"applied",projectId:input.projectId,branch:input.branch,applied,totalBytes:total,verification};}
