import { artifactStoreInfo, listArtifacts } from "./artifacts.js";
import { executionStoreInfo, resolveExecutions } from "./execution-store.js";
import { externalEngineStatus } from "./external-engines.js";
import { integrationRegistry } from "./integrations.js";
import { taskBridgeInfo } from "./task-bridge.js";
import { orchestrationSnapshot } from "./orchestrator.js";
import { qaWorkerInfo } from "./qa-worker.js";
import { qaSwarmInfo } from "./qa-swarm.js";
import { qaMemoryInfo,listQaRecipes } from "./qa-memory.js";
import { qaReplayInfo } from "./qa-replay.js";
import { releaseGovernorInfo } from "./release-governor.js";
import { browserFleetInfo } from "./browser-fleet.js";
import { playwrightCiInfo } from "./playwright-ci.js";
import { capabilityTrustInfo,trustedCapabilities } from "./capability-trust.js";
import { previewDeploymentInfo } from "./preview-deployment.js";
import { nextGenIntegrations } from "./next-gen-integrations.js";

export async function controlCenterSnapshot(){const executions=await resolveExecutions();const artifacts=await listArtifacts();const integrations=integrationRegistry();const nextGen=nextGenIntegrations();const orchestration=await orchestrationSnapshot();const trusted=trustedCapabilities();const recipes=await listQaRecipes();const states=orchestration.rows.reduce<Record<string,number>>((acc,row)=>{const state=String((row.orchestration as Record<string,unknown>).state??"unknown");acc[state]=(acc[state]??0)+1;return acc;},{});const approvedRecipes=recipes.filter(r=>r.approved);const totalRuns=recipes.reduce((n,r)=>n+r.passCount+r.failCount,0);const totalPasses=recipes.reduce((n,r)=>n+r.passCount,0);return{schemaVersion:"1.6",app:{name:"Game Shop Control Center",resourceUri:"ui://game-shop/control-center",mcpAppsTarget:true},summary:{executions:executions.length,artifacts:artifacts.length,integrations:integrations.length+nextGen.length,mcpCapable:integrations.filter(i=>i.kinds.includes("mcp")||i.kinds.includes("desktop-mcp")).length+nextGen.filter(i=>i.kind.includes("mcp")).length,apiCapable:integrations.filter(i=>i.kinds.includes("api")).length+nextGen.filter(i=>i.kind.includes("api")).length,dynamicTrustedMcp:trusted.length,orchestrated:orchestration.count,orchestrationStates:states,qaRecipes:recipes.length,approvedQaRecipes:approvedRecipes.length,qaReplayRuns:totalRuns,qaReplayPassRate:totalRuns?totalPasses/totalRuns:null},stores:{executions:executionStoreInfo(),artifacts:artifactStoreInfo(),qaMemory:qaMemoryInfo()},tasks:taskBridgeInfo(),engines:externalEngineStatus(),qa:{worker:qaWorkerInfo(),swarm:qaSwarmInfo(),fleet:browserFleetInfo(),playwrightCi:playwrightCiInfo(),memory:{info:qaMemoryInfo(),replay:qaReplayInfo(),recentRecipes:recipes.slice(0,30)},releaseGovernor:releaseGovernorInfo()},preview:previewDeploymentInfo(),trust:{info:capabilityTrustInfo(),promoted:trusted},integrations:{catalog:integrations,nextGen},orchestration,recentExecutions:executions.slice(0,20),recentArtifacts:artifacts.slice(0,30)};}
export function controlCenterAppInfo(){return{extension:"io.modelcontextprotocol/apps",resourceUri:"ui://game-shop/control-center",status:"learning-release-governed",surfaces:["executions","tasks","artifacts","engines","integrations","persistence","placement","preview","browser-fleet","browserbase","playwright-mcp","playwright-ci","playwright-cli","chrome-devtools-mcp","qa-swarm","qa-memory","regression-replay","release-governor","verification","repair","patch-worker","capability-trust","orchestration"],pipeline:["provider","finalize","persist","assign","place","preview","browser-fleet-route","live-qa","deterministic-qa","evidence-fusion","learn-regression","replay-approved-memory","release-governor","repair-approval","patch","re-preview","re-qa","complete"],learning:["capture-green-path","propose-recipe","approve","replay-on-future-builds","track-pass-fail-history","gate-release"],expansion:["discover","inspect","sandbox-test","score","approve","promote"]};}
