type LimitClass="read"|"qa"|"execute"|"write"|"deploy"|"generation";
const memory=new Map<string,{count:number;resetAt:number}>();
function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
function classifyTool(name?:string):LimitClass{const n=name??"";if(/generate|sprite|speech|video|image|3d|render/i.test(n))return"generation";if(/deploy|preview/i.test(n))return"deploy";if(/write|upsert|patch|branch|create_project_pr/i.test(n))return"write";if(/qa|verify|diagnostic|release/i.test(n))return"qa";if(/execute|invoke|orchestrate|approve|cancel/i.test(n))return"execute";return"read";}
function limitFor(kind:LimitClass){const defaults:Record<LimitClass,number>={read:120,qa:30,execute:30,write:20,deploy:10,generation:10};const raw=Number(process.env[`GAME_SHOP_RATE_LIMIT_${kind.toUpperCase()}_PER_MINUTE`]??defaults[kind]);return Number.isFinite(raw)&&raw>0?Math.floor(raw):defaults[kind];}
function clientKey(request:Request,auth?:{mode?:string;scopes?:string[];clientId?:string;subject?:string}){if(auth?.mode==="oauth"&&auth.clientId)return`oauth:${auth.clientId}:${auth.subject??"subject"}`;if(auth?.mode==="gateway")return`gateway:${auth.clientId??"owner"}`;const forwarded=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim();return`ip:${forwarded||request.headers.get("x-real-ip")||"unknown"}`;}
function extractTool(request:Request,body?:unknown){if(request.method!=="POST")return undefined;const row=(Array.isArray(body)?body[0]:body) as Record<string,unknown>|undefined;if(!row||row.method!=="tools/call")return undefined;const params=row.params as Record<string,unknown>|undefined;return typeof params?.name==="string"?params.name:undefined;}
export function distributedRateLimitInfo(){return{backend:config()?"supabase-rpc":"memory-fallback",windowSeconds:60,classes:["read","qa","execute","write","deploy","generation"],limits:Object.fromEntries((["read","qa","execute","write","deploy","generation"] as LimitClass[]).map(k=>[k,limitFor(k)])),identity:"OAuth client_id+subject → gateway identity → IP",fallback:"in-process memory",note:"Use migration 007_rate_limit.sql to enable atomic distributed counters."};}
export async function enforceDistributedRateLimit(request:Request,auth?:{mode?:string;scopes?:string[];clientId?:string;subject?:string}){let body:unknown;try{body=request.method==="POST"?await request.clone().json():undefined}catch{}const tool=extractTool(request,body);const kind=classifyTool(tool);const limit=limitFor(kind);const key=`${clientKey(request,auth)}:${kind}`;const c=config();if(c){const r=await fetch(`${c.url}/rest/v1/rpc/game_shop_take_rate_limit`,{method:"POST",headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json"},body:JSON.stringify({p_key:key,p_limit:limit,p_window_seconds:60}),signal:AbortSignal.timeout(8000)});if(r.ok){const data=await r.json() as {allowed?:boolean;retry_after?:number;remaining?:number}|Array<{allowed?:boolean;retry_after?:number;remaining?:number}>;const row=Array.isArray(data)?data[0]:data;if(row&&row.allowed===false)return{ok:false as const,retryAfter:Math.max(1,Number(row.retry_after??60)),kind,limit,remaining:Number(row.remaining??0)};if(row)return{ok:true as const,kind,limit,remaining:Number(row.remaining??0)};}}
 const now=Date.now();const current=memory.get(key);if(!current||current.resetAt<=now){memory.set(key,{count:1,resetAt:now+60000});return{ok:true as const,kind,limit,remaining:limit-1};}if(current.count>=limit)return{ok:false as const,retryAfter:Math.max(1,Math.ceil((current.resetAt-now)/1000)),kind,limit,remaining:0};current.count++;return{ok:true as const,kind,limit,remaining:Math.max(0,limit-current.count)};}
