type StoreConfig={url:string;key:string};
function config():StoreConfig|null{const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
async function request(path:string,init:RequestInit={}){const c=config();if(!c)return null;const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init.headers||{})},signal:AbortSignal.timeout(12000)});const text=await r.text();if(!r.ok)throw new Error(`Governance store failed (${r.status}).`);return text?JSON.parse(text):null;}
const memoryEvents:Array<Record<string,unknown>>=[];const memoryBudgets=new Map<string,Record<string,unknown>>();const memoryPreviews:Array<Record<string,unknown>>=[];
export function governanceInfo(){return{durableAcrossColdStarts:Boolean(config()),backend:config()?"supabase-postgres":"process-memory-fallback",tables:["game_shop_cost_ledger","game_shop_events","game_shop_previews"],rules:{neverLogSecrets:true,budgetHardFail:true,previewCommitBinding:true}};}
export async function setExecutionBudget(input:{executionId:string;budgetUsd:number;providerBudgets?:Record<string,number>}){if(!(input.budgetUsd>=0))throw new Error("budgetUsd must be >= 0");const now=new Date().toISOString();const row={execution_id:input.executionId,budget_usd:input.budgetUsd,provider_budgets:input.providerBudgets??{},estimated_cost:0,actual_cost:0,credits_used:0,updated_at:now};memoryBudgets.set(input.executionId,row);await request("game_shop_cost_ledger?on_conflict=execution_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row)});return row;}
export async function budgetStatus(executionId:string){const data=await request(`game_shop_cost_ledger?execution_id=eq.${encodeURIComponent(executionId)}&limit=1`);const row=Array.isArray(data)&&data[0]?data[0]:memoryBudgets.get(executionId)??null;if(!row)return null;const r=row as Record<string,unknown>;const budget=Number(r.budget_usd??0),actual=Number(r.actual_cost??0),estimated=Number(r.estimated_cost??0);return{...r,remaining_budget:Math.max(0,budget-actual-estimated)};}
export async function reserveCost(input:{executionId:string;provider:string;estimatedUsd:number}){const status=await budgetStatus(input.executionId);if(!status)throw new Error("Execution budget is not configured.");const current=status as Record<string,unknown>;const remaining=Number(current.remaining_budget??0);if(input.estimatedUsd>remaining)throw new Error(`Projected spend $${input.estimatedUsd.toFixed(2)} exceeds remaining authorized budget $${remaining.toFixed(2)}.`);const actual=Number(current.actual_cost??0);const estimated=Number(current.estimated_cost??0)+input.estimatedUsd;const row:Record<string,unknown>={...current,estimated_cost:estimated,updated_at:new Date().toISOString()};memoryBudgets.set(input.executionId,row);await request(`game_shop_cost_ledger?execution_id=eq.${encodeURIComponent(input.executionId)}`,{method:"PATCH",body:JSON.stringify({estimated_cost:estimated,updated_at:row.updated_at})});await logEvent({executionId:input.executionId,type:"cost.reserved",provider:input.provider,data:{estimatedUsd:input.estimatedUsd,remainingBefore:remaining}});return{...row,remaining_budget:Math.max(0,Number(row.budget_usd??0)-actual-estimated)};}
export async function settleCost(input:{executionId:string;provider:string;actualUsd:number;reservedUsd?:number;creditsUsed?:number}){const status=await budgetStatus(input.executionId);if(!status)throw new Error("Execution budget is not configured.");const current=status as Record<string,unknown>;const estimated=Math.max(0,Number(current.estimated_cost??0)-Math.max(0,input.reservedUsd??0));const actual=Number(current.actual_cost??0)+Math.max(0,input.actualUsd);const credits=Number(current.credits_used??0)+Math.max(0,input.creditsUsed??0);const row:Record<string,unknown>={...current,estimated_cost:estimated,actual_cost:actual,credits_used:credits,updated_at:new Date().toISOString()};memoryBudgets.set(input.executionId,row);await request(`game_shop_cost_ledger?execution_id=eq.${encodeURIComponent(input.executionId)}`,{method:"PATCH",body:JSON.stringify({estimated_cost:estimated,actual_cost:actual,credits_used:credits,updated_at:row.updated_at})});await logEvent({executionId:input.executionId,type:"cost.settled",provider:input.provider,data:{actualUsd:input.actualUsd,creditsUsed:input.creditsUsed??0}});return{...row,remaining_budget:Math.max(0,Number(row.budget_usd??0)-actual-estimated)};}
function scrub(value:unknown):unknown{if(Array.isArray(value))return value.map(scrub);if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>)){if(/token|secret|authorization|api.?key|credential|cookie/i.test(k))out[k]="[redacted]";else out[k]=scrub(v);}return out;}return value;}
export async function logEvent(input:{type:string;executionId?:string;projectId?:string;clientId?:string;scope?:string[];provider?:string;latencyMs?:number;data?:Record<string,unknown>}){const row={event_id:`evt_${crypto.randomUUID()}`,type:input.type,execution_id:input.executionId??null,project_id:input.projectId??null,client_id:input.clientId??null,scope:input.scope??[],provider:input.provider??null,latency_ms:input.latencyMs??null,data:scrub(input.data??{}),created_at:new Date().toISOString()};memoryEvents.unshift(row);if(memoryEvents.length>500)memoryEvents.length=500;await request("game_shop_events",{method:"POST",body:JSON.stringify(row)});return row;}
export async function listEvents(input:{executionId?:string;projectId?:string;limit?:number}={}){const params=new URLSearchParams({order:"created_at.desc",limit:String(Math.min(100,input.limit??30))});if(input.executionId)params.set("execution_id",`eq.${input.executionId}`);if(input.projectId)params.set("project_id",`eq.${input.projectId}`);const data=await request(`game_shop_events?${params}`);if(Array.isArray(data))return data;return memoryEvents.filter(e=>(!input.executionId||e.execution_id===input.executionId)&&(!input.projectId||e.project_id===input.projectId)).slice(0,input.limit??30);}
export async function recordPreview(input:{projectId:string;branch:string;commitSha?:string;provider:string;deploymentId?:string;previewUrl?:string;status:string}){const row={preview_id:`prv_${crypto.randomUUID()}`,project_id:input.projectId,branch:input.branch,commit_sha:input.commitSha??null,provider:input.provider,deployment_id:input.deploymentId??null,preview_url:input.previewUrl??null,status:input.status,created_at:new Date().toISOString(),tested_at:null};memoryPreviews.unshift(row);await request("game_shop_previews",{method:"POST",body:JSON.stringify(row)});return row;}
export async function markPreviewTested(input:{projectId:string;commitSha:string;previewUrl:string}){const testedAt=new Date().toISOString();await request(`game_shop_previews?project_id=eq.${encodeURIComponent(input.projectId)}&commit_sha=eq.${encodeURIComponent(input.commitSha)}&preview_url=eq.${encodeURIComponent(input.previewUrl)}`,{method:"PATCH",body:JSON.stringify({tested_at:testedAt,status:"tested"})});for(const p of memoryPreviews)if(p.project_id===input.projectId&&p.commit_sha===input.commitSha&&p.preview_url===input.previewUrl){p.tested_at=testedAt;p.status="tested";}return{projectId:input.projectId,commitSha:input.commitSha,previewUrl:input.previewUrl,testedAt};}
export async function listPreviews(input:{projectId?:string;limit?:number}={}){const params=new URLSearchParams({order:"created_at.desc",limit:String(Math.min(100,input.limit??30))});if(input.projectId)params.set("project_id",`eq.${input.projectId}`);const data=await request(`game_shop_previews?${params}`);if(Array.isArray(data))return data;return memoryPreviews.filter(p=>!input.projectId||p.project_id===input.projectId).slice(0,input.limit??30);}
