import { integrationRegistry } from "./integrations.js";
import { integrationReadiness } from "./integration-runtime.js";
import { mcpInitialize, mcpListTools } from "./mcp-http-client.js";
export type HealthState="HEALTHY"|"DEGRADED"|"AUTH_REQUIRED"|"RATE_LIMITED"|"CONTRACT_CHANGED"|"OFFLINE"|"QUARANTINED";
const history=new Map<string,{toolHash?:string;state:HealthState;latencyMs?:number;checkedAt:string}>();
function hashTools(tools:string[]){let h=2166136261;for(const c of tools.sort().join("|")){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
export function integrationHealthInfo(){return{states:["HEALTHY","DEGRADED","AUTH_REQUIRED","RATE_LIMITED","CONTRACT_CHANGED","OFFLINE","QUARANTINED"],signals:["auth","reachability","protocol","tool-contract","latency","quota","cost"],routerPolicy:"Avoid OFFLINE, RATE_LIMITED, AUTH_REQUIRED and QUARANTINED engines; prefer HEALTHY over DEGRADED."};}
export async function checkIntegrationHealth(id:string){const integration=integrationRegistry().find(i=>i.id===id);if(!integration)throw new Error(`Unknown integration: ${id}`);const readiness=integrationReadiness(id)[0];if(!readiness)return{integration:id,state:"OFFLINE" as HealthState,reason:"missing-readiness"};if(readiness.env?.some((e:any)=>!e.configured))return{integration:id,state:"AUTH_REQUIRED" as HealthState,readiness,checkedAt:new Date().toISOString()};if((integration.state as string)==="quarantined")return{integration:id,state:"QUARANTINED" as HealthState,checkedAt:new Date().toISOString()};if(!integration.endpoint)return{integration:id,state:readiness.mode==="library"||readiness.mode==="installable"?"DEGRADED" as HealthState:"OFFLINE" as HealthState,reason:"no-remote-endpoint",checkedAt:new Date().toISOString()};const started=Date.now();let state:HealthState="HEALTHY";let protocol:string|undefined;let tools:string[]=[];let error:string|undefined;try{if(integration.kinds.includes("mcp")){const init=await mcpInitialize({url:integration.endpoint,timeoutMs:8000});protocol=init.protocolVersion;const listed=await mcpListTools({url:integration.endpoint,sessionId:init.sessionId,timeoutMs:8000});tools=listed.tools.map(t=>t.name);const toolHash=hashTools(tools);const prev=history.get(id);if(prev?.toolHash&&prev.toolHash!==toolHash)state="CONTRACT_CHANGED";history.set(id,{toolHash,state,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()});}else{const r=await fetch(integration.endpoint,{method:"HEAD",signal:AbortSignal.timeout(8000)});if(r.status===401||r.status===403)state="AUTH_REQUIRED";else if(r.status===429)state="RATE_LIMITED";else if(r.status>=500)state="DEGRADED";else if(!r.ok&&r.status!==405)state="OFFLINE";history.set(id,{state,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()});}}catch(e){state="OFFLINE";error=e instanceof Error?e.message:String(e);history.set(id,{state,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()});}return{integration:id,name:integration.name,state,latencyMs:Date.now()-started,protocol,toolCount:tools.length,error,checkedAt:new Date().toISOString(),readiness};}
export async function checkIntegrationNetwork(input:{ids?:string[];limit?:number}={}){const all=integrationRegistry();const chosen=(input.ids?.length?all.filter(i=>input.ids!.includes(i.id)):all.filter(i=>i.endpoint)).slice(0,input.limit??20);const results=[];for(const item of chosen)results.push(await checkIntegrationHealth(item.id));const counts=results.reduce<Record<string,number>>((a,r)=>{a[r.state]=(a[r.state]??0)+1;return a;},{});return{checked:results.length,counts,results,policy:integrationHealthInfo()};}
export function routeHealthyIntegration(candidates:string[]){const ranked=candidates.map(id=>({id,last:history.get(id)})).sort((a,b)=>{const rank=(s?:HealthState)=>s==="HEALTHY"?0:s==="DEGRADED"||s==="CONTRACT_CHANGED"?1:2;return rank(a.last?.state)-rank(b.last?.state)||(a.last?.latencyMs??999999)-(b.last?.latencyMs??999999);});return{selected:ranked.find(r=>!r.last||!["OFFLINE","AUTH_REQUIRED","RATE_LIMITED","QUARANTINED"].includes(r.last.state))?.id??null,ranked};}
