export type IntegrationKind = "mcp" | "api" | "cli" | "registry" | "library" | "desktop-mcp" | "reference";
export type IntegrationState = "ready" | "needs-auth" | "local-app-required" | "installable" | "research";
export type Integration = { id:string; name:string; kinds:IntegrationKind[]; state:IntegrationState; domains:string[]; endpoint?:string; install?:string; env?:string[]; auth?:string; capabilities:string[]; notes:string; };

// Only verified integration contracts belong here. Unknown or ambiguous products remain research-only until their official programmable surface is confirmed.
const integrations: Integration[] = [
  {id:"21st-dev",name:"21st.dev",kinds:["mcp","cli","registry"],state:"needs-auth",domains:["ui","agent-platform"],endpoint:"https://21st.dev/api/mcp",install:"npx @21st-dev/cli@latest init --client codex",env:["API_KEY_21ST"],auth:"API key/OAuth depending on client.",capabilities:["component-search","component-install","ui-generation","themes","templates","publishing","mcp-app-ui"],notes:"Use official stateless MCP/CLI; preserve catalog licensing."},
  {id:"motion-ai-kit",name:"Motion AI Kit",kinds:["mcp","cli","library"],state:"installable",domains:["motion","ui","3d"],install:"npx motion-ai@latest",capabilities:["motion-docs","example-search","transition-editor","performance-audit","css-generation","threejs-motion","motion-ui-source"],notes:"Current installer wires hosted MCP servers and /motion skill."},
  {id:"spline-mcp",name:"Spline MCP Server",kinds:["desktop-mcp","api"],state:"local-app-required",domains:["3d","ui","agent-platform"],capabilities:["create-scene","edit-scene","generate-3d","generate-image","layout","scene-code-api","realtime-api"],notes:"Official MCP runs through an open Spline desktop app; route local-capable agents to it."},
  {id:"raylight-mcp",name:"Raylight MCP",kinds:["mcp"],state:"needs-auth",domains:["video","motion","agent-platform"],endpoint:"https://api.raylight.app/mcp",auth:"OAuth/sign in with Raylight account through the MCP client; keep the Raylight project open while the agent works.",capabilities:["project-list","shot-read","shot-edit","animation-edit","render-frames","visual-review"],notes:"Official remote MCP operating against the live Raylight editor/canvas."},
  {id:"manus-api",name:"Manus API v2",kinds:["api","cli"],state:"needs-auth",domains:["agent-platform","video","ui"],endpoint:"https://api.manus.ai",install:"npx skills add https://open.manus.ai/docs --skill manus-api --agent codex --global --yes",env:["MANUS_API_KEY"],auth:"Use x-manus-api-key for account integrations or OAuth2 Bearer tokens for Open Apps.",capabilities:["task-create","task-followup","task-results","projects","files","webhooks","skills","agents","connectors","website-publish"],notes:"Use API v2 and the official live API skill."},
  {id:"manus-custom-mcp",name:"Manus Custom MCP",kinds:["mcp"],state:"ready",domains:["agent-platform"],capabilities:["custom-tools","resources","prompts","api-bridging","workflow-actions"],notes:"Manus can consume HTTPS custom MCP servers; Game Shop can be connected into Manus."},
  {id:"rive-web",name:"Rive Web Runtime",kinds:["library","api"],state:"installable",domains:["ui","motion","3d"],install:"npm install @rive-app/webgl2",capabilities:["interactive-animation","state-machines","runtime-interactivity","webgl2","game-render-loop","rive-files","wasm-runtime"],notes:"Official JavaScript/WASM runtime; use @rive-app/react-webgl2 for React projects."},
  {id:"ludo-ai",name:"Ludo AI",kinds:["mcp","api"],state:"needs-auth",domains:["ui","motion","3d","video","agent-platform"],endpoint:"https://mcp.ludo.ai/mcp",env:["LUDO_API_KEY"],auth:"Remote HTTP MCP uses Authentication: ApiKey <key>. REST base is https://api.ludo.ai/api/.",capabilities:["image-generation","sprites","spritesheets","background-removal","3d-glb","rigging","animation","music","sound-effects","voice","voice-cloning","video","generation-history","job-status","job-cancel","docs"],notes:"Game-focused generation platform. Jobs are asynchronous; use request_id for safe retries and persist generated assets because API asset URLs expire."},
  {id:"meshy",name:"Meshy",kinds:["mcp","api","cli"],state:"needs-auth",domains:["3d","agent-platform"],install:"npx -y @meshy-ai/meshy-mcp-server",env:["MESHY_API_KEY"],auth:"Meshy API key required by the official MCP server and REST API.",capabilities:["text-to-3d","image-to-3d","texturing","task-status","asset-download"],notes:"Official open-source MCP wraps Meshy REST workflows. Treat generation as paid/external work and route through Game Shop spend policy."},
  {id:"motionsites-mcp",name:"MotionSites AI MCP",kinds:["mcp"],state:"needs-auth",domains:["ui","design-reference","agent-platform"],endpoint:"https://xgdzyqfalbibzelpdpvr.supabase.co/functions/v1/mcp",auth:"OAuth/browser sign-in with MotionSites account; no static API key required by the documented setup.",capabilities:["website-design-prompts","design-reference","agent-design-guidance"],notes:"Official remote MCP exposes MotionSites premium website-design prompt library to Claude, Cursor, Codex and other MCP clients."},
  {id:"unison-brain",name:"Unison Brain",kinds:["mcp","api","cli"],state:"needs-auth",domains:["agent-platform"],endpoint:"https://brain.unisonlabs.ai",install:"npx -y @unisonlabs/mcp",env:["UNISON_TOKEN"],auth:"Authorization: Bearer usk_... for Brain HTTP API; MCP reads UNISON_TOKEN.",capabilities:["project-memory","context-recall","ingest","search","facts","knowledge-graph","remember","write","edit","status"],notes:"Strong candidate for durable cross-agent project memory. API paths are under /v1; SDK, CLI and MCP share the same brain."},
  {id:"wangp",name:"WanGP / Wan2GP",kinds:["mcp","api","cli"],state:"local-app-required",domains:["video","agent-platform"],install:"python wgp.py --mcp --mcp-transport stdio",capabilities:["model-discovery","warm-session","generation","session-reuse","streamable-http"],notes:"Official project exposes a local MCP over stdio or streamable HTTP. Keep HTTP bound to localhost unless placed behind authenticated trusted infrastructure."},
  {id:"shadergradient",name:"ShaderGradient",kinds:["library"],state:"installable",domains:["shader","3d","ui","motion"],install:"npm i @shadergradient/react @react-three/fiber three three-stdlib camera-controls",capabilities:["animated-gradients","react-renderer","threejs","webgl","shader-backgrounds","query-config","camera-control"],notes:"MIT React renderer. React/R3F versions must match the target framework; do not treat it as a remote API or MCP."},
  {id:"kokonutui",name:"KokonutUI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["component-search","component-install","registry-dependency-resolution","react-ui","motion-components"],notes:"Use official shadcn MCP and @kokonutui registry."},
  {id:"cult-ui",name:"Cult UI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["component-search","component-install","registry-browse","landing-page-ui","motion-ui"],notes:"Use shadcn MCP with official Cult UI registry; do not mirror Pro content."},
  {id:"animate-ui",name:"Animate UI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["animated-components","component-search","component-install","motion-ui"],notes:"Use standard shadcn MCP workflow."},
  {id:"preline-ui",name:"Preline UI MCP",kinds:["mcp","cli","registry"],state:"needs-auth",domains:["ui","agent-platform"],endpoint:"https://mcp.preline.co",install:"npx skills add htmlstreamofficial/preline",env:["PRELINE_API_KEY"],auth:"Authorization: Bearer TOKEN_KEY.",capabilities:["components-list","component-source","blocks","component-docs","framework-docs","themes","preline-init"],notes:"Hosted Streamable HTTP MCP; keep token in secret storage."},
  {id:"daisyui-mcp",name:"daisyUI MCP",kinds:["mcp","library"],state:"installable",domains:["ui","agent-platform"],capabilities:["daisyui-code-generation","component-guidance","theme-guidance"],notes:"Use official current MCP/code-generator setup rather than hard-coding a stale client config."},
  {id:"animejs",name:"Anime.js",kinds:["library"],state:"installable",domains:["motion","ui"],install:"npm install animejs",capabilities:["timeline","dom-animation","svg-animation","js-object-animation","stagger","drag","scroll"],notes:"Local runtime library."},
  {id:"threejs",name:"Three.js",kinds:["library"],state:"installable",domains:["3d","shader"],install:"npm install three",capabilities:["webgl","webgpu","scene","gltf","shader","postprocessing"],notes:"Local runtime library."},
  {id:"lenis",name:"Lenis",kinds:["library"],state:"installable",domains:["motion","ui","3d"],install:"npm install lenis",capabilities:["smooth-scroll","scroll-sync","webgl-scroll"],notes:"Local runtime library."},
  {id:"gsap",name:"GSAP",kinds:["library"],state:"installable",domains:["motion","ui"],install:"npm install gsap",capabilities:["timeline","scroll","svg","cinematic-motion"],notes:"Local runtime integration; respect current licensing."},
  {id:"spline-code-api",name:"Spline Code API",kinds:["api"],state:"ready",domains:["3d","ui"],capabilities:["scene-variables","object-properties","events","transitions","runtime-interactivity"],notes:"Runtime API for controlling exported Spline scenes."},
  {id:"jitter",name:"Jitter",kinds:["reference"],state:"research",domains:["video","motion"],capabilities:["motion-design","timeline-animation","ai-animation","bulk-create","video-export"],notes:"No public developer API/MCP contract verified yet; do not invent one."}
];

export function integrationRegistry(){return integrations;}
export function integrationStatus(id?:string){if(!id)return integrations;return integrations.find(i=>i.id===id)??null;}
