export type IntegrationKind = "mcp" | "api" | "cli" | "registry" | "library" | "desktop-mcp" | "reference";
export type IntegrationState = "ready" | "needs-auth" | "local-app-required" | "installable" | "research";
export type Integration = { id:string; name:string; kinds:IntegrationKind[]; state:IntegrationState; domains:string[]; endpoint?:string; install?:string; env?:string[]; auth?:string; capabilities:string[]; notes:string; };

// Only verified integration contracts belong here. Unknown or ambiguous products remain research-only until their official programmable surface is confirmed.
const integrations: Integration[] = [
{id:"magic-ui",name:"Magic UI",kinds:["mcp","cli","registry"],state:"installable",domains:["ui","motion","website","web-app"],install:"npx @magicuidesign/cli@latest install cursor",capabilities:["component-list","component-search","component-source","templates","animated-ui"],notes:"Official MCP and CLI. Client-specific install targets vary; Game Shop should install into the target project/client rather than mirror components."},
{id:"kibo-ui",name:"Kibo UI",kinds:["mcp","cli","registry"],state:"installable",domains:["ui","website","web-app"],install:"npx kibo-ui add",capabilities:["component-docs","component-install","shadcn-components","product-ui","data-ui"],notes:"Official component library with MCP support and on-demand CLI installation."},
{id:"heroui",name:"HeroUI",kinds:["mcp","cli","library"],state:"installable",domains:["ui","website","web-app","mobile-app"],install:"npx heroui-cli@latest",capabilities:["react-components","react-native-components","component-docs","project-init","install","upgrade","doctor","agent-docs"],notes:"Official React MCP package @heroui/react-mcp uses stdio; HeroUI Native also exposes an official MCP. CLI supports web projects and Native supports Expo/React Native."},
{id:"impeccable",name:"Impeccable",kinds:["cli"],state:"installable",domains:["ui","design-reference","website","web-app","mobile-app","agent-platform"],install:"npx impeccable install",capabilities:["design-context","audit","critique","polish","live-iteration","detector","design-hooks","design-system-drift","ui-verification"],notes:"Agent design skill plus deterministic detector CLI. Strong verifier/repair-loop integration; detector can run as a pre-ship quality gate."},
{id:"podium",name:"Podium",kinds:["api"],state:"needs-auth",domains:["commerce","website","web-app","mobile-app","agent-platform"],endpoint:"https://api.podium.build/api/v1",env:["PODIUM_API_KEY"],auth:"Bearer token; live keys use podium_live_ prefix and test keys use podium_test_.",capabilities:["products","creators","users","orders","payments","campaigns","rewards","companion","task-pool","search","webhooks","agentic-commerce"],notes:"Verified REST API. Useful for commerce/product infrastructure beyond games."},
{id:"skiper-ui",name:"Skiper UI",kinds:["registry","cli"],state:"installable",domains:["ui","motion","website","web-app"],install:"npx shadcn add @skiper-ui/skiper40",capabilities:["animated-components","shadcn-registry","component-install"],notes:"Verified shadcn registry. Pro installs require SKIPER_LICENSE_KEY and licensed registry access; never mirror Pro source."},
{id:"smoothui",name:"SmoothUI",kinds:["reference","registry"],state:"ready",domains:["ui","motion","website","web-app"],capabilities:["animated-react-components","ui-blocks","motion","gsap","shadcn-compatible"],notes:"Verified production-ready animated React component and block catalog; no separate public MCP/API promoted in this pass."},
{id:"unlumen-ui",name:"Unlumen UI",kinds:["reference","registry"],state:"ready",domains:["ui","motion","website","web-app"],capabilities:["react-components","shadcn-components","motion-ui","design-reference"],notes:"Verified UI library with open-source primitives and licensed Pro components. Do not redistribute paid source."},
{id:"horizonx",name:"HorizonX",kinds:["reference"],state:"ready",domains:["ui","design-reference","website","web-app"],capabilities:["ui-kits","figma","coded-templates","design-systems","commercial-assets"],notes:"Premium design/code library. Commercial use is permitted for downloaded assets under membership, but source redistribution/resale is prohibited; no public programmable API verified."},
{id:"vengeance-ui",name:"Vengeance UI",kinds:["cli","registry"],state:"installable",domains:["ui","motion","website","web-app"],capabilities:["animated-components","component-install","shader-ui","interactive-ui"],notes:"Verified animated component library with documented CLI install flows; exact component commands are selected from its docs rather than hard-coded globally."},
{id:"chatterbox-tts",name:"Chatterbox TTS",kinds:["library","cli"],state:"local-app-required",domains:["audio","website","web-app","mobile-app","game","interactive-experience"],install:"pip install chatterbox-tts",capabilities:["text-to-speech","voice-cloning","multilingual-speech","emotion-control","voice-conversion","watermarking"],notes:"Official Resemble AI open-source MIT TTS family. Local GPU/runtime integration; use only voices/reference audio the operator has permission to use."},
{id:"21st-dev",name:"21st.dev",kinds:["mcp","cli","registry"],state:"needs-auth",domains:["ui","agent-platform"],endpoint:"https://21st.dev/api/mcp",install:"npx @21st-dev/cli@latest init --client codex",env:["API_KEY_21ST"],capabilities:["component-search","component-install","ui-generation","themes","templates","publishing","mcp-app-ui"],notes:"Official MCP/CLI; preserve catalog licensing."},
{id:"motion-ai-kit",name:"Motion AI Kit",kinds:["mcp","cli","library"],state:"installable",domains:["motion","ui","3d"],install:"npx motion-ai@latest",capabilities:["motion-docs","example-search","transition-editor","performance-audit","css-generation","threejs-motion"],notes:"Installer wires hosted MCP servers and Motion skill."},
{id:"spline-mcp",name:"Spline MCP Server",kinds:["desktop-mcp","api"],state:"local-app-required",domains:["3d","ui","agent-platform"],capabilities:["create-scene","edit-scene","generate-3d","generate-image","layout","scene-code-api","realtime-api"],notes:"Official MCP runs through open Spline desktop app."},
{id:"raylight-mcp",name:"Raylight MCP",kinds:["mcp"],state:"needs-auth",domains:["video","motion","agent-platform"],endpoint:"https://api.raylight.app/mcp",auth:"OAuth through MCP client; keep Raylight project open.",capabilities:["project-list","shot-read","shot-edit","animation-edit","render-frames","visual-review"],notes:"Official remote MCP."},
{id:"manus-api",name:"Manus API v2",kinds:["api","cli"],state:"needs-auth",domains:["agent-platform","video","ui"],endpoint:"https://api.manus.ai",install:"npx skills add https://open.manus.ai/docs --skill manus-api --agent codex --global --yes",env:["MANUS_API_KEY"],capabilities:["task-create","task-followup","task-results","projects","files","webhooks","skills","agents","connectors","website-publish"],notes:"Use API v2 and official skill."},
{id:"manus-custom-mcp",name:"Manus Custom MCP",kinds:["mcp"],state:"ready",domains:["agent-platform"],capabilities:["custom-tools","resources","prompts","api-bridging","workflow-actions"],notes:"Game Shop can itself be connected into Manus."},
{id:"rive-web",name:"Rive Web Runtime",kinds:["library","api"],state:"installable",domains:["ui","motion","3d","website","web-app","mobile-app","game"],install:"npm install @rive-app/webgl2",capabilities:["interactive-animation","state-machines","runtime-interactivity","webgl2","rive-files","wasm-runtime"],notes:"Official JavaScript/WASM runtime; Rive artifacts are first-class Game Shop artifact candidates."},
{id:"ludo-ai",name:"Ludo AI",kinds:["mcp","api"],state:"needs-auth",domains:["ui","motion","3d","video","agent-platform"],endpoint:"https://mcp.ludo.ai/mcp",env:["LUDO_API_KEY"],auth:"Remote HTTP MCP: Authentication: ApiKey <key>; REST base https://api.ludo.ai/api/.",capabilities:["image-generation","sprites","spritesheets","background-removal","3d-glb","rigging","animation","music","sound-effects","voice","voice-cloning","video","generation-history","job-status","job-cancel","docs"],notes:"Async multimodal generation; request_id supports safe retries."},
{id:"meshy",name:"Meshy",kinds:["mcp","api","cli"],state:"needs-auth",domains:["3d","agent-platform"],endpoint:"https://api.meshy.ai",env:["MESHY_API_KEY"],auth:"Bearer API key.",capabilities:["text-to-3d","image-to-3d","texturing","task-status","asset-download"],notes:"Official MCP and REST API."},
{id:"fal-ai",name:"fal",kinds:["mcp","api","cli"],state:"needs-auth",domains:["ui","motion","3d","video","audio","agent-platform"],endpoint:"https://mcp.fal.ai/mcp",env:["FAL_KEY"],capabilities:["model-search","schema-inspection","inference","file-upload","image","video","audio","3d","queue","webhooks"],notes:"Hosted MCP plus durable queue API."},
{id:"replicate",name:"Replicate",kinds:["mcp","api","cli"],state:"needs-auth",domains:["ui","motion","3d","video","audio","agent-platform"],endpoint:"https://mcp.replicate.com",env:["REPLICATE_API_TOKEN"],capabilities:["model-search","predictions","image","video","audio","3d","upscaling"],notes:"Official MCP mirrors HTTP API."},
{id:"elevenlabs",name:"ElevenLabs",kinds:["mcp","api"],state:"needs-auth",domains:["audio","video","agent-platform","website","web-app","mobile-app","game"],endpoint:"https://api.elevenlabs.io/v1/mcp",env:["ELEVENLABS_API_KEY"],capabilities:["speech","voices","sound-effects","music","image-generation","video-generation","agents"],notes:"Hosted MCP and media APIs."},
{id:"scenario",name:"Scenario",kinds:["api"],state:"needs-auth",domains:["ui","3d","video","audio","agent-platform"],env:["SCENARIO_API_KEY"],capabilities:["image-generation","video","3d","audio","textures","skyboxes","model-training","inpainting","outpainting","background-removal","upscaling","asset-management"],notes:"Verified REST/OpenAPI surface."},
{id:"cloudinary",name:"Cloudinary",kinds:["api","cli"],state:"needs-auth",domains:["ui","video","audio","website","web-app","mobile-app","agent-platform"],env:["CLOUDINARY_URL"],capabilities:["asset-upload","asset-management","image-transform","video-transform","optimization","delivery","analysis"],notes:"Artifact lifecycle and delivery layer."},
{id:"motionsites-mcp",name:"MotionSites AI MCP",kinds:["mcp"],state:"needs-auth",domains:["ui","design-reference","agent-platform"],endpoint:"https://xgdzyqfalbibzelpdpvr.supabase.co/functions/v1/mcp",capabilities:["website-design-prompts","design-reference","agent-design-guidance"],notes:"Official remote MCP."},
{id:"unison-brain",name:"Unison Brain",kinds:["mcp","api","cli"],state:"needs-auth",domains:["agent-platform"],endpoint:"https://brain.unisonlabs.ai",install:"npx -y @unisonlabs/mcp",env:["UNISON_TOKEN"],capabilities:["project-memory","context-recall","ingest","search","facts","knowledge-graph","remember","write","edit","status"],notes:"Candidate cross-agent project memory."},
{id:"wangp",name:"WanGP / Wan2GP",kinds:["mcp","api","cli"],state:"local-app-required",domains:["video","agent-platform"],install:"python wgp.py --mcp --mcp-transport stdio",capabilities:["model-discovery","warm-session","generation","session-reuse","streamable-http"],notes:"Local MCP over stdio or Streamable HTTP."},
{id:"shadergradient",name:"ShaderGradient",kinds:["library"],state:"installable",domains:["shader","3d","ui","motion"],install:"npm i @shadergradient/react @react-three/fiber three three-stdlib camera-controls",capabilities:["animated-gradients","react-renderer","threejs","webgl","shader-backgrounds"],notes:"MIT React renderer."},
{id:"kokonutui",name:"KokonutUI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["component-search","component-install","react-ui","motion-components"],notes:"Official shadcn workflow."},
{id:"cult-ui",name:"Cult UI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["component-search","component-install","registry-browse","motion-ui"],notes:"Do not mirror Pro content."},
{id:"animate-ui",name:"Animate UI",kinds:["mcp","registry","cli"],state:"installable",domains:["ui","motion"],install:"npx shadcn@latest mcp init --client codex",capabilities:["animated-components","component-search","component-install","motion-ui"],notes:"Standard shadcn MCP workflow."},
{id:"preline-ui",name:"Preline UI MCP",kinds:["mcp","cli","registry"],state:"needs-auth",domains:["ui","agent-platform"],endpoint:"https://mcp.preline.co",install:"npx skills add htmlstreamofficial/preline",env:["PRELINE_API_KEY"],capabilities:["components-list","component-source","blocks","component-docs","themes"],notes:"Hosted Streamable HTTP MCP."},
{id:"daisyui-mcp",name:"daisyUI MCP",kinds:["mcp","library"],state:"installable",domains:["ui","agent-platform"],capabilities:["daisyui-code-generation","component-guidance","theme-guidance"],notes:"Official MCP/code-generator setup."},
{id:"animejs",name:"Anime.js",kinds:["library"],state:"installable",domains:["motion","ui"],install:"npm install animejs",capabilities:["timeline","dom-animation","svg-animation","js-object-animation","stagger","drag","scroll"],notes:"Local runtime."},
{id:"threejs",name:"Three.js",kinds:["library"],state:"installable",domains:["3d","shader"],install:"npm install three",capabilities:["webgl","webgpu","scene","gltf","shader","postprocessing"],notes:"Local runtime."},
{id:"lenis",name:"Lenis",kinds:["library"],state:"installable",domains:["motion","ui","3d"],install:"npm install lenis",capabilities:["smooth-scroll","scroll-sync","webgl-scroll"],notes:"Local runtime."},
{id:"gsap",name:"GSAP",kinds:["library"],state:"installable",domains:["motion","ui"],install:"npm install gsap",capabilities:["timeline","scroll","svg","cinematic-motion"],notes:"Respect current licensing."},
{id:"spline-code-api",name:"Spline Code API",kinds:["api"],state:"ready",domains:["3d","ui"],capabilities:["scene-variables","object-properties","events","transitions","runtime-interactivity"],notes:"Controls exported Spline scenes."},
{id:"jitter",name:"Jitter",kinds:["reference"],state:"research",domains:["video","motion"],capabilities:["motion-design","timeline-animation","ai-animation","bulk-create","video-export"],notes:"No public developer API/MCP contract verified yet."}
];
export function integrationRegistry(){return integrations;}
export function integrationStatus(id?:string){if(!id)return integrations;return integrations.find(i=>i.id===id)??null;}
