import { listProjects } from "./projects.js";
import { getProjectV2 } from "./project-registry-v2.js";

export type MissionProductKind="game"|"website"|"app"|"media";
export type MissionProjectSource=
 |{kind:"github";repo:string;root:string;branch:string}
 |{kind:"lovable";projectId:string;workspaceId:string;previewUrl?:string;publishedUrl?:string};
export type MissionProject={projectId:string;name:string;productKind:MissionProductKind;description?:string;framework?:string;runtime?:string;source:MissionProjectSource;deployment?:{provider:string;project?:string;url?:string};tags?:string[]};

const BUILTIN:MissionProject[]=[
 {projectId:"thegreishow-site",name:"TheGreiShow.com",productKind:"website",description:"The Grei Show artist/creative portal and arcade host.",source:{kind:"github",repo:"thegreishow/thegreishow.com",root:".",branch:"main"},deployment:{provider:"cloudflare-pages",url:"https://thegreishow.com"},tags:["artist","portfolio","arcade"]},
 {projectId:"cruber",name:"Cruber",productKind:"app",description:"Work and Connect temporary-staff marketplace.",source:{kind:"github",repo:"thegreishow/cruber",root:".",branch:"main"},deployment:{provider:"vercel",url:"https://cruberapp.com"},tags:["marketplace","web-app","supabase"]},
 {projectId:"jukebaxx",name:"JukeBaxx",productKind:"app",description:"Vinyl bidding application.",source:{kind:"github",repo:"thegreishow/Jukebaxx",root:".",branch:"main"},deployment:{provider:"git-connected"},tags:["marketplace","music","web-app"]},
 {projectId:"watadash",name:"WataDash",productKind:"app",description:"Jamaica-first water delivery marketplace.",source:{kind:"lovable",projectId:"6016e841-db8b-4f9d-bd5c-2f80a6455d02",workspaceId:"ajwzIQ6wCwY7EfYa3CAi",previewUrl:"https://id-preview--6016e841-db8b-4f9d-bd5c-2f80a6455d02.lovable.app",publishedUrl:"https://watadash.lovable.app"},deployment:{provider:"lovable",project:"watadash",url:"https://watadash.lovable.app"},tags:["marketplace","jamaica","delivery"]},
 {projectId:"watadash-game",name:"Wata Dash Game",productKind:"game",description:"WataDash: Kingston Run browser driving/delivery game.",framework:"phaser",runtime:"browser",source:{kind:"lovable",projectId:"2a6667e9-1c53-4b51-94b0-f7b30186821b",workspaceId:"ajwzIQ6wCwY7EfYa3CAi",previewUrl:"https://id-preview--2a6667e9-1c53-4b51-94b0-f7b30186821b.lovable.app"},deployment:{provider:"lovable-preview",project:"kingston-run-play"},tags:["phaser","jamaica","driving"]},
 {projectId:"game-shop-mcp",name:"Game Shop",productKind:"app",description:"Universal production orchestration MCP and browser control room.",framework:"vanilla+typescript",runtime:"vercel",source:{kind:"github",repo:"thegreishow/game-shop-mcp",root:".",branch:"main"},deployment:{provider:"vercel",project:"game-shop-mcp",url:"https://game-shop-mcp.vercel.app/console"},tags:["mcp","orchestration","control-room"]},
];

function gameProjects():MissionProject[]{return listProjects().map(p=>({projectId:p.id,name:p.name??p.id,productKind:"game" as const,framework:p.framework,runtime:"browser",description:p.notes,source:{kind:"github" as const,repo:p.repo,root:p.projectPath||p.gamePath||".",branch:p.defaultBranch},deployment:{provider:"site-host",url:`https://thegreishow.com/${(p.projectPath||p.gamePath||"").replace(/^\/+/,"")}`},tags:[p.artStyle,"arcade"].filter(Boolean) as string[]}));}
export function listMissionProjects(){const rows=[...BUILTIN,...gameProjects()];const seen=new Set<string>();return rows.filter(p=>!seen.has(p.projectId)&&seen.add(p.projectId));}
export function getMissionProject(projectId:string){const project=listMissionProjects().find(p=>p.projectId===projectId);if(!project)throw new Error("Mission Control project not found.");return project;}

function githubToken(){return process.env.GAME_SHOP_GITHUB_TOKEN||process.env.GITHUB_TOKEN||null;}
async function githubApi(path:string){const token=githubToken();if(!token)return null;const response=await fetch(`https://api.github.com${path}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","User-Agent":"game-shop-mcp"},signal:AbortSignal.timeout(10000)});if(!response.ok)return{ok:false,status:response.status};return{ok:true,status:response.status,data:await response.json() as Record<string,unknown>};}
async function githubTextFile(source:Extract<MissionProjectSource,{kind:"github"}>,path:string){const root=source.root==="."?"":source.root.replace(/^\/+|\/+$/g,"");const full=[root,path].filter(Boolean).join("/");const r=await githubApi(`/repos/${source.repo}/contents/${encodeURI(full)}?ref=${encodeURIComponent(source.branch)}`);if(!r?.ok||!r.data)return null;const content=typeof r.data.content==="string"?r.data.content.replace(/\s/g,""):"";if(!content)return null;try{return Buffer.from(content,"base64").toString("utf8");}catch{return null;}}
async function detectFramework(project:MissionProject){if(project.framework)return project.framework;if(project.source.kind!=="github")return project.productKind==="app"?"lovable-react":"provider-managed";const text=await githubTextFile(project.source,"package.json");if(!text)return undefined;try{const pkg=JSON.parse(text) as Record<string,any>,deps={...(pkg.dependencies??{}),...(pkg.devDependencies??{})};if(deps.expo)return"expo";if(deps.next)return"next";if(deps.phaser)return"phaser";if(deps.vue)return"vue";if(deps.react&&deps.vite)return"react-vite";if(deps.react)return"react";return"node";}catch{return undefined;}}
async function githubSnapshot(project:MissionProject){if(project.source.kind!=="github")return{kind:project.source.kind,liveInspection:"client-connector",projectId:project.source.projectId,previewUrl:project.source.previewUrl??null,publishedUrl:project.source.publishedUrl??null};const repo=await githubApi(`/repos/${project.source.repo}`);const commit=await githubApi(`/repos/${project.source.repo}/commits/${encodeURIComponent(project.source.branch)}`);return{kind:"github",configured:Boolean(githubToken()),repo:project.source.repo,root:project.source.root,branch:project.source.branch,repository:repo?.ok?{defaultBranch:repo.data?.default_branch,visibility:repo.data?.visibility,pushedAt:repo.data?.pushed_at,updatedAt:repo.data?.updated_at}:repo,latestCommit:commit?.ok?{sha:commit.data?.sha,htmlUrl:commit.data?.html_url}:commit};}

export function projectSpecialists(project:MissionProject){
 if(project.productKind==="game")return["Game Shop","Game Studio","Game Development Studio","Build 3D Game Rooms","Unity","Yoroll","GitHub","Playwright"];
 if(project.productKind==="website")return["Game Shop","React Bits / shadcn / UI lane","Motion / GSAP","Supabase","Stripe","Cloudinary","Three.js / Spline","Playwright","Chrome DevTools","GitHub"];
 if(project.productKind==="media")return["Game Shop","ElevenLabs","Cloudinary","Jitter","Yoroll","Motion / GSAP","Media QA"];
 return["Game Shop","Expo / React Native","Lovable","Supabase","Stripe","Playwright","Chrome DevTools","GitHub"];
}

export async function missionProjectSourceSnapshot(projectId:string){const project=getMissionProject(projectId);const [source,framework,enrichment]=await Promise.all([githubSnapshot(project),detectFramework(project),getProjectV2(projectId).catch(()=>null)]);return{project:{...project,framework:enrichment?.framework||framework||project.framework},source,enrichment:enrichment?{framework:enrichment.framework,deploymentProvider:enrichment.deploymentProvider,deploymentProject:enrichment.deploymentProject,qaPolicy:enrichment.qaPolicy,requiredRegressions:enrichment.requiredRegressions,permissionProfile:enrichment.permissionProfile,budgetProfile:enrichment.budgetProfile,brandContext:enrichment.brandContext}:null,specialists:projectSpecialists(project)};}

export function missionProjectRegistryInfo(){return{version:3,role:"cross-product Mission Control registry",sources:["github","lovable"],productKinds:["game","website","app","media"],builtins:BUILTIN.map(p=>p.projectId),arcadeProjects:"hydrated from canonical thegreishow.com arcade registry",v2Enrichment:"applied when present; never allowed to silently replace source identity"};}
