import { Buffer } from "node:buffer";
import { getMissionProject, type MissionProjectSource } from "./mission-projects.js";
import { resolveExecution, updateExecution, type StoredExecution } from "./execution-store.js";
import { logEvent } from "./governance-ledger.js";
import { upsertQaEvidence } from "./qa-evidence.js";

const MAX_TREE_FILES=900,MAX_SELECTED_FILES=8,MAX_SELECTED_BYTES=240_000,MAX_PATCH_FILES=6,MAX_PATCH_BYTES=350_000;
const BLOCKED_PATH=/(^|\/)(\.env(?:\.|$)|\.git\/|node_modules\/|dist\/|build\/|\.next\/|coverage\/|.*\.(?:pem|key|p12|pfx|jks)$)/i;
const TEXT_EXT=/\.(?:[cm]?[jt]sx?|html?|css|scss|sass|less|json|md|mdx|yaml|yml|toml|txt|sql|graphql|gql|py|rb|php|java|kt|swift|go|rs|sh|vue|svelte)$/i;
type GitSource=Extract<MissionProjectSource,{kind:"github"}>;
type AgentOperation={path:string;content:string;reason?:string};
type MissionPacketLike={mission?:{brief?:string;phase?:string;lane?:string};route?:Record<string,unknown>};
type CodeRuntime={provider:"vercel-ai-gateway"|"openai-direct";token:string;endpoint:string;model:string};

function githubToken(){return process.env.GAME_SHOP_GITHUB_TOKEN?.trim()||process.env.GITHUB_TOKEN?.trim()||"";}
function emergencyDisabled(){return process.env.GAME_SHOP_DISABLE_REAL_MISSIONS==="true";}
function codeRuntime():CodeRuntime|null{const gateway=process.env.AI_GATEWAY_API_KEY?.trim()||process.env.VERCEL_OIDC_TOKEN?.trim()||"";if(gateway)return{provider:"vercel-ai-gateway",token:gateway,endpoint:"https://ai-gateway.vercel.sh/v1/responses",model:process.env.GAME_SHOP_CODE_MODEL?.trim()||"openai/gpt-5.6-sol"};const direct=process.env.OPENAI_API_KEY?.trim()||"";if(!direct)return null;return{provider:"openai-direct",token:direct,endpoint:"https://api.openai.com/v1/responses",model:(process.env.GAME_SHOP_CODE_MODEL?.trim()||"gpt-5.6-sol").replace(/^openai\//,"")};}
export function missionCodeAgentStatus(){const runtime=codeRuntime();return{available:Boolean(githubToken()&&runtime&&!emergencyDisabled()),githubConfigured:Boolean(githubToken()),codeModelConfigured:Boolean(runtime),codeModelProvider:runtime?.provider??null,model:runtime?.model??"openai/gpt-5.6-sol",vercelOidcAvailable:Boolean(process.env.VERCEL_OIDC_TOKEN?.trim()),aiGatewayKeyConfigured:Boolean(process.env.AI_GATEWAY_API_KEY?.trim()),openAiFallbackConfigured:Boolean(process.env.OPENAI_API_KEY?.trim()),emergencyDisabled:emergencyDisabled(),branchPolicy:"gameshop/*",maxSelectedFiles:MAX_SELECTED_FILES,maxPatchFiles:MAX_PATCH_FILES,authorization:"OAuth gameshop.execute + gameshop.write, plus explicit per-run model-spend confirmation.",note:emergencyDisabled()?"Real missions are disabled by GAME_SHOP_DISABLE_REAL_MISSIONS=true.":"Uses Vercel AI Gateway/OIDC when available and direct OpenAI only as fallback. Writes are isolated to a verified gameshop/* branch and PR."};}
function ghHeaders(){const token=githubToken();if(!token)throw new Error("Real execution blocked: GitHub runtime credentials are not configured.");return{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"game-shop-mcp"};}
async function gh(path:string,init:RequestInit={}){const response=await fetch(`https://api.github.com${path}`,{...init,headers:{...ghHeaders(),...(init.headers||{})},signal:AbortSignal.timeout(20_000)});const text=await response.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{}if(!response.ok)throw new Error(`${body?.message||"GitHub request failed"} (${response.status}).`);return body;}
function rootOf(source:GitSource){return source.root==="."?"":source.root.replace(/^\/+|\/+$/g,"");}
function safeRelative(path:string){const clean=path.replace(/^\/+|\/+$/g,"");if(!clean||clean.includes("..")||BLOCKED_PATH.test(clean))throw new Error(`Unsafe code-agent path: ${path}`);return clean;}
function fullPath(source:GitSource,relative:string){return[rootOf(source),safeRelative(relative)].filter(Boolean).join("/");}
function relativePath(source:GitSource,full:string){const root=rootOf(source);if(!root)return full;if(full===root)return"";return full.startsWith(`${root}/`)?full.slice(root.length+1):"";}
function packetFrom(execution:StoredExecution){const row=[...execution.operationResults].reverse().find(value=>value.kind==="mission.packet");return row?.packet as MissionPacketLike|undefined;}
function jsonFromText(text:string){const cleaned=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/```$/," ").trim(),start=cleaned.indexOf("{"),end=cleaned.lastIndexOf("}");if(start<0||end<start)throw new Error("Code agent returned no JSON object.");return JSON.parse(cleaned.slice(start,end+1));}
function responseText(body:any){if(typeof body?.output_text==="string"&&body.output_text.trim())return body.output_text;const out:string[]=[];for(const item of Array.isArray(body?.output)?body.output:[])for(const part of Array.isArray(item?.content)?item.content:[])if(typeof part?.text==="string")out.push(part.text);return out.join("\n");}
async function ai(prompt:string){const runtime=codeRuntime();if(!runtime)throw new Error("Real execution blocked: no Vercel AI Gateway/OIDC or OpenAI code-model credential is available.");const started=Date.now();const payload:any={model:runtime.model,input:[{type:"message",role:"user",content:prompt}],reasoning:{effort:"medium"},max_output_tokens:24000};if(runtime.provider==="vercel-ai-gateway")payload.providerOptions={gateway:{disallowPromptTraining:true}};const response=await fetch(runtime.endpoint,{method:"POST",headers:{Authorization:`Bearer ${runtime.token}`,"content-type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(120_000)});const text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}if(!response.ok)throw new Error(`Code model request failed (${response.status}): ${body?.error?.message||text.slice(0,300)}`);const output=responseText(body);if(!output.trim())throw new Error("Code model returned no text output.");return{output,model:runtime.model,provider:runtime.provider,latencyMs:Date.now()-started,responseId:body?.id??null,usage:body?.usage??null};}
async function repoTree(source:GitSource){const tree=await gh(`/repos/${source.repo}/git/trees/${encodeURIComponent(source.branch)}?recursive=1`);const root=rootOf(source);return(Array.isArray(tree?.tree)?tree.tree:[]).filter((x:any)=>x?.type==="blob"&&typeof x.path==="string").map((x:any)=>({path:String(x.path),size:Number(x.size||0)})).filter((x:any)=>{const relative=relativePath(source,x.path);return Boolean(relative)&&(!root||x.path.startsWith(`${root}/`))&&x.size<=120_000&&!BLOCKED_PATH.test(relative)&&TEXT_EXT.test(relative);}).slice(0,MAX_TREE_FILES);}
async function readFile(source:GitSource,relative:string){const full=fullPath(source,relative);const row=await gh(`/repos/${source.repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(source.branch)}`);if(row?.type!=="file"||typeof row.content!=="string")throw new Error(`Code-agent file is not readable: ${relative}`);return{path:relative,content:Buffer.from(row.content.replace(/\s/g,""),"base64").toString("utf8")};}
async function createBranch(source:GitSource,branch:string){const base=await gh(`/repos/${source.repo}/git/ref/heads/${encodeURIComponent(source.branch)}`),sha=String(base?.object?.sha||"");if(!sha)throw new Error("Could not resolve project base branch SHA.");try{await gh(`/repos/${source.repo}/git/refs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${branch}`,sha})});}catch(error){if(!/422|already exists|reference already exists/i.test(error instanceof Error?error.message:String(error)))throw error;const current=await gh(`/repos/${source.repo}/git/ref/heads/${encodeURIComponent(branch)}`);if(String(current?.object?.sha||"")!==sha)throw new Error("Mission branch already exists with different content. Create a new mission instead of overwriting it.");}return sha;}
async function applyFile(source:GitSource,branch:string,operation:AgentOperation){const full=fullPath(source,operation.path);let sha:string|undefined;try{const current=await gh(`/repos/${source.repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(branch)}`);if(current?.type==="file"&&typeof current.sha==="string")sha=current.sha;}catch(error){if(!/404/.test(error instanceof Error?error.message:String(error)))throw error;}const payload:any={message:`Game Shop mission: ${operation.reason||operation.path}`,content:Buffer.from(operation.content,"utf8").toString("base64"),branch};if(sha)payload.sha=sha;const out=await gh(`/repos/${source.repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{path:operation.path,commitSha:out?.commit?.sha??null};}
async function verify(source:GitSource,branch:string){const compare=await gh(`/repos/${source.repo}/compare/${encodeURIComponent(source.branch)}...${encodeURIComponent(branch)}`),changed=(Array.isArray(compare?.files)?compare.files:[]).map((f:any)=>String(f.filename||"")),root=rootOf(source),escaped=root?changed.filter((f:string)=>f!==root&&!f.startsWith(`${root}/`)):[];return{status:String(compare?.status||"unknown"),aheadBy:Number(compare?.ahead_by||0),changedFiles:changed,escapedFiles:escaped,scopeSafe:escaped.length===0,passed:changed.length>0&&escaped.length===0&&!['behind','diverged'].includes(String(compare?.status||""))};}
async function openPr(source:GitSource,branch:string,title:string,body:string){const row=await gh(`/repos/${source.repo}/pulls`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,body,head:branch,base:source.branch})});return{number:row?.number??null,url:row?.html_url??null};}
function selectionPrompt(input:{brief:string;phase:string;lane:string;tree:Array<{path:string;size:number}>;framework?:string;root:string}){return`You are Game Shop's code-planning stage. Select the smallest existing text-file set needed to implement this mission.\nMISSION: ${input.brief}\nPHASE: ${input.phase}\nLANE: ${input.lane}\nFRAMEWORK: ${input.framework||"unknown"}\nROOT: ${input.root}\nFILES:\n${input.tree.map(x=>`${x.path} (${x.size} bytes)`).join("\n")}\nReturn ONLY JSON {"paths":["path"],"rationale":"short text"}. At most ${MAX_SELECTED_FILES} files. Prefer directly relevant entrypoints/components/styles/config; avoid generated files, assets, secrets, lockfiles and rewrites.`;}
function patchPrompt(input:{brief:string;phase:string;lane:string;framework?:string;route?:Record<string,unknown>;files:Array<{path:string;content:string}>}){return`You are Game Shop's implementation stage. Produce a SMALL, WORKING patch using the supplied project files. Preserve the existing stack and behavior unless the mission explicitly requires a change. Never fabricate credentials or placeholder functionality.\nMISSION: ${input.brief}\nPHASE: ${input.phase}\nLANE: ${input.lane}\nFRAMEWORK: ${input.framework||"unknown"}\nROUTED PLAN: ${JSON.stringify(input.route||{})}\n${input.files.map(f=>`\n--- ${f.path} ---\n${f.content}`).join("\n")}\nReturn ONLY JSON {"summary":"what changed","operations":[{"path":"relative/path","content":"complete UTF-8 replacement content","reason":"why"}],"notes":["optional note"]}. Maximum ${MAX_PATCH_FILES} operations. If safe implementation needs other context, return no operations and explain in notes.`;}

export async function runMissionCodeAgent(input:{executionId:string;confirmModelSpend:boolean}){
 if(input.confirmModelSpend!==true)throw new Error("Real mission execution requires explicit confirmation that code-model usage may incur provider charges.");
 const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const packet=packetFrom(execution);if(!packet)throw new Error("Execution is not a Mission Control job.");const project=getMissionProject(execution.projectId),source=project.source;if(source.kind!=="github")return{status:"client-action-required",executionId:execution.executionId,projectId:project.projectId,target:source.kind==="lovable"?"Lovable":"project specialist",reason:"This project is provider-managed; the Vercel code agent currently executes only against GitHub-backed Mission projects."};
 const readiness=missionCodeAgentStatus();if(!readiness.available)return{status:"blocked",executionId:execution.executionId,projectId:project.projectId,readiness};const runtime=codeRuntime();if(!runtime)throw new Error("Code-model runtime is unavailable.");const brief=String(packet.mission?.brief||"").trim();if(!brief)throw new Error("Mission brief is missing.");const phase=String(packet.mission?.phase||"upgrade"),lane=String(packet.mission?.lane||project.productKind);
 await updateExecution(execution.executionId,{mode:"execute",status:"running",operationResults:[...execution.operationResults,{kind:"mission.code-agent.started",at:new Date().toISOString(),model:runtime.model,provider:runtime.provider}]});await logEvent({type:"mission.code-agent.started",executionId:execution.executionId,projectId:project.projectId,provider:runtime.provider,data:{model:runtime.model,repo:source.repo,phase,lane}}).catch(()=>{});
 try{const tree=await repoTree(source);if(!tree.length)throw new Error("No readable source files were found in the registered project root.");const selector=await ai(selectionPrompt({brief,phase,lane,tree:tree.map((x:any)=>({path:relativePath(source,x.path),size:x.size})),framework:project.framework,root:source.root})),selection=jsonFromText(selector.output),requested=Array.isArray(selection?.paths)?selection.paths.map((x:any)=>String(x)).slice(0,MAX_SELECTED_FILES):[],allowed=new Set(tree.map((x:any)=>relativePath(source,x.path))),paths=requested.filter((p:string)=>allowed.has(p)&&!BLOCKED_PATH.test(p));if(!paths.length)throw new Error("Code agent did not select any valid project files.");
  const files:Array<{path:string;content:string}>=[];let bytes=0;for(const path of paths){const file=await readFile(source,path);bytes+=Buffer.byteLength(file.content,"utf8");if(bytes>MAX_SELECTED_BYTES)break;files.push(file);}if(!files.length)throw new Error("Selected project files exceeded the safe context limit.");
  const patchCall=await ai(patchPrompt({brief,phase,lane,framework:project.framework,route:packet.route,files})),patch=jsonFromText(patchCall.output),rawOps=Array.isArray(patch?.operations)?patch.operations.slice(0,MAX_PATCH_FILES):[],operations:AgentOperation[]=rawOps.map((op:any)=>({path:String(op?.path||""),content:String(op?.content||""),reason:op?.reason?String(op.reason):undefined})).filter((op:AgentOperation)=>op.path&&op.content&&!BLOCKED_PATH.test(op.path));if(!operations.length){const current=await resolveExecution(execution.executionId)||execution;await updateExecution(execution.executionId,{status:"input_required",operationResults:[...current.operationResults,{kind:"mission.code-agent.input-required",at:new Date().toISOString(),notes:Array.isArray(patch?.notes)?patch.notes:[]}]});return{status:"input-required",executionId:execution.executionId,projectId:project.projectId,summary:String(patch?.summary||"No safe code changes were produced."),notes:Array.isArray(patch?.notes)?patch.notes:[],selectedFiles:files.map(f=>f.path)};}
  let patchBytes=0;for(const op of operations){safeRelative(op.path);patchBytes+=Buffer.byteLength(op.content,"utf8");if(Buffer.byteLength(op.content,"utf8")>120_000)throw new Error(`Generated file is too large: ${op.path}`);}if(patchBytes>MAX_PATCH_BYTES)throw new Error("Generated patch exceeds the safe total size limit.");const branch=`gameshop/mission-${execution.executionId.replace(/[^a-z0-9-]/gi,"-").slice(-32).toLowerCase()}`,baseSha=await createBranch(source,branch),applied=[];for(const operation of operations)applied.push(await applyFile(source,branch,operation));const verification=await verify(source,branch);if(!verification.passed)throw new Error(`Generated branch failed scope verification: ${verification.escapedFiles.join(", ")||verification.status}`);
  const title=`Game Shop: ${brief.slice(0,72)}`,pr=await openPr(source,branch,title,`Automated Mission Control implementation.\n\nMission: ${brief}\n\nSummary: ${String(patch?.summary||"Generated project-scoped implementation.")}\n\nVerification: scope-safe ${verification.changedFiles.length}-file change on ${branch}.\n\nThis PR still requires independent QA/release approval.`),evidence=await upsertQaEvidence({projectId:project.projectId,executionId:execution.executionId,provider:"github-scope",commitSha:String(applied[applied.length-1]?.commitSha||baseSha),status:"passed",evidence:{branch,base:source.branch,repo:source.repo,changedFiles:verification.changedFiles,scopeSafe:true,prUrl:pr.url,summary:String(patch?.summary||"")}}),current=await resolveExecution(execution.executionId)||execution,result={kind:"mission.code-agent.completed",at:new Date().toISOString(),provider:patchCall.provider,model:patchCall.model,branch,baseSha,selectedFiles:files.map(f=>f.path),applied,verification,pr,summary:String(patch?.summary||""),notes:Array.isArray(patch?.notes)?patch.notes:[],qaEvidenceId:evidence.evidenceId};await updateExecution(execution.executionId,{mode:"execute",status:"running",completedOperations:Math.min(current.totalOperations,Math.max(current.completedOperations,1)),operationResults:[...current.operationResults,result]});await logEvent({type:"mission.code-agent.completed",executionId:execution.executionId,projectId:project.projectId,provider:patchCall.provider,data:{model:patchCall.model,branch,prUrl:pr.url,changedFiles:verification.changedFiles,responseIds:[selector.responseId,patchCall.responseId].filter(Boolean)}}).catch(()=>{});return{status:"implemented",executionId:execution.executionId,projectId:project.projectId,branch,pr,verification,summary:result.summary,notes:result.notes,selectedFiles:result.selectedFiles,qaEvidenceId:evidence.evidenceId,modelProvider:patchCall.provider,nextAction:"Review the generated PR/preview, run automatic QA, then approve or repair before release."};
 }catch(error){const message=error instanceof Error?error.message:String(error),current=await resolveExecution(execution.executionId)||execution;await updateExecution(execution.executionId,{status:"failed",lastError:message,operationResults:[...current.operationResults,{kind:"mission.code-agent.failed",at:new Date().toISOString(),message}]});await logEvent({type:"mission.code-agent.failed",executionId:execution.executionId,projectId:project.projectId,provider:runtime.provider,data:{message}}).catch(()=>{});throw error;}
}
