import { Buffer } from "node:buffer";
import { getMissionProject } from "./mission-projects.js";
import { resolveExecution, updateExecution, type StoredExecution } from "./execution-store.js";
import { logEvent } from "./governance-ledger.js";
import { upsertQaEvidence } from "./qa-evidence.js";

const MAX_TREE_FILES=900;
const MAX_SELECTED_FILES=8;
const MAX_SELECTED_BYTES=240_000;
const MAX_PATCH_FILES=6;
const MAX_PATCH_BYTES=350_000;
const BLOCKED_PATH=/(^|\/)(\.env(?:\.|$)|\.git\/|node_modules\/|dist\/|build\/|\.next\/|coverage\/|.*\.(?:pem|key|p12|pfx|jks)$)/i;
const TEXT_EXT=/\.(?:[cm]?[jt]sx?|html?|css|scss|sass|less|json|md|mdx|yaml|yml|toml|txt|sql|graphql|gql|py|rb|php|java|kt|swift|go|rs|sh|vue|svelte)$/i;

type AgentOperation={path:string;content:string;reason?:string};
type MissionPacketLike={mission?:{brief?:string;phase?:string;lane?:string};route?:Record<string,unknown>;project?:Record<string,unknown>};

function githubToken(){return process.env.GAME_SHOP_GITHUB_TOKEN?.trim()||process.env.GITHUB_TOKEN?.trim()||"";}
function githubWritesAllowed(){return process.env.GAME_SHOP_ALLOW_GITHUB_WRITES==="true";}
function externalAllowed(){return process.env.GAME_SHOP_ALLOW_EXTERNAL_INTEGRATIONS==="true";}
function paidAllowed(){return process.env.GAME_SHOP_ALLOW_PAID_GENERATION==="true";}
function openAiKey(){return process.env.OPENAI_API_KEY?.trim()||"";}
function model(){return process.env.GAME_SHOP_CODE_MODEL?.trim()||"gpt-5.6-terra";}

export function missionCodeAgentStatus(){return{
  available:Boolean(githubToken()&&githubWritesAllowed()&&externalAllowed()&&paidAllowed()&&openAiKey()),
  githubConfigured:Boolean(githubToken()),githubWritesAllowed:githubWritesAllowed(),externalIntegrationsAllowed:externalAllowed(),paidGenerationAllowed:paidAllowed(),openAiConfigured:Boolean(openAiKey()),model:model(),
  branchPolicy:"gameshop/*",maxSelectedFiles:MAX_SELECTED_FILES,maxPatchFiles:MAX_PATCH_FILES,
  note:"The code agent runs only when GitHub, external execution, paid model usage and OpenAI are all explicitly configured. Secrets are never returned.",
};}

function ghHeaders(){const token=githubToken();if(!token)throw new Error("Real execution blocked: GitHub runtime credentials are not configured.");return{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"game-shop-mcp"};}
async function gh(path:string,init:RequestInit={}){const response=await fetch(`https://api.github.com${path}`,{...init,headers:{...ghHeaders(),...(init.headers||{})},signal:AbortSignal.timeout(20_000)});const text=await response.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{}if(!response.ok)throw new Error(`${body?.message||"GitHub request failed"} (${response.status}).`);return body;}
function cleanRoot(root:string){return root==="."?"":root.replace(/^\/+|\/+$/g,"");}
function projectPath(root:string,relative:string){const clean=relative.replace(/^\/+|\/+$/g,"");if(!clean||clean.includes("..")||BLOCKED_PATH.test(clean))throw new Error(`Unsafe code-agent path: ${relative}`);const prefix=cleanRoot(root);return[prefix,clean].filter(Boolean).join("/");}
function relativePath(root:string,full:string){const prefix=cleanRoot(root);if(!prefix)return full;if(full===prefix)return"";return full.startsWith(`${prefix}/`)?full.slice(prefix.length+1):"";}
function packetFrom(execution:StoredExecution){return execution.operationResults.findLast?.(r=>r.kind==="mission.packet")?.packet as MissionPacketLike|undefined||[...execution.operationResults].reverse().find(r=>r.kind==="mission.packet")?.packet as MissionPacketLike|undefined;}
function jsonFromText(text:string){const cleaned=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/```$/," ").trim();const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start<0||end<start)throw new Error("Code agent returned no JSON object.");return JSON.parse(cleaned.slice(start,end+1));}
function responseText(body:any){if(typeof body?.output_text==="string"&&body.output_text.trim())return body.output_text;const parts:string[]=[];for(const item of Array.isArray(body?.output)?body.output:[]){for(const content of Array.isArray(item?.content)?item.content:[]){if(typeof content?.text==="string")parts.push(content.text);}}return parts.join("\n");}
async function ai(prompt:string){if(!externalAllowed())throw new Error("Real execution blocked: GAME_SHOP_ALLOW_EXTERNAL_INTEGRATIONS=true is required.");if(!paidAllowed())throw new Error("Real execution blocked: GAME_SHOP_ALLOW_PAID_GENERATION=true is required for the code model.");const key=openAiKey();if(!key)throw new Error("Real execution blocked: OPENAI_API_KEY is not configured in the Game Shop runtime.");const started=Date.now();const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({model:model(),input:prompt,reasoning:{effort:"medium"}}),signal:AbortSignal.timeout(120_000)});const text=await response.text();let body:any=null;try{body=JSON.parse(text)}catch{}if(!response.ok)throw new Error(`Code model request failed (${response.status}): ${body?.error?.message||text.slice(0,300)}`);const output=responseText(body);if(!output.trim())throw new Error("Code model returned no text output.");return{output,model:model(),latencyMs:Date.now()-started,responseId:body?.id??null,usage:body?.usage??null};}

async function repoTree(repo:string,branch:string,root:string){const tree=await gh(`/repos/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`);const prefix=cleanRoot(root);const files=(Array.isArray(tree?.tree)?tree.tree:[]).filter((x:any)=>x?.type==="blob"&&typeof x.path==="string").map((x:any)=>({path:String(x.path),size:Number(x.size||0),sha:String(x.sha||"")})).filter((x:any)=>{const relative=relativePath(root,x.path);return Boolean(relative)&&(!prefix||x.path.startsWith(`${prefix}/`))&&x.size<=120_000&&!BLOCKED_PATH.test(relative)&&TEXT_EXT.test(relative);}).slice(0,MAX_TREE_FILES);return files;}
async function readFile(repo:string,branch:string,root:string,relative:string){const full=projectPath(root,relative);const row=await gh(`/repos/${repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(branch)}`);if(row?.type!=="file"||typeof row.content!=="string")throw new Error(`Code-agent file is not readable: ${relative}`);const content=Buffer.from(row.content.replace(/\s/g,""),"base64").toString("utf8");return{path:relative,fullPath:full,sha:String(row.sha||""),content};}
async function createBranch(repo:string,base:string,branch:string){if(!githubWritesAllowed())throw new Error("Real execution blocked: GAME_SHOP_ALLOW_GITHUB_WRITES=true is required.");const baseRef=await gh(`/repos/${repo}/git/ref/heads/${encodeURIComponent(base)}`);const sha=String(baseRef?.object?.sha||"");if(!sha)throw new Error("Could not resolve project base branch.");await gh(`/repos/${repo}/git/refs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${branch}`,sha})});return sha;}
async function applyFile(repo:string,branch:string,root:string,operation:AgentOperation,title:string){const full=projectPath(root,operation.path);let sha:string|undefined;try{const current=await gh(`/repos/${repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(branch)}`);if(current?.type==="file"&&typeof current.sha==="string")sha=current.sha;}catch(error){if(!/404/.test(error instanceof Error?error.message:String(error)))throw error;}const payload:any={message:`${title}: ${operation.reason||operation.path}`,content:Buffer.from(operation.content,"utf8").toString("base64"),branch};if(sha)payload.sha=sha;const out=await gh(`/repos/${repo}/contents/${full.split("/").map(encodeURIComponent).join("/")}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});return{path:operation.path,commitSha:out?.commit?.sha??null};}
async function verifyBranch(repo:string,base:string,branch:string,root:string){const compare=await gh(`/repos/${repo}/compare/${encodeURIComponent(base)}...${encodeURIComponent(branch)}`);const changed=(Array.isArray(compare?.files)?compare.files:[]).map((f:any)=>String(f.filename||""));const prefix=cleanRoot(root);const escaped=prefix?changed.filter((f:string)=>f!==prefix&&!f.startsWith(`${prefix}/`)):[];return{status:String(compare?.status||"unknown"),aheadBy:Number(compare?.ahead_by||0),changedFiles:changed,escapedFiles:escaped,scopeSafe:escaped.length===0,passed:changed.length>0&&escaped.length===0&&!['behind','diverged'].includes(String(compare?.status||""))};}
async function openPr(repo:string,base:string,branch:string,title:string,body:string){const row=await gh(`/repos/${repo}/pulls`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,body,head:branch,base})});return{number:row?.number??null,url:row?.html_url??null};}

function selectionPrompt(input:{brief:string;phase:string;lane:string;tree:Array<{path:string;size:number}>;framework?:string;root:string}){return`You are the code-planning stage of Game Shop Mission Control. Select the smallest set of existing text files that must be read before implementing the requested mission.\n\nMISSION: ${input.brief}\nPHASE: ${input.phase}\nPRODUCT LANE: ${input.lane}\nFRAMEWORK: ${input.framework||"unknown"}\nPROJECT ROOT: ${input.root}\n\nRepository files (paths are relative to project root):\n${input.tree.map(x=>`${x.path} (${x.size} bytes)`).join("\n")}\n\nReturn ONLY JSON in this exact shape: {"paths":["path"],"rationale":"short text"}. Choose at most ${MAX_SELECTED_FILES} files. Prefer entrypoints, directly relevant components/styles/config, and avoid lockfiles, generated output, secrets, assets and broad rewrites.`;}
function patchPrompt(input:{brief:string;phase:string;lane:string;framework?:string;route?:Record<string,unknown>;files:Array<{path:string;content:string}>}){return`You are the implementation stage of Game Shop Mission Control. Produce a SMALL, WORKING patch for the mission using only the supplied project files. Return complete replacement contents for every changed or newly created text file. Do not fabricate external credentials, do not add placeholder functionality, do not rewrite the project, and preserve the existing framework and product behavior unless the mission explicitly requires otherwise.\n\nMISSION: ${input.brief}\nPHASE: ${input.phase}\nPRODUCT LANE: ${input.lane}\nFRAMEWORK: ${input.framework||"unknown"}\nROUTED PLAN: ${JSON.stringify(input.route||{})}\n\nFILES:\n${input.files.map(f=>`\n--- ${f.path} ---\n${f.content}`).join("\n")}\n\nReturn ONLY JSON in this exact shape: {"summary":"what changed","operations":[{"path":"relative/path","content":"complete UTF-8 file content","reason":"why"}],"notes":["optional note"]}. Maximum ${MAX_PATCH_FILES} operations. Paths must be relative to the registered project root. If the mission cannot be implemented safely from the supplied files, return an empty operations array and explain what is missing in notes.`;}

export async function runMissionCodeAgent(input:{executionId:string}){
 const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const packet=packetFrom(execution);if(!packet)throw new Error("Execution is not a Mission Control job.");const project=getMissionProject(execution.projectId);if(project.source.kind!=="github")return{status:"client-action-required",executionId:execution.executionId,projectId:project.projectId,target:project.source.kind==="lovable"?"Lovable":"project specialist",reason:"This project is provider-managed; the Vercel code agent currently executes only against GitHub-backed Mission projects."};
 const readiness=missionCodeAgentStatus();if(!readiness.available)return{status:"blocked",executionId:execution.executionId,projectId:project.projectId,readiness};
 const brief=String(packet.mission?.brief||"").trim();if(!brief)throw new Error("Mission brief is missing.");const phase=String(packet.mission?.phase||"upgrade"),lane=String(packet.mission?.lane||project.productKind);await updateExecution(execution.executionId,{mode:"execute",status:"running",operationResults:[...execution.operationResults,{kind:"mission.code-agent.started",at:new Date().toISOString(),model:model()}]});await logEvent({type:"mission.code-agent.started",executionId:execution.executionId,projectId:project.projectId,provider:"openai",data:{model:model(),repo:project.source.repo,phase,lane}}).catch(()=>{});
 try{
  const tree=await repoTree(project.source.repo,project.source.branch,project.source.root);if(!tree.length)throw new Error("No readable source files were found in the registered project root.");
  const selector=await ai(selectionPrompt({brief,phase,lane,tree:tree.map(x=>({path:relativePath(project.source.root,x.path),size:x.size})),framework:project.framework,root:project.source.root}));const selection=jsonFromText(selector.output);const requested=Array.isArray(selection?.paths)?selection.paths.map((x:any)=>String(x)).slice(0,MAX_SELECTED_FILES):[];const allowed=new Set(tree.map(x=>relativePath(project.source.root,x.path)));const paths=requested.filter((p:string)=>allowed.has(p)&&!BLOCKED_PATH.test(p));if(!paths.length)throw new Error("Code agent did not select any valid project files.");
  const files:Array<{path:string;content:string}>=[];let selectedBytes=0;for(const path of paths){const file=await readFile(project.source.repo,project.source.branch,project.source.root,path);selectedBytes+=Buffer.byteLength(file.content,"utf8");if(selectedBytes>MAX_SELECTED_BYTES)break;files.push({path:file.path,content:file.content});}if(!files.length)throw new Error("Selected project files exceeded the safe context limit.");
  const patchCall=await ai(patchPrompt({brief,phase,lane,framework:project.framework,route:packet.route,files}));const patch=jsonFromText(patchCall.output);const rawOps=Array.isArray(patch?.operations)?patch.operations.slice(0,MAX_PATCH_FILES):[];const operations:AgentOperation[]=rawOps.map((op:any)=>({path:String(op?.path||""),content:String(op?.content||""),reason:op?.reason?String(op.reason):undefined})).filter((op:AgentOperation)=>op.path&&op.content&&!BLOCKED_PATH.test(op.path));if(!operations.length)return{status:"input-required",executionId:execution.executionId,projectId:project.projectId,summary:String(patch?.summary||"No safe code changes were produced."),notes:Array.isArray(patch?.notes)?patch.notes:[],selectedFiles:files.map(f=>f.path)};
  let patchBytes=0;for(const op of operations){projectPath(project.source.root,op.path);patchBytes+=Buffer.byteLength(op.content,"utf8");if(Buffer.byteLength(op.content,"utf8")>120_000)throw new Error(`Generated file is too large: ${op.path}`);}if(patchBytes>MAX_PATCH_BYTES)throw new Error("Generated patch exceeds the safe total size limit.");
  const branch=`gameshop/mission-${execution.executionId.replace(/[^a-z0-9-]/gi,"-").slice(-32).toLowerCase()}`;const baseSha=await createBranch(project.source.repo,project.source.branch,branch);const applied=[];for(const operation of operations)applied.push(await applyFile(project.source.repo,branch,project.source.root,operation,"Game Shop mission"));const verification=await verifyBranch(project.source.repo,project.source.branch,branch,project.source.root);if(!verification.passed)throw new Error(`Generated branch failed scope verification: ${verification.escapedFiles.join(", ")||verification.status}`);
  const title=`Game Shop: ${brief.slice(0,72)}`;const pr=await openPr(project.source.repo,project.source.branch,branch,title,`Automated Mission Control implementation.\n\nMission: ${brief}\n\nSummary: ${String(patch?.summary||"Generated project-scoped implementation.")}\n\nVerification: scope-safe ${verification.changedFiles.length}-file change on ${branch}.\n\nThe PR remains subject to independent QA and release approval.`);const evidence=await upsertQaEvidence({projectId:project.projectId,executionId:execution.executionId,provider:"github-scope",commitSha:String(applied.at(-1)?.commitSha||baseSha),status:"passed",evidence:{branch,base:project.source.branch,repo:project.source.repo,changedFiles:verification.changedFiles,scopeSafe:true,prUrl:pr.url,summary:String(patch?.summary||"")}});
  const current=await resolveExecution(execution.executionId)||execution;const result={kind:"mission.code-agent.completed",at:new Date().toISOString(),provider:"openai",model:model(),branch,baseSha,selectedFiles:files.map(f=>f.path),applied,verification,pr,summary:String(patch?.summary||""),notes:Array.isArray(patch?.notes)?patch.notes:[],qaEvidenceId:evidence.evidenceId};await updateExecution(execution.executionId,{mode:"execute",status:"running",completedOperations:Math.min(current.totalOperations,Math.max(current.completedOperations,1)),operationResults:[...current.operationResults,result]});await logEvent({type:"mission.code-agent.completed",executionId:execution.executionId,projectId:project.projectId,provider:"openai",data:{model:model(),branch,prUrl:pr.url,changedFiles:verification.changedFiles,responseIds:[selector.responseId,patchCall.responseId].filter(Boolean)}}).catch(()=>{});return{status:"implemented",executionId:execution.executionId,projectId:project.projectId,branch,pr,verification,summary:result.summary,notes:result.notes,selectedFiles:result.selectedFiles,qaEvidenceId:evidence.evidenceId,nextAction:"Review the generated PR/preview, run automatic QA, then approve or repair before release."};
 }catch(error){const message=error instanceof Error?error.message:String(error);const current=await resolveExecution(execution.executionId)||execution;await updateExecution(execution.executionId,{status:"failed",lastError:message,operationResults:[...current.operationResults,{kind:"mission.code-agent.failed",at:new Date().toISOString(),message}]});await logEvent({type:"mission.code-agent.failed",executionId:execution.executionId,projectId:project.projectId,provider:"openai",data:{message}}).catch(()=>{});throw error;}
}
