import { Buffer } from "node:buffer";
import { getMissionProject, type MissionProject } from "./mission-projects.js";
import { resolveExecution } from "./execution-store.js";
import { executeBrowserQa } from "./browser-adapters.js";
import { upsertQaEvidence, listQaEvidence } from "./qa-evidence.js";
import { orchestrateProviderCapability, type RealOrchestrationCapability } from "./real-orchestration.js";
import { transitionMission, dispatchMissionHandoff } from "./mission-control.js";

export type MissionPatchOperation={path:string;content:string;expectedSha?:string;reason?:string};
type AdapterId="github-inspect"|"github-patch"|"browser-qa"|"provider-capability"|"client-bridge";

function ghToken(){return process.env.GAME_SHOP_GITHUB_TOKEN?.trim()||process.env.GITHUB_TOKEN?.trim()||"";}
function ghHeaders(){const token=ghToken();if(!token)throw new Error("GitHub execution is not configured in Game Shop runtime.");return{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"game-shop-mcp"};}
async function gh(path:string,init:RequestInit={}){const response=await fetch(`https://api.github.com${path}`,{...init,headers:{...ghHeaders(),...(init.headers||{})},signal:AbortSignal.timeout(12000)});const text=await response.text();let body:any=null;try{body=text?JSON.parse(text):null}catch{}if(!response.ok)throw new Error(`${body?.message||"GitHub request failed"} (${response.status}).`);return body;}
function sourcePath(project:MissionProject,relative=""){if(project.source.kind!=="github")throw new Error("Mission project is not GitHub-backed.");const root=project.source.root==="."?"":project.source.root.replace(/^\/+|\/+$/g,"");const clean=relative.replace(/^\/+|\/+$/g,"");if(clean.includes(".."))throw new Error("Path escape is not allowed.");return[root,clean].filter(Boolean).join("/");}
function encodedPath(path:string){return path.split("/").filter(Boolean).map(encodeURIComponent).join("/");}
function writesAllowed(){return process.env.GAME_SHOP_ALLOW_GITHUB_WRITES==="true";}

async function githubInspect(project:MissionProject,ref?:string){if(project.source.kind!=="github")throw new Error("GitHub inspect requires a GitHub-backed Mission project.");const branch=ref||project.source.branch,path=sourcePath(project);const endpoint=path?`/repos/${project.source.repo}/contents/${encodedPath(path)}?ref=${encodeURIComponent(branch)}`:`/repos/${project.source.repo}/contents?ref=${encodeURIComponent(branch)}`;const data=await gh(endpoint);const entries=Array.isArray(data)?data.map((x:any)=>({name:x.name,path:x.path,type:x.type,size:x.size,sha:x.sha})):[];return{projectId:project.projectId,repo:project.source.repo,root:project.source.root,branch,entries};}

async function githubPatch(project:MissionProject,input:{branch:string;baseRef?:string;operations:MissionPatchOperation[];title?:string}){if(project.source.kind!=="github")throw new Error("GitHub patch requires a GitHub-backed Mission project.");if(!writesAllowed())throw new Error("GitHub writes are disabled. Set GAME_SHOP_ALLOW_GITHUB_WRITES=true to opt in.");if(!/^gameshop\/[a-z0-9._/-]+$/i.test(input.branch))throw new Error("Controlled edits require a gameshop/* branch.");if(!input.operations.length||input.operations.length>8)throw new Error("Patch must contain 1–8 replacement files.");let total=0;for(const op of input.operations){if(op.path.startsWith("/")||op.path.includes(".."))throw new Error("Invalid patch path.");total+=Buffer.byteLength(op.content,"utf8");if(Buffer.byteLength(op.content,"utf8")>120000)throw new Error("Patch file exceeds 120 KB.");}if(total>400000)throw new Error("Patch exceeds 400 KB total.");const base=input.baseRef||project.source.branch;const ref=await gh(`/repos/${project.source.repo}/git/ref/heads/${encodeURIComponent(base)}`);const baseSha=String(ref?.object?.sha||"");if(!baseSha)throw new Error("Could not resolve base branch SHA.");try{await gh(`/repos/${project.source.repo}/git/refs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${input.branch}`,sha:baseSha})});}catch(error){if(!/422|already exists|reference already exists/i.test(error instanceof Error?error.message:String(error)))throw error;}
 const applied=[];for(const op of input.operations){const full=sourcePath(project,op.path);let sha:string|undefined;try{const current=await gh(`/repos/${project.source.repo}/contents/${encodedPath(full)}?ref=${encodeURIComponent(input.branch)}`);sha=typeof current?.sha==="string"?current.sha:undefined;if(op.expectedSha&&sha!==op.expectedSha)throw new Error(`Patch precondition failed for ${op.path}.`);}catch(error){if(op.expectedSha)throw error;}const payload:any={message:input.title||`Game Shop repair: ${op.reason||op.path}`,content:Buffer.from(op.content,"utf8").toString("base64"),branch:input.branch};if(sha)payload.sha=sha;const out=await gh(`/repos/${project.source.repo}/contents/${encodedPath(full)}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});applied.push({path:op.path,commitSha:out?.commit?.sha??null});}
 const compare=await gh(`/repos/${project.source.repo}/compare/${encodeURIComponent(base)}...${encodeURIComponent(input.branch)}`);const changed=(Array.isArray(compare?.files)?compare.files:[]).map((f:any)=>String(f.filename||""));const root=project.source.root==="."?"":project.source.root.replace(/^\/+|\/+$/g,"");const escaped=root?changed.filter((f:string)=>f!==root&&!f.startsWith(`${root}/`)):[];if(escaped.length)throw new Error(`Patch escaped the registered project root: ${escaped.join(", ")}`);return{status:"applied",projectId:project.projectId,repo:project.source.repo,branch:input.branch,base,baseSha,applied,changedFiles:changed,scopeSafe:true,totalBytes:total};}

function nestedImage(value:any):string|null{if(!value)return null;if(typeof value==="string"&&/^https?:\/\//.test(value))return value;if(Array.isArray(value)){for(let i=value.length-1;i>=0;i--){const found=nestedImage(value[i]);if(found)return found;}return null;}if(typeof value==="object"){if(typeof value.url==="string"&&/^https?:\/\//.test(value.url))return value.url;if((value.type==="image"||value.mimeType?.startsWith?.("image/"))&&typeof value.data==="string"&&value.data.length<2_000_000)return`data:${value.mimeType||"image/png"};base64,${value.data}`;for(const key of ["content","data","image","screenshot","screenshots","result"]){if(key in value){const found=nestedImage(value[key]);if(found)return found;}}}return null;}
function flattenErrors(rows:any[]|undefined){return(rows||[]).flatMap(row=>{const data=row?.data??row;if(typeof data==="string")return[data];try{return[JSON.stringify(data)]}catch{return[String(data)]}}).slice(0,100);}

export function missionExecutionAdapterCatalog(){return{serverDirect:[{id:"github-inspect",gate:"GAME_SHOP_GITHUB_TOKEN/GITHUB_TOKEN",mutates:false},{id:"github-patch",gate:"GAME_SHOP_ALLOW_GITHUB_WRITES=true",mutates:true,branchPolicy:"gameshop/*"},{id:"browser-qa",gate:"BROWSERBASE_API_KEY or GAME_SHOP_PLAYWRIGHT_MCP_URL",mutates:false},{id:"provider-capability",gate:"GAME_SHOP_ALLOW_EXTERNAL_INTEGRATIONS=true + provider auth + paid-generation policy when applicable",mutates:"provider-dependent"}],clientBridges:["Game Studio","Game Development Studio","Build 3D Game Rooms","Unity","Yoroll","Lovable","Expo / React Native"],policy:"Server-direct adapters execute only when runtime credentials and safety gates are satisfied. Local/plugin/workspace specialists remain client-mediated and must return artifacts/evidence to Game Shop."};}

export async function executeMissionAdapter(input:{executionId:string;adapter:AdapterId;url?:string;provider?:"browserbase"|"playwright-mcp";branch?:string;baseRef?:string;operations?:MissionPatchOperation[];title?:string;capability?:RealOrchestrationCapability;payloads?:Record<string,Record<string,unknown>>;preferredProvider?:"fal"|"replicate"|"elevenlabs"|"scenario"|"cloudinary";target?:string}){const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const project=getMissionProject(execution.projectId);
 if(input.adapter==="github-inspect")return{mode:"executed",adapter:input.adapter,result:await githubInspect(project,input.baseRef)};
 if(input.adapter==="github-patch")return{mode:"executed",adapter:input.adapter,result:await githubPatch(project,{branch:input.branch||`gameshop/mission-${input.executionId.slice(-10)}`,baseRef:input.baseRef,operations:input.operations||[],title:input.title})};
 if(input.adapter==="browser-qa")return captureMissionQa({executionId:input.executionId,url:input.url,provider:input.provider});
 if(input.adapter==="provider-capability"){if(!input.capability)throw new Error("Provider capability is required.");return orchestrateProviderCapability({capability:input.capability,preferredProvider:input.preferredProvider,payloads:(input.payloads||{}) as any,execute:true,executionId:execution.executionId,projectId:execution.projectId,purpose:project.productKind==="media"?"media-project":project.productKind==="app"?"web-app":project.productKind});}
 if(input.target)return{mode:"client-bridge",adapter:input.adapter,target:input.target,projectId:project.projectId,executionId:execution.executionId,returnContract:{required:["status","artifacts","evidence","errors"],rule:"Do not mark the handoff executed until evidence is returned to Game Shop."}};
 return dispatchMissionHandoff({executionId:input.executionId,note:"Client/local bridge requested through Mission execution adapter."});}

export async function captureMissionQa(input:{executionId:string;url?:string;provider?:"browserbase"|"playwright-mcp"}){const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const project=getMissionProject(execution.projectId);await transitionMission({executionId:execution.executionId,action:"qa",message:"Automatic Mission QA capture"});
 let structural:any={status:"blocked",reason:"Source inspection unavailable."};if(project.source.kind==="github"){try{structural={status:"passed",inspection:await githubInspect(project)};}catch(error){structural={status:"blocked",error:error instanceof Error?error.message:String(error)};}}else structural={status:"passed",source:"provider-managed",note:"Structural source inspection is delegated to the provider/client bridge."};await upsertQaEvidence({projectId:project.projectId,executionId:execution.executionId,provider:"structural",status:structural.status==="passed"?"passed":"blocked",evidence:structural});
 const url=input.url||project.deployment?.url||(project.source.kind==="lovable"?(project.source.previewUrl||project.source.publishedUrl):undefined);if(!url){await upsertQaEvidence({projectId:project.projectId,executionId:execution.executionId,provider:"visual-console",runId:`auto-${crypto.randomUUID()}`,status:"blocked",evidence:{reason:"No browser target URL is available."}});return{status:"blocked",projectId:project.projectId,executionId:execution.executionId,structural,url:null};}
 let browser:any=null,status:"passed"|"failed"|"blocked"="blocked";try{browser=await executeBrowserQa({url,provider:input.provider});status=browser.errors.length?"failed":"passed";}catch(error){browser={errors:[error instanceof Error?error.message:String(error)],console:[],network:[],screenshots:[]};status="blocked";}
 const history=await listQaEvidence({executionId:execution.executionId,provider:"visual-console",limit:20});const previous=history.find(row=>typeof row.evidence?.afterUrl==="string");const afterUrl=nestedImage(browser?.screenshots);const beforeUrl=typeof previous?.evidence?.afterUrl==="string"?String(previous.evidence.afterUrl):null;const evidence={source:"automatic-browser-capture",beforeUrl,afterUrl,findings:browser?.errors||[],consoleErrors:flattenErrors(browser?.console),networkErrors:flattenErrors(browser?.network),browser,comparison:{hasBefore:Boolean(beforeUrl),hasAfter:Boolean(afterUrl),mode:beforeUrl&&afterUrl?"true-before-after":"single-capture"}};await upsertQaEvidence({projectId:project.projectId,executionId:execution.executionId,provider:"visual-console",runId:`auto-${crypto.randomUUID()}`,previewUrl:url,status,evidence});return{status,projectId:project.projectId,executionId:execution.executionId,url,structural,browser,evidence};}

export async function repairAndRerunMissionQa(input:{executionId:string;url?:string;provider?:"browserbase"|"playwright-mcp";branch?:string;operations?:MissionPatchOperation[];title?:string;assumeRepairApplied?:boolean}){const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const project=getMissionProject(execution.projectId);await transitionMission({executionId:execution.executionId,action:"repair",message:"Repair + rerun QA requested"});let repair:any=null;if(input.operations?.length){if(project.source.kind!=="github")return{status:"client-action-required",projectId:project.projectId,reason:"Provider-managed/local project repair cannot be executed by the Vercel runtime.",bridge:await executeMissionAdapter({executionId:execution.executionId,adapter:"client-bridge",target:project.source.kind==="lovable"?"Lovable":"project specialist"})};repair=await githubPatch(project,{branch:input.branch||`gameshop/repair-${execution.executionId.slice(-10)}`,operations:input.operations,title:input.title});}else if(!input.assumeRepairApplied){return{status:"repair-input-required",projectId:project.projectId,executionId:execution.executionId,source:project.source.kind,nextAction:project.source.kind==="github"?"Provide approved replacement-file patch operations, or set assumeRepairApplied=true after an external repair is completed.":"Run the client/local repair bridge, then call again with assumeRepairApplied=true.",bridge:project.source.kind==="github"?null:await executeMissionAdapter({executionId:execution.executionId,adapter:"client-bridge",target:project.source.kind==="lovable"?"Lovable":"project specialist"})};}
 await transitionMission({executionId:execution.executionId,action:"qa",message:"Repair complete; rerunning automatic QA"});const qa=await captureMissionQa({executionId:execution.executionId,url:input.url,provider:input.provider});return{status:qa.status==="passed"?"rerun-passed":"rerun-needs-review",repair,qa};}
