import { createHash } from "node:crypto";
import { routeGameWorkflow } from "./game-workflow-router.js";
import { routeWebsiteWorkflow } from "./website-workflow-router.js";
import { routeAppWorkflow } from "./app-workflow-router.js";
import { routeMediaWorkflow } from "./media-workflow-router.js";
import { getMissionProject, listMissionProjects, missionProjectSourceSnapshot, missionProjectRegistryInfo } from "./mission-projects.js";
import { cancelExecutionDurable, resolveExecution, resolveExecutions, saveExecution, updateExecution, type StoredExecution } from "./execution-store.js";
import { budgetStatus, listEvents, listPreviews, logEvent, setExecutionBudget } from "./governance-ledger.js";
import { listQaEvidence, upsertQaEvidence, type QaEvidenceStatus } from "./qa-evidence.js";
import { listQaRecipes } from "./qa-memory.js";
import { evaluateRelease } from "./release-governor.js";

export type MissionStage="planned"|"running"|"qa"|"repair"|"ready"|"released"|"failed"|"cancelled";
export type MissionPhase="create"|"upgrade"|"fix"|"audit"|"release";
export type MissionPermission={read:boolean;plan:boolean;qa:boolean;execute:boolean;write:boolean;deploy:boolean};
export type SpecialistHandoff={handoffId:string;order:number;target:string;transport:string;instruction:string;gate?:string;requiredScope:string;clientMediated:boolean;status:"queued"|"dispatched"|"completed"};
export type MissionPacket={version:1;executionId:string;projectId:string;createdAt:string;mission:{brief:string;phase:MissionPhase;lane:"game"|"website"|"app"|"media"};project:Awaited<ReturnType<typeof missionProjectSourceSnapshot>>;route:Record<string,unknown>;permissions:MissionPermission;expectedArtifacts:string[];requiredEvidence:string[];rollback:Record<string,unknown>;handoffs:SpecialistHandoff[]};

type StoredResult=Record<string,unknown>;
function now(){return new Date().toISOString();}
function id(){return`exec_mission_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;}
function digest(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0,24);}
function asObject(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function routeFor(kind:string,input:{brief:string;phase:MissionPhase;preference?:any}){
 if(kind==="game")return routeGameWorkflow({brief:input.brief,phase:input.phase,runtime:"auto",preference:input.preference??"balanced",existingProject:true} as any) as unknown as Record<string,unknown>;
 if(kind==="website")return routeWebsiteWorkflow({brief:input.brief,phase:input.phase,kind:"auto",framework:"any",preference:input.preference??"balanced",existingProject:true} as any) as unknown as Record<string,unknown>;
 if(kind==="media")return routeMediaWorkflow({brief:input.brief,phase:input.phase,kind:"auto",preference:input.preference??"balanced",existingProject:true} as any) as unknown as Record<string,unknown>;
 return routeAppWorkflow({brief:input.brief,phase:input.phase,kind:"auto",framework:"auto",preference:input.preference??"balanced",existingProject:true} as any) as unknown as Record<string,unknown>;
}
function transportFor(target:string){const t=target.toLowerCase();if(t.includes("game studio")||t.includes("build 3d"))return"client-plugin";if(t.includes("game development studio"))return"local-cli";if(t.includes("unity"))return"local-mcp/workspace";if(t.includes("yoroll"))return"remote-mcp/client-plugin";if(t.includes("lovable"))return"client-connector";if(t.includes("expo"))return"codex-skill/local-workspace";if(t.includes("github"))return"gameshop-github-api";if(t.includes("playwright")||t.includes("qa"))return"gameshop-qa-lane";if(t.includes("game shop"))return"gameshop-internal";return"integration-or-client";}
function scopeFor(target:string,gate?:string,lane?:string,phase?:string){const text=`${target} ${gate??""}`.toLowerCase();if(lane==="release"||/release|deploy|store/.test(text))return"gameshop.deploy";if(lane==="source"&&phase==="audit"&&target.toLowerCase()==="github")return"gameshop.read";if(lane==="qa"||/qa|playwright|test|diagnostic/.test(text))return"gameshop.qa";if(/github|source|write|patch/.test(text))return"gameshop.write";if(/provider|generate|unity|yoroll|lovable|expo|studio|external/.test(text))return"gameshop.execute";return"gameshop.plan";}
function makeHandoffs(route:Record<string,unknown>):SpecialistHandoff[]{const stages=Array.isArray(route.stages)?route.stages as Array<Record<string,unknown>>:[];return stages.map((stage,index)=>{const target=String(stage.owner??stage.lane??`Stage ${index+1}`),gate=stage.gate?String(stage.gate):undefined,transport=String(stage.transport??transportFor(target));return{handoffId:`handoff_${index+1}`,order:index+1,target,transport,instruction:String(stage.purpose??"Execute routed stage."),...(gate?{gate}:{}),requiredScope:scopeFor(target,gate,String(stage.lane??""),String(route.phase??"")),clientMediated:/client|local|workspace/.test(transport),status:"queued" as const};});}
function serverExecutable(h:SpecialistHandoff){return !h.clientMediated&&/^(gameshop-|integration-or-client)/.test(h.transport);}
function expectedArtifacts(kind:string,phase:MissionPhase){const out=["mission packet","execution evidence","QA evidence"];if(phase!=="audit")out.push(kind==="media"?"versioned media outputs":"source changes");if(phase!=="audit")out.push("preview or runtime proof");if(phase==="release")out.push("release decision");return out;}
function requiredEvidence(kind:string){const base=["structural verification","before/after or runtime visual evidence","console/network findings","deterministic QA result"];if(kind==="game")base.push("playability regression");if(kind==="app")base.push("auth/data flow verification when applicable");if(kind==="media")base.push("artifact integrity/playback verification");return base;}
function rollbackFor(source:Awaited<ReturnType<typeof missionProjectSourceSnapshot>>["project"]["source"]){if(source.kind==="github")return{strategy:"isolated branch + revert",source:source.repo,branch:source.branch,rule:"Never overwrite the verified source branch before QA/release gates."};return{strategy:"provider revision / project history",provider:"lovable",projectId:source.projectId,rule:"Preserve the prior working provider revision before accepting generated edits."};}
function packetFrom(execution:StoredExecution){const row=[...execution.operationResults].reverse().find(v=>v.kind==="mission.packet");return row?.packet as MissionPacket|undefined;}
function explicitStage(execution:StoredExecution){const row=[...execution.operationResults].reverse().find(v=>v.kind==="mission.stage");return row?.stage as MissionStage|undefined;}
export function missionStage(execution:StoredExecution):MissionStage{const explicit=explicitStage(execution);if(explicit)return explicit;if(execution.status==="planned")return"planned";if(execution.status==="failed")return"failed";if(execution.status==="cancelled")return"cancelled";if(execution.status==="completed")return"ready";return"running";}
function storedStatus(stage:MissionStage):StoredExecution["status"]{if(stage==="planned")return"planned";if(stage==="failed")return"failed";if(stage==="cancelled")return"cancelled";if(stage==="ready"||stage==="released")return"completed";return"running";}
function stageEntry(stage:MissionStage,data:Record<string,unknown>={}):StoredResult{return{kind:"mission.stage",stage,at:now(),...data};}
function latestPerProvider<T extends {provider:string}>(rows:T[]){const seen=new Set<string>();return rows.filter(row=>!seen.has(row.provider)&&seen.add(row.provider));}

export async function missionControlContext(projectId:string){
 const project=await missionProjectSourceSnapshot(projectId);const [executions,evidence,recipes,previews,events]=await Promise.all([resolveExecutions(),listQaEvidence({projectId,limit:50}),listQaRecipes({projectId}),listPreviews({projectId,limit:30}),listEvents({projectId,limit:50})]);
 const jobs=executions.filter(e=>e.projectId===projectId&&packetFrom(e));const recentEvidence=latestPerProvider(evidence);const issues:Array<Record<string,unknown>>=[];
 for(const execution of jobs.filter(e=>e.lastError))issues.push({kind:"execution",executionId:execution.executionId,message:execution.lastError,at:execution.updatedAt});
 for(const qa of recentEvidence.filter(e=>e.status==="failed"||e.status==="blocked"))issues.push({kind:"qa",provider:qa.provider,evidenceId:qa.evidenceId,status:qa.status,message:qa.evidence.summary??qa.evidence.message??qa.evidence.errors??"QA evidence failed or blocked.",at:qa.updatedAt});
 for(const event of events.filter(e=>/failed|error|blocked|repair/i.test(String(e.type??""))).slice(0,10))issues.push({kind:"event",type:event.type,data:event.data,at:event.created_at});
 const revision=asObject(project.source).latestCommit?asObject(asObject(project.source).latestCommit).sha??null:null;const relevantFiles=project.project.source.kind==="github"?["AGENTS.md","package.json",project.project.source.root].filter(Boolean):[];const nextActions=issues.length?["Resolve the highest-priority known issue, then rerun bound QA."]:jobs.length?["Resume the most recent incomplete durable job or create a narrowly scoped mission."]:["Create a narrowly scoped mission from this project brief."];return{brief:{projectId,sourceRevision:revision,stack:{framework:project.project.framework??null,runtime:project.project.runtime??null},relevantFiles,deployment:{declared:project.project.deployment??null,latestPreview:previews[0]??null},constraints:{source:project.project.source,permissions:project.enrichment?.permissionProfile??null,qaPolicy:project.enrichment?.qaPolicy??null},nextActions,freshness:project.freshness},registry:missionProjectRegistryInfo(),project,deployment:{declared:project.project.deployment??null,previews},recentQa:recentEvidence.slice(0,20),qaRecipes:recipes.slice(0,20),knownIssues:issues.slice(0,25),recentJobs:await Promise.all(jobs.slice(0,12).map(missionJobSummary)),recentEvents:events.slice(0,25)};
}

export async function prepareMission(input:{projectId:string;brief:string;phase?:MissionPhase;preference?:string;budgetUsd?:number;providerBudgets?:Record<string,number>;permissions?:Partial<MissionPermission>}){
 const project=getMissionProject(input.projectId);const executionId=id();const phase=input.phase??"upgrade";const sourceSnapshot=await missionProjectSourceSnapshot(project.projectId);const route=routeFor(project.productKind,{brief:input.brief,phase,preference:input.preference});
 const permissions:MissionPermission={read:true,plan:true,qa:true,execute:false,write:false,deploy:false,...(input.permissions??{})};
 const packet:MissionPacket={version:1,executionId,projectId:project.projectId,createdAt:now(),mission:{brief:input.brief.trim(),phase,lane:project.productKind},project:sourceSnapshot,route,permissions,expectedArtifacts:expectedArtifacts(project.productKind,phase),requiredEvidence:requiredEvidence(project.productKind),rollback:rollbackFor(sourceSnapshot.project.source),handoffs:makeHandoffs(route)};
 const created:StoredExecution={executionId,planDigest:digest(packet),projectId:project.projectId,mode:"dry-run",status:"planned",createdAt:packet.createdAt,updatedAt:packet.createdAt,completedOperations:0,totalOperations:packet.handoffs.length,operationResults:[{kind:"mission.packet",packet},stageEntry("planned")]};
 await saveExecution(created);if(input.budgetUsd!==undefined)await setExecutionBudget({executionId,budgetUsd:input.budgetUsd,providerBudgets:input.providerBudgets});await logEvent({type:"mission.planned",executionId,projectId:project.projectId,data:{phase,lane:project.productKind,planDigest:created.planDigest}}).catch(()=>{});return{execution:created,packet,budget:await budgetStatus(executionId)};
}

export async function dispatchMissionHandoff(input:{executionId:string;handoffId?:string;note?:string}){
 const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const packet=packetFrom(execution);if(!packet)throw new Error("Execution is not a Mission Control job.");const dispatched=new Set(execution.operationResults.filter(r=>r.kind==="mission.handoff").map(r=>String(r.handoffId)));
 const handoff=packet.handoffs.find(h=>h.handoffId===input.handoffId)||(packet.handoffs.find(h=>!dispatched.has(h.handoffId)));if(!handoff)throw new Error("No queued handoff remains.");
 const record={kind:"mission.handoff",handoffId:handoff.handoffId,target:handoff.target,transport:handoff.transport,requiredScope:handoff.requiredScope,clientMediated:handoff.clientMediated,instruction:handoff.instruction,gate:handoff.gate??null,note:input.note??null,status:"dispatched",dispatchedAt:now()};
 const nextResults=[...execution.operationResults,record,stageEntry("running",{handoffId:handoff.handoffId})];await updateExecution(execution.executionId,{mode:"execute",status:"running",operationResults:nextResults,completedOperations:Math.min(execution.completedOperations,execution.totalOperations)});await logEvent({type:"mission.handoff.dispatched",executionId:execution.executionId,projectId:execution.projectId,data:record}).catch(()=>{});
 const canExecute=serverExecutable(handoff)&&Boolean(packet.permissions.execute||handoff.requiredScope==="gameshop.plan"||handoff.requiredScope==="gameshop.qa"||handoff.requiredScope==="gameshop.read");
 return{executionId:execution.executionId,handoff:record,executionMode:canExecute?"server-capable":"client-mediated",packet:{projectId:packet.projectId,mission:packet.mission,permissions:packet.permissions,expectedArtifacts:packet.expectedArtifacts,requiredEvidence:packet.requiredEvidence,rollback:packet.rollback},nextAction:canExecute?"Game Shop server/runtime should execute this handoff and persist artifacts/evidence; the browser is a control surface, not the worker.":"The connected client must execute this specialist handoff because its transport requires a client/local workspace, then return artifacts/evidence to Game Shop."};
}

export async function recordMissionVisualQa(input:{projectId:string;executionId?:string;commitSha?:string;previewUrl?:string;status:QaEvidenceStatus;beforeUrl?:string;afterUrl?:string;findings?:string[];consoleErrors?:string[];networkErrors?:string[];playwright?:Record<string,unknown>;notes?:string}){
 const value=await upsertQaEvidence({executionId:input.executionId,projectId:input.projectId,provider:"visual-console",commitSha:input.commitSha,previewUrl:input.previewUrl,status:input.status,evidence:{beforeUrl:input.beforeUrl??null,afterUrl:input.afterUrl??null,findings:input.findings??[],consoleErrors:input.consoleErrors??[],networkErrors:input.networkErrors??[],playwright:input.playwright??null,notes:input.notes??null}});
 if(input.executionId){const execution=await resolveExecution(input.executionId);if(execution)await updateExecution(input.executionId,{operationResults:[...execution.operationResults,{kind:"mission.visual-qa",evidenceId:value.evidenceId,status:value.status,at:now()}]});}
 await logEvent({type:`mission.qa.${input.status}`,executionId:input.executionId,projectId:input.projectId,data:{evidenceId:value.evidenceId,previewUrl:input.previewUrl??null}}).catch(()=>{});return value;
}

async function applyStage(execution:StoredExecution,stage:MissionStage,data:Record<string,unknown>={}){const results=[...execution.operationResults,stageEntry(stage,data)];const completed=stage==="ready"||stage==="released"?execution.totalOperations:execution.completedOperations;const updated=await updateExecution(execution.executionId,{status:storedStatus(stage),completedOperations:completed,operationResults:results,lastError:stage==="failed"?String(data.message??execution.lastError??"Mission failed."):execution.lastError});await logEvent({type:`mission.stage.${stage}`,executionId:execution.executionId,projectId:execution.projectId,data}).catch(()=>{});return updated;}
export async function transitionMission(input:{executionId:string;action:"start"|"qa"|"repair"|"approve"|"release"|"fail"|"cancel";message?:string}){
 const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Mission execution not found.");const packet=packetFrom(execution);if(!packet)throw new Error("Execution is not a Mission Control job.");
 if(input.action==="cancel")return cancelExecutionDurable(execution.executionId);
 if(input.action==="start")return applyStage(execution,"running",{message:input.message??null});
 if(input.action==="qa")return applyStage(execution,"qa",{message:input.message??null});
 if(input.action==="repair")return applyStage(execution,"repair",{message:input.message??null});
 if(input.action==="fail")return applyStage(execution,"failed",{message:input.message??"Mission failed."});
 const evidence=latestPerProvider(await listQaEvidence({projectId:execution.projectId,executionId:execution.executionId,limit:100}));
 if(input.action==="approve"){
   if(!evidence.length)throw new Error("Cannot approve without persisted QA evidence for this execution.");const bad=evidence.filter(e=>e.status==="failed"||e.status==="blocked");const pending=evidence.filter(e=>e.status==="queued"||e.status==="running");if(bad.length)throw new Error("Cannot approve while QA evidence is failed or blocked.");if(pending.length)throw new Error("Cannot approve while QA evidence is still pending.");return applyStage(execution,"ready",{evidenceIds:evidence.map(e=>e.evidenceId)});
 }
 const previews=await listPreviews({projectId:execution.projectId,limit:20});const preview=previews.find(p=>String(p.status)==="tested")??previews[0];const source=packet.project.source as Record<string,unknown>;const latestCommit=asObject(source.latestCommit);const release=await evaluateRelease({projectId:execution.projectId,url:preview?.preview_url?String(preview.preview_url):packet.project.project.deployment?.url,commitSha:latestCommit.sha?String(latestCommit.sha):undefined,runRegressions:true,queuePlaywrightCi:true});if(!release.releaseAllowed)throw new Error(`Release blocked: ${release.reasons.join(" ")}`);return applyStage(execution,"released",{releaseDecision:release.decision,reasons:release.reasons});
}

export async function missionJobSummary(execution:StoredExecution){const packet=packetFrom(execution);if(!packet)return null;const [budget,evidence,previews]=await Promise.all([budgetStatus(execution.executionId),listQaEvidence({projectId:execution.projectId,executionId:execution.executionId,limit:50}),listPreviews({projectId:execution.projectId,limit:10})]);const handoffs=execution.operationResults.filter(r=>r.kind==="mission.handoff");const visual=evidence.find(e=>e.provider==="visual-console")??null;return{executionId:execution.executionId,projectId:execution.projectId,projectName:packet.project.project.name,lane:packet.mission.lane,brief:packet.mission.brief,phase:packet.mission.phase,stage:missionStage(execution),createdAt:execution.createdAt,updatedAt:execution.updatedAt,completedOperations:execution.completedOperations,totalOperations:execution.totalOperations,lastError:execution.lastError??null,budget,provider:handoffs.at(-1)?.target??null,handoffs,artifacts:execution.operationResults.filter(r=>/artifact/i.test(String(r.kind??""))),qa:{evidence,visual,passed:evidence.filter(e=>e.status==="passed").length,failed:evidence.filter(e=>e.status==="failed"||e.status==="blocked").length},previews,rollback:packet.rollback};}
export async function listMissionJobs(input:{projectId?:string;limit?:number}={}){const rows=(await resolveExecutions()).filter(e=>packetFrom(e)&&(!input.projectId||e.projectId===input.projectId)).slice(0,Math.min(100,input.limit??50));return Promise.all(rows.map(missionJobSummary));}
export async function missionJob(executionId:string){const execution=await resolveExecution(executionId);if(!execution)return null;return missionJobSummary(execution);}
export function missionControlInfo(){return{version:1,flow:["select-project","load-context","plan","handoff","running","qa","repair","ready","released"],registry:missionProjectRegistryInfo(),durableState:"existing execution store + governance/QA ledgers",release:"strict release governor; Release never bypasses persisted evidence gates",handoff:"structured packet with transport, required scope, artifacts, QA and rollback; client-mediated specialists are explicitly labelled rather than falsely claimed as server-executed"};}
export function missionProjects(){return listMissionProjects();}
