import { resolveExecution } from "./execution-store.js";
import { listArtifacts } from "./artifacts.js";
import { listQaEvidence } from "./qa-evidence.js";
import { listEvents, logEvent } from "./governance-ledger.js";
export type AiClient="grok"|"chatgpt"|"codex"|"claude"|"cursor"|"other";
const sessions=new Map<string,Record<string,unknown>>();
function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
async function store(path:string,init:RequestInit={}){const c=config();if(!c)return null;const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init.headers||{})},signal:AbortSignal.timeout(10000)});const text=await r.text();if(!r.ok)throw new Error(`Continuity store failed (${r.status}).`);return text?JSON.parse(text):null;}
export function multiAiContinuityInfo(){return{mode:"shared-authoritative-game-shop-state",clients:["grok","chatgpt","codex","claude","cursor","other"],truth:["execution","artifact-graph","qa-evidence","event-ledger"],durableHandoffs:Boolean(config()),rule:"Clients may propose work, but Game Shop execution/artifact/evidence state is authoritative."};}
export async function handoffExecution(input:{executionId:string;from:AiClient;to:AiClient;note?:string}){const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Execution not found.");const artifacts=await listArtifacts({executionId:input.executionId});const evidence=await listQaEvidence({executionId:input.executionId,limit:50});const event=await logEvent({type:"ai.handoff",executionId:input.executionId,clientId:input.from,data:{from:input.from,to:input.to,note:input.note??null,artifactCount:artifacts.length,evidenceCount:evidence.length}});const token=`handoff_${crypto.randomUUID()}`;const createdAt=new Date().toISOString();const artifactIds=artifacts.map(a=>a.artifactId);const evidenceIds=evidence.map((e:any)=>String(e.evidence_id??e.evidenceId??""));const snapshot={token,executionId:input.executionId,from:input.from,to:input.to,execution,artifactIds,evidenceIds,eventId:(event as any).event_id,createdAt};sessions.set(token,snapshot);await store("game_shop_ai_handoffs",{method:"POST",body:JSON.stringify({handoff_id:token,execution_id:input.executionId,from_client:input.from,to_client:input.to,note:input.note??null,artifact_ids:artifactIds,evidence_ids:evidenceIds,created_at:createdAt})});return snapshot;}
export async function listHandoffs(input:{executionId?:string;limit?:number}={}){const params=new URLSearchParams({order:"created_at.desc",limit:String(Math.min(100,input.limit??30))});if(input.executionId)params.set("execution_id",`eq.${input.executionId}`);const data=await store(`game_shop_ai_handoffs?${params}`);if(Array.isArray(data))return data;return[...sessions.values()].filter((r:any)=>!input.executionId||r.executionId===input.executionId).slice(0,input.limit??30);}
export async function continuitySnapshot(executionId:string){const [execution,artifacts,evidence,events,handoffs]=await Promise.all([resolveExecution(executionId),listArtifacts({executionId}),listQaEvidence({executionId,limit:100}),listEvents({executionId,limit:100}),listHandoffs({executionId,limit:100})]);return{executionId,execution,artifacts,evidence,events,handoffs,policy:multiAiContinuityInfo()};}
export async function verifyContinuity(input:{executionId:string;expectedArtifactIds?:string[];expectedEvidenceIds?:string[]}){const snap=await continuitySnapshot(input.executionId);const artifacts=new Set(snap.artifacts.map(a=>a.artifactId));const evidence=new Set(snap.evidence.map((e:any)=>String(e.evidence_id??e.evidenceId??"")));const missingArtifacts=(input.expectedArtifactIds??[]).filter(id=>!artifacts.has(id));const missingEvidence=(input.expectedEvidenceIds??[]).filter(id=>!evidence.has(id));return{ok:!missingArtifacts.length&&!missingEvidence.length,missingArtifacts,missingEvidence,snapshot:snap};}
