import { resolveExecution } from "./execution-store.js";
import { listArtifacts } from "./artifacts.js";
import { listQaEvidence } from "./qa-evidence.js";
import { listEvents, logEvent } from "./governance-ledger.js";
export type AiClient="grok"|"chatgpt"|"codex"|"claude"|"cursor"|"other";
const sessions=new Map<string,Record<string,unknown>>();
export function multiAiContinuityInfo(){return{mode:"shared-authoritative-game-shop-state",clients:["grok","chatgpt","codex","claude","cursor","other"],truth:["execution","artifact-graph","qa-evidence","event-ledger"],rule:"Clients may propose work, but Game Shop execution/artifact/evidence state is authoritative."};}
export async function handoffExecution(input:{executionId:string;from:AiClient;to:AiClient;note?:string}){const execution=await resolveExecution(input.executionId);if(!execution)throw new Error("Execution not found.");const artifacts=await listArtifacts({executionId:input.executionId});const evidence=await listQaEvidence({executionId:input.executionId,limit:50});const event=await logEvent({type:"ai.handoff",executionId:input.executionId,clientId:input.from,data:{from:input.from,to:input.to,note:input.note??null,artifactCount:artifacts.length,evidenceCount:evidence.length}});const token=`handoff_${crypto.randomUUID()}`;const snapshot={token,executionId:input.executionId,from:input.from,to:input.to,execution,artifactIds:artifacts.map(a=>a.artifactId),evidenceIds:evidence.map((e:any)=>e.evidence_id??e.evidenceId),eventId:(event as any).event_id,createdAt:new Date().toISOString()};sessions.set(token,snapshot);return snapshot;}
export async function continuitySnapshot(executionId:string){const [execution,artifacts,evidence,events]=await Promise.all([resolveExecution(executionId),listArtifacts({executionId}),listQaEvidence({executionId,limit:100}),listEvents({executionId,limit:100})]);return{executionId,execution,artifacts,evidence,events,policy:multiAiContinuityInfo()};}
export async function verifyContinuity(input:{executionId:string;expectedArtifactIds?:string[];expectedEvidenceIds?:string[]}){const snap=await continuitySnapshot(input.executionId);const artifacts=new Set(snap.artifacts.map(a=>a.artifactId));const evidence=new Set(snap.evidence.map((e:any)=>String(e.evidence_id??e.evidenceId??"")));const missingArtifacts=(input.expectedArtifactIds??[]).filter(id=>!artifacts.has(id));const missingEvidence=(input.expectedEvidenceIds??[]).filter(id=>!evidence.has(id));return{ok:!missingArtifacts.length&&!missingEvidence.length,missingArtifacts,missingEvidence,snapshot:snap};}
