export type NextGenIntegration={id:string;name:string;kind:Array<"mcp"|"api"|"cli"|"registry">;state:"ready"|"needs-auth"|"installable";endpoint?:string;install?:string;env?:string[];capabilities:string[];notes:string};
const items:NextGenIntegration[]=[
 {id:"browserbase-mcp",name:"Browserbase MCP",kind:["mcp","api","cli"],state:"needs-auth",endpoint:"https://mcp.browserbase.com/mcp",install:"npx @browserbasehq/mcp",env:["BROWSERBASE_API_KEY"],capabilities:["cloud-browser","navigate","act","observe","extract","sessions","stagehand","qa"],notes:"Hosted Streamable HTTP MCP is wired directly by Game Shop's browser adapter."},
 {id:"playwright-mcp",name:"Playwright MCP",kind:["mcp","cli"],state:"installable",install:"npx @playwright/mcp@latest --headless --caps=network,testing,devtools --port 8931",env:["GAME_SHOP_PLAYWRIGHT_MCP_URL"],capabilities:["browser-automation","accessibility-snapshot","screenshots","console","network","testing","devtools","cross-browser","self-healing-qa"],notes:"Official Microsoft Playwright MCP. Game Shop can use a remote HTTP instance or its deterministic GitHub Actions lane."},
 {id:"playwright-cli",name:"Playwright CLI + Skills",kind:["cli"],state:"installable",install:"npm install -g @playwright/cli@latest && playwright-cli install --skills",capabilities:["token-efficient-browser-automation","screenshots","snapshots","network","console","tracing","video","recording","sessions","coding-agent-skills"],notes:"Official Microsoft CLI/Skills path. Prefer for high-throughput coding-agent repair loops; MCP remains preferred for persistent exploratory sessions."},
 {id:"chrome-devtools-mcp",name:"Chrome DevTools MCP",kind:["mcp","cli"],state:"installable",install:"npx -y chrome-devtools-mcp@latest --headless --no-usage-statistics",capabilities:["chrome-debugging","performance-traces","performance-insights","console","network","screenshots","puppeteer-automation","source-mapped-errors"],notes:"Official ChromeDevTools MCP/CLI. Strong third QA lane for deep Chrome performance and runtime debugging; CI disables usage statistics."},
 {id:"vercel-preview-api",name:"Vercel Preview API",kind:["api"],state:"needs-auth",endpoint:"https://api.vercel.com",env:["VERCEL_TOKEN","GAME_SHOP_VERCEL_PROJECTS_JSON"],capabilities:["preview-deployments","deployment-discovery","git-source","deploy-hooks","status"],notes:"Game Shop only creates/discovers Preview deployments through this adapter; production is intentionally excluded."},
 {id:"official-mcp-registry",name:"Official MCP Registry",kind:["registry","api"],state:"ready",endpoint:"https://registry.modelcontextprotocol.io/v0.1/servers",capabilities:["server-discovery","remote-metadata","package-metadata","capability-expansion"],notes:"Feeds the trust pipeline; discovered servers are never auto-promoted without sandbox and approval."}
];
export function nextGenIntegrations(){return items;}
