import { routeMultiDomain, type Domain, type Preference } from "./multidomain-router.js";

export type ProductKind = "website" | "web-app" | "browser-game" | "mobile-app" | "interactive-experience" | "digital-product";
export type BuildGoal = "premium" | "cinematic" | "playful" | "minimal" | "immersive" | "conversion" | "performance";
export type BuildPlanRequest = { brief:string; product:ProductKind; goals?:BuildGoal[]; framework?:"react"|"vanilla"|"vue"|"phaser"|"three"|"any"; preference?:Preference; includeDomains?:Domain[] };
type PlanStep={id:string;phase:"foundation"|"visual-system"|"interaction"|"scene"|"media";domain:Domain;capability:string;engine:string|null;install?:string;connect?:string;action:string;dependsOn:string[]};
const capabilities:Record<Domain,string[]>={ui:["component","layout"],motion:["timeline","micro-interaction","smooth-scroll"],"3d":["scene","interactive-3d"],shader:["shader","webgl-effect"],video:["motion-design","video"],"design-reference":["visual-reference","design-guidance"],"agent-platform":["build-workflow","agent-ui"]};
function defaultDomains(product:ProductKind,goals:BuildGoal[]):Domain[]{const d:Domain[]=["ui","motion","design-reference"];if(product==="browser-game"||product==="interactive-experience"||goals.includes("immersive")||goals.includes("cinematic"))d.push("3d","shader");if(goals.includes("cinematic")||goals.includes("conversion"))d.push("video");return [...new Set(d)];}
function phaseFor(d:Domain):PlanStep["phase"]{if(d==="design-reference"||d==="agent-platform")return"foundation";if(d==="ui")return"visual-system";if(d==="motion")return"interaction";if(d==="3d"||d==="shader")return"scene";return"media";}
export function createBuildPlan(request:BuildPlanRequest){const goals=request.goals?.length?request.goals:["premium"];const domains=request.includeDomains?.length?request.includeDomains:defaultDomains(request.product,goals);const preference=request.preference??(goals.includes("performance")?"bundle":goals.includes("premium")||goals.includes("cinematic")?"quality":"balanced");const framework=request.framework??"any";const steps:PlanStep[]=[];for(const domain of domains){for(const capability of capabilities[domain]){const routed=routeMultiDomain({domain,capability,preference,framework});const s=routed.selected;const phase=phaseFor(domain);const id=`${domain}-${capability}`;steps.push({id,phase,domain,capability,engine:s?.id??null,install:s?.install,connect:s?.connect,action:s?`Use ${s.id} for ${capability}. ${s.notes}`:`No verified route for ${capability}; keep manual until integration is verified.`,dependsOn:phase==="foundation"?[]:steps.filter(x=>x.phase==="foundation"||x.phase==="visual-system").map(x=>x.id).slice(0,4)});}}const installs=[...new Set(steps.map(s=>s.install).filter((x):x is string=>Boolean(x)))];const connections=[...new Set(steps.map(s=>s.connect).filter((x):x is string=>Boolean(x)))];return{version:"1.0",brief:request.brief,product:request.product,goals,framework,preference,domains,installs,connections,steps,executionPolicy:{paidGeneration:"Respect GAME_SHOP_ALLOW_PAID_GENERATION; a plan never grants billing permission.",externalServices:"Use only authorized services and verified integration contracts.",libraries:"Install libraries in the target project, not the gateway unless the gateway imports them.",registries:"Use official registries and preserve license restrictions."}};}
