import { upsertQaEvidence } from "./qa-evidence.js";
const REPO="thegreishow/game-shop-mcp";
const WORKFLOW="playwright-qa.yml";
function token(){const value=process.env.GAME_SHOP_GITHUB_TOKEN?.trim()||process.env.GITHUB_TOKEN?.trim();if(!value)throw new Error("GAME_SHOP_GITHUB_TOKEN or GITHUB_TOKEN is not configured for Playwright CI dispatch.");return value;}
function headers(){return{Authorization:`Bearer ${token()}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","content-type":"application/json","User-Agent":"game-shop-mcp"};}
function safeUrl(value:string){const url=new URL(value);if(url.protocol!=="https:")throw new Error("QA target must use HTTPS.");const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".local")||/^127\./.test(host)||/^10\./.test(host)||/^192\.168\./.test(host)||/^169\.254\./.test(host)||/^172\.(1[6-9]|2\d|3[01])\./.test(host))throw new Error("Private QA targets are not allowed.");return url.toString();}
async function github(path:string,init:RequestInit={}){const response=await fetch(`https://api.github.com/repos/${REPO}${path}`,{...init,headers:{...headers(),...(init.headers||{})},signal:AbortSignal.timeout(15000)});const text=await response.text();if(!response.ok)throw new Error(`Playwright CI GitHub request failed (${response.status}).`);return text?JSON.parse(text):null;}
export function playwrightCiInfo(){const configured=Boolean(process.env.GAME_SHOP_GITHUB_TOKEN||process.env.GITHUB_TOKEN);return{repo:REPO,workflow:WORKFLOW,configured,credential:configured?(process.env.GAME_SHOP_GITHUB_TOKEN?"GAME_SHOP_GITHUB_TOKEN":"GITHUB_TOKEN"):null,mode:"github-actions-playwright-mcp",browser:"chromium",caps:["network","testing","devtools"],artifacts:["gameshop-playwright-qa","playwright-mcp-log"],evidenceCallback:"/qa/evidence",policy:{targetHttpsOnly:true,privateNetworkBlocked:true,productionMutation:false}};}
export async function dispatchPlaywrightCi(input:{url:string;projectId?:string;executionId?:string;interactions?:string[];ref?:string;commitSha?:string}){const url=safeUrl(input.url);const interactions=(input.interactions??[]).filter(Boolean).slice(0,8);await github(`/actions/workflows/${WORKFLOW}/dispatches`,{method:"POST",body:JSON.stringify({ref:input.ref||"main",inputs:{target_url:url,project_id:input.projectId||"",execution_id:input.executionId||"",commit_sha:input.commitSha||"",interactions_json:JSON.stringify(interactions)}})});if(input.projectId)await upsertQaEvidence({projectId:input.projectId,executionId:input.executionId,provider:"playwright-ci",commitSha:input.commitSha,previewUrl:url,status:"queued",evidence:{workflow:WORKFLOW,ref:input.ref||"main"}});return{status:"queued",url,repo:REPO,workflow:WORKFLOW,ref:input.ref||"main",commitSha:input.commitSha??null,correlation:{projectId:input.projectId??null,executionId:input.executionId??null},runsUrl:`https://github.com/${REPO}/actions/workflows/${WORKFLOW}`};}
export async function listPlaywrightCiRuns(input:{limit?:number}={}){const data=await github(`/actions/workflows/${WORKFLOW}/runs?event=workflow_dispatch&per_page=${Math.min(20,input.limit??10)}`) as Record<string,unknown>;const runs=Array.isArray(data?.workflow_runs)?data.workflow_runs as Array<Record<string,unknown>>:[];return{runs:runs.map(run=>({id:run.id,status:run.status,conclusion:run.conclusion,url:run.html_url,createdAt:run.created_at,updatedAt:run.updated_at,headSha:run.head_sha,headBranch:run.head_branch})),info:playwrightCiInfo()};}
