import { getProjectOverlay, listProjectOverlays } from "./project-overlay.js";
import { resolveArcadeAlias } from "./arcade-registry.js";
export type GameProjectContext = {id:string;name?:string;repo:string;defaultBranch:string;framework?:string;projectPath?:string;gamePath?:string;productKind?:string;artStyle?:string;notes?:string;verifyPaths?:string[]};
export type ProjectContext = GameProjectContext;
// Compatibility fallback only. The live arcade registry is authoritative and overlays these records at tool invocation time.
const LEGACY_FALLBACK_PROJECTS: ProjectContext[] = [
{id:"dubai-legends",name:"Dubai Legends",repo:"thegreishow/thegreishow.com",defaultBranch:"main",framework:"browser-game",productKind:"browser-game",projectPath:"arcade/games/dubai-legends",gamePath:"arcade/games/dubai-legends",artStyle:"cinematic arcade cricket",notes:"Compatibility fallback; refresh arcade/games/games.json for authoritative metadata.",verifyPaths:["arcade/games/dubai-legends"]},
{id:"dreamweaver-oracle",name:"Dreamweaver Oracle",repo:"thegreishow/thegreishow.com",defaultBranch:"main",framework:"browser-game",productKind:"browser-game",projectPath:"arcade/games/dreamweaver-oracle",gamePath:"arcade/games/dreamweaver-oracle",artStyle:"psychedelic cosmic arcade",notes:"Compatibility fallback; refresh arcade/games/games.json for authoritative metadata.",verifyPaths:["arcade/games/dreamweaver-oracle"]},
{id:"rodeo-are-you-ready",name:"Rodeo: Are You Ready",repo:"thegreishow/thegreishow.com",defaultBranch:"main",framework:"browser-game",productKind:"browser-game",projectPath:"arcade/games/rodeo-are-you-ready",gamePath:"arcade/games/rodeo-are-you-ready",artStyle:"cinematic western music arcade",notes:"Compatibility fallback; refresh arcade/games/games.json for authoritative metadata.",verifyPaths:["arcade/games/rodeo-are-you-ready"]},
];
function normalizeProject(value:ProjectContext):ProjectContext{const projectPath=value.projectPath||value.gamePath;return{...value,projectPath,gamePath:value.gamePath||projectPath,productKind:value.productKind||value.framework||"other"};}
function configuredProjects():ProjectContext[]{let base=LEGACY_FALLBACK_PROJECTS.map(normalizeProject);const raw=process.env.GAME_SHOP_PROJECTS_JSON;if(raw){try{const parsed=JSON.parse(raw);if(Array.isArray(parsed)){const extra=parsed.filter((v:any)=>v&&typeof v.id==="string"&&typeof v.repo==="string"&&typeof v.defaultBranch==="string").map(normalizeProject);const merged=new Map(base.map(p=>[p.id,p]));for(const p of extra)merged.set(p.id,p);base=[...merged.values()];}}catch{}}
 const merged=new Map(base.map(p=>[p.id,p]));for(const project of listProjectOverlays())merged.set(project.id,normalizeProject(project));return[...merged.values()];}
export function listProjects(){return configuredProjects();}
export function getProject(id:string){const canonical=resolveArcadeAlias(id);const overlay=getProjectOverlay(canonical);if(overlay)return normalizeProject(overlay);const project=configuredProjects().find(c=>c.id===canonical);if(!project)throw new Error("Project is not configured in the Game Shop allowlist.");return project;}
export function projectContext(id:string){const project=getProject(id);const githubReadToken=process.env.GAME_SHOP_GITHUB_TOKEN||process.env.GITHUB_TOKEN;return{...project,execution:{githubReadConfigured:Boolean(githubReadToken),githubCredential:githubReadToken?(process.env.GAME_SHOP_GITHUB_TOKEN?"GAME_SHOP_GITHUB_TOKEN":"GITHUB_TOKEN"):null,githubWritesAllowed:process.env.GAME_SHOP_ALLOW_GITHUB_WRITES==="true",externalIntegrationsAllowed:process.env.GAME_SHOP_ALLOW_EXTERNAL_INTEGRATIONS==="true",paidGenerationAllowed:process.env.GAME_SHOP_ALLOW_PAID_GENERATION==="true",destructiveExternalAllowed:process.env.GAME_SHOP_ALLOW_DESTRUCTIVE_EXTERNAL_ACTIONS==="true",deployAllowed:process.env.GAME_SHOP_ALLOW_DEPLOY==="true"}};}
