import { listArtifacts } from "./artifacts.js";
import { elevenSpeechJob, falJob, ludoJob, meshyTask, replicatePrediction } from "./external-engines.js";
import { scenarioJobV2 } from "./scenario-v2.js";
import { logEvent } from "./governance-ledger.js";
export type ReconcileResult={artifactId:string;provider?:string;jobId?:string;status:string;result?:unknown;error?:string};
export function providerReconcilerInfo(){return{mode:"idempotent-provider-reconciliation",providers:["meshy","fal","replicate","ludo","elevenlabs","scenario"],strategy:["webhook-when-supported","scheduled-reconciliation","bounded-backoff","terminal-finalization","orchestration-continuation"],exactlyOnce:"artifact terminal state is the idempotency boundary",scheduledWorker:"provider-reconcile.yml"};}
function metadata(a:any){return(a.metadata??{}) as Record<string,unknown>;}
export async function reconcileArtifact(artifactId:string):Promise<ReconcileResult>{const artifact=(await listArtifacts()).find(a=>a.artifactId===artifactId);if(!artifact)throw new Error("Artifact not found.");if(["ready","failed","archived"].includes(artifact.status))return{artifactId,provider:artifact.provider,jobId:artifact.providerJobId,status:artifact.status};if(!artifact.provider||!artifact.providerJobId)return{artifactId,provider:artifact.provider,jobId:artifact.providerJobId,status:"blocked",error:"Provider/job id missing."};try{let result:unknown;switch(artifact.provider){case"meshy":result=await meshyTask(artifact.providerJobId);break;case"replicate":result=await replicatePrediction(artifact.providerJobId);break;case"ludo":result=await ludoJob({id:artifact.providerJobId,wait:0});break;case"elevenlabs":result=await elevenSpeechJob(artifact.providerJobId);break;case"scenario":result=await scenarioJobV2(artifact.providerJobId);break;case"fal":{const m=metadata(artifact);const response=m.providerResponse as Record<string,unknown>|undefined;const statusUrl=String(m.statusUrl??response?.status_url??response?.statusUrl??"");const responseUrl=String(m.responseUrl??response?.response_url??response?.responseUrl??"");if(!statusUrl)throw new Error("fal artifact is missing status URL.");result=await falJob({jobId:artifact.providerJobId,statusUrl,responseUrl:responseUrl||undefined});break;}default:return{artifactId,provider:artifact.provider,jobId:artifact.providerJobId,status:"unsupported"};}await logEvent({type:"provider.reconciled",executionId:artifact.executionId,projectId:artifact.projectId,provider:artifact.provider,data:{artifactId,jobId:artifact.providerJobId}});return{artifactId,provider:artifact.provider,jobId:artifact.providerJobId,status:"reconciled",result};}catch(e){const error=e instanceof Error?e.message:String(e);await logEvent({type:"provider.reconcile_failed",executionId:artifact.executionId,projectId:artifact.projectId,provider:artifact.provider,data:{artifactId,error}});return{artifactId,provider:artifact.provider,jobId:artifact.providerJobId,status:"error",error};}}
export async function reconcilePendingProviders(input:{executionId?:string;projectId?:string;limit?:number}={}){const artifacts=(await listArtifacts({executionId:input.executionId,projectId:input.projectId})).filter(a=>a.status==="pending"&&a.providerJobId).slice(0,input.limit??20);const results:ReconcileResult[]=[];for(const artifact of artifacts)results.push(await reconcileArtifact(artifact.artifactId));return{checked:results.length,results,info:providerReconcilerInfo()};}
