export type QaEvidenceStatus="queued"|"running"|"passed"|"failed"|"blocked";
export type QaEvidence={evidenceId:string;executionId?:string;projectId:string;provider:string;runId?:string;commitSha?:string;previewUrl?:string;status:QaEvidenceStatus;evidence:Record<string,unknown>;createdAt:string;updatedAt:string};
const memory=new Map<string,QaEvidence>();

function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY?.trim();return url&&key?{url,key}:null;}
function row(v:QaEvidence){return{evidence_id:v.evidenceId,execution_id:v.executionId??null,project_id:v.projectId,provider:v.provider,run_id:v.runId??null,commit_sha:v.commitSha??null,preview_url:v.previewUrl??null,status:v.status,evidence:v.evidence,created_at:v.createdAt,updated_at:v.updatedAt};}
function evidence(r:Record<string,unknown>):QaEvidence{return{evidenceId:String(r.evidence_id),executionId:r.execution_id?String(r.execution_id):undefined,projectId:String(r.project_id),provider:String(r.provider),runId:r.run_id?String(r.run_id):undefined,commitSha:r.commit_sha?String(r.commit_sha):undefined,previewUrl:r.preview_url?String(r.preview_url):undefined,status:String(r.status) as QaEvidenceStatus,evidence:(r.evidence??{}) as Record<string,unknown>,createdAt:String(r.created_at),updatedAt:String(r.updated_at)};}
async function request(path:string,init:RequestInit={}){const c=config();if(!c)return null;const response=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init.headers||{})},signal:AbortSignal.timeout(12000)});const text=await response.text();if(!response.ok)throw new Error(`QA evidence store failed (${response.status}).`);return text?JSON.parse(text):null;}
export function qaEvidenceInfo(){return{backend:config()?"supabase-postgres":"process-memory-fallback",durableAcrossColdStarts:Boolean(config()),table:"game_shop_qa_evidence",providers:["browserbase","playwright-mcp","playwright-ci","chrome-devtools-mcp","structural"],policy:{terminalStatuses:["passed","failed","blocked"],releaseUsesTerminalEvidence:true}};}
export async function upsertQaEvidence(input:{evidenceId?:string;executionId?:string;projectId:string;provider:string;runId?:string;commitSha?:string;previewUrl?:string;status:QaEvidenceStatus;evidence?:Record<string,unknown>}){const now=new Date().toISOString();const id=input.evidenceId??(input.runId?`qae_${input.provider}_${input.runId}`:`qae_${crypto.randomUUID()}`);const current=memory.get(id);const value:QaEvidence={evidenceId:id,executionId:input.executionId??current?.executionId,projectId:input.projectId,provider:input.provider,runId:input.runId??current?.runId,commitSha:input.commitSha??current?.commitSha,previewUrl:input.previewUrl??current?.previewUrl,status:input.status,evidence:{...(current?.evidence??{}),...(input.evidence??{})},createdAt:current?.createdAt??now,updatedAt:now};memory.set(id,value);const data=await request("game_shop_qa_evidence?on_conflict=evidence_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row(value))});return Array.isArray(data)&&data[0]?evidence(data[0]):value;}
export async function listQaEvidence(input:{projectId?:string;executionId?:string;provider?:string;limit?:number}={}){const params=new URLSearchParams({order:"updated_at.desc",limit:String(Math.min(200,input.limit??100))});if(input.projectId)params.set("project_id",`eq.${input.projectId}`);if(input.executionId)params.set("execution_id",`eq.${input.executionId}`);if(input.provider)params.set("provider",`eq.${input.provider}`);const data=await request(`game_shop_qa_evidence?${params}`);const rows=Array.isArray(data)?data.map(evidence):[...memory.values()];return rows.filter(v=>(!input.projectId||v.projectId===input.projectId)&&(!input.executionId||v.executionId===input.executionId)&&(!input.provider||v.provider===input.provider)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,input.limit??100);}
export async function latestTerminalEvidence(projectId:string,provider:string,commitSha?:string){const rows=await listQaEvidence({projectId,provider,limit:50});return rows.find(v=>(!commitSha||v.commitSha===commitSha)&&["passed","failed","blocked"].includes(v.status))??null;}
