import type { VerificationCheck } from "./verification.js";

export type QaRecipe={recipeId:string;projectId:string;name:string;description?:string;checks:VerificationCheck[];interactions:string[];createdFromExecutionId?:string;approved:boolean;passCount:number;failCount:number;lastStatus?:"passed"|"failed";lastRunAt?:string;createdAt:string;updatedAt:string};
const memory=new Map<string,QaRecipe>();
function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
function id(){return `qar_${Date.now().toString(36)}_${crypto.randomUUID().slice(0,8)}`;}
async function request(path:string,init:RequestInit={}){const c=config();if(!c)return null;const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init.headers||{})},signal:AbortSignal.timeout(12000)});const text=await r.text();if(!r.ok)throw new Error(`QA memory request failed (${r.status}).`);return text?JSON.parse(text):null;}
function row(r:QaRecipe){return{recipe_id:r.recipeId,project_id:r.projectId,name:r.name,description:r.description??null,checks:r.checks,interactions:r.interactions,created_from_execution_id:r.createdFromExecutionId??null,approved:r.approved,pass_count:r.passCount,fail_count:r.failCount,last_status:r.lastStatus??null,last_run_at:r.lastRunAt??null,created_at:r.createdAt,updated_at:r.updatedAt};}
function recipe(v:Record<string,unknown>):QaRecipe{return{recipeId:String(v.recipe_id),projectId:String(v.project_id),name:String(v.name),description:v.description?String(v.description):undefined,checks:Array.isArray(v.checks)?v.checks as VerificationCheck[]:[],interactions:Array.isArray(v.interactions)?v.interactions.map(String):[],createdFromExecutionId:v.created_from_execution_id?String(v.created_from_execution_id):undefined,approved:Boolean(v.approved),passCount:Number(v.pass_count??0),failCount:Number(v.fail_count??0),lastStatus:v.last_status?String(v.last_status) as QaRecipe["lastStatus"]:undefined,lastRunAt:v.last_run_at?String(v.last_run_at):undefined,createdAt:String(v.created_at),updatedAt:String(v.updated_at)};}
export function qaMemoryInfo(){return{backend:config()?"supabase-postgres":"process-memory-fallback",durableAcrossColdStarts:Boolean(config()),table:"game_shop_qa_recipes",policy:{approvalRequiredBeforeReplay:true,maxInteractions:8,maxChecks:25},purpose:"Turns successful exploratory QA and repaired failures into reusable regression memory."};}
export async function createQaRecipe(input:{projectId:string;name:string;description?:string;checks?:VerificationCheck[];interactions?:string[];createdFromExecutionId?:string;approved?:boolean}){const now=new Date().toISOString();const r:QaRecipe={recipeId:id(),projectId:input.projectId,name:input.name,description:input.description,checks:(input.checks??[]).slice(0,25),interactions:(input.interactions??[]).slice(0,8),createdFromExecutionId:input.createdFromExecutionId,approved:Boolean(input.approved),passCount:0,failCount:0,createdAt:now,updatedAt:now};memory.set(r.recipeId,r);const data=await request("game_shop_qa_recipes",{method:"POST",body:JSON.stringify(row(r))});return Array.isArray(data)&&data[0]?recipe(data[0]):r;}
export async function listQaRecipes(input:{projectId?:string;approvedOnly?:boolean}={}){const params=new URLSearchParams({order:"updated_at.desc",limit:"100"});if(input.projectId)params.set("project_id",`eq.${input.projectId}`);if(input.approvedOnly)params.set("approved","eq.true");const data=await request(`game_shop_qa_recipes?${params}`);const rows=Array.isArray(data)?data.map(recipe):[...memory.values()];return rows.filter(r=>(!input.projectId||r.projectId===input.projectId)&&(!input.approvedOnly||r.approved));}
export async function getQaRecipe(recipeId:string){if(memory.has(recipeId))return memory.get(recipeId)!;const data=await request(`game_shop_qa_recipes?recipe_id=eq.${encodeURIComponent(recipeId)}&limit=1`);return Array.isArray(data)&&data[0]?recipe(data[0]):null;}
export async function approveQaRecipe(recipeId:string,approved:boolean){const current=await getQaRecipe(recipeId);if(!current)throw new Error("QA recipe not found.");const next={...current,approved,updatedAt:new Date().toISOString()};memory.set(recipeId,next);const data=await request(`game_shop_qa_recipes?recipe_id=eq.${encodeURIComponent(recipeId)}`,{method:"PATCH",body:JSON.stringify(row(next))});return Array.isArray(data)&&data[0]?recipe(data[0]):next;}
export async function recordQaRecipeResult(recipeId:string,status:"passed"|"failed"){const current=await getQaRecipe(recipeId);if(!current)throw new Error("QA recipe not found.");const next:QaRecipe={...current,passCount:current.passCount+(status==="passed"?1:0),failCount:current.failCount+(status==="failed"?1:0),lastStatus:status,lastRunAt:new Date().toISOString(),updatedAt:new Date().toISOString()};memory.set(recipeId,next);const data=await request(`game_shop_qa_recipes?recipe_id=eq.${encodeURIComponent(recipeId)}`,{method:"PATCH",body:JSON.stringify(row(next))});return Array.isArray(data)&&data[0]?recipe(data[0]):next;}
export const QA_MEMORY_SQL=`create table if not exists public.game_shop_qa_recipes (recipe_id text primary key,project_id text not null,name text not null,description text,checks jsonb not null default '[]'::jsonb,interactions jsonb not null default '[]'::jsonb,created_from_execution_id text,approved boolean not null default false,pass_count integer not null default 0,fail_count integer not null default 0,last_status text,last_run_at timestamptz,created_at timestamptz not null,updated_at timestamptz not null); create index if not exists game_shop_qa_recipes_project_idx on public.game_shop_qa_recipes(project_id);`;
