import { runQa } from "./qa-worker.js";
import { executeBrowserQa } from "./browser-adapters.js";
import { dispatchPlaywrightCi,playwrightCiInfo } from "./playwright-ci.js";
import { chromeDiagnosticsInfo,dispatchChromeDiagnostics } from "./chrome-diagnostics.js";
import { upsertQaEvidence } from "./qa-evidence.js";
import type { VerificationCheck } from "./verification.js";

export type QaGate="green"|"provisional"|"blocked"|"red";
function countErrors(value:unknown){const row=value as Record<string,unknown>|null;const findings=Array.isArray(row?.findings)?row!.findings as Array<Record<string,unknown>>:[];return findings.filter(f=>f.severity==="error").length;}
function githubConfigured(){return Boolean(process.env.GAME_SHOP_GITHUB_TOKEN||process.env.GITHUB_TOKEN);}
export function qaSwarmInfo(){return{mode:"multi-lane-evidence-fusion",lanes:{structural:"github-source",browserbase:"hosted-stagehand-mcp",playwrightRemote:"streamable-http-mcp",playwrightCi:playwrightCiInfo(),chromeDevtools:chromeDiagnosticsInfo()},gate:{green:"all required terminal evidence passed",provisional:"live QA passed but deterministic/deep evidence is queued",red:"one or more error findings",blocked:"required evidence or browser target is missing"}};}
export async function runQaSwarm(input:{projectId:string;ref?:string;url?:string;checks?:VerificationCheck[];interactions?:string[];autoPreview?:boolean;queuePlaywrightCi?:boolean;queueChromeDiagnostics?:boolean;executionId?:string;commitSha?:string}){
 const requireCi=input.queuePlaywrightCi??true;
 const primaryProvider=process.env.BROWSERBASE_API_KEY?"browserbase":"playwright-mcp";
 const primary=await runQa({projectId:input.projectId,ref:input.ref,url:input.url,provider:primaryProvider,checks:input.checks,interactions:input.interactions,autoPreview:input.autoPreview??true,executionId:input.executionId,commitSha:input.commitSha});
 const target=primary.url?String(primary.url):null;const lanes:Record<string,unknown>={primary};let errorCount=countErrors(primary);let deterministicCovered=false;let chromeQueued=false;
 if(target&&process.env.GAME_SHOP_PLAYWRIGHT_MCP_URL&&primaryProvider!=="playwright-mcp"){try{const remotePlaywright=await executeBrowserQa({url:target,provider:"playwright-mcp",interactions:input.interactions});lanes.playwrightRemote=remotePlaywright;const errors=remotePlaywright.errors.length;errorCount+=errors;deterministicCovered=errors===0;await upsertQaEvidence({projectId:input.projectId,executionId:input.executionId,provider:"playwright-mcp",commitSha:input.commitSha,previewUrl:target,status:errors?"failed":"passed",evidence:{browser:remotePlaywright}});}catch(error){errorCount++;lanes.playwrightRemote={status:"failed",error:error instanceof Error?error.message:String(error)};await upsertQaEvidence({projectId:input.projectId,executionId:input.executionId,provider:"playwright-mcp",commitSha:input.commitSha,previewUrl:target,status:"failed",evidence:{error:error instanceof Error?error.message:String(error)}});}}
 if(target&&requireCi){if(githubConfigured()){try{lanes.playwrightCi=await dispatchPlaywrightCi({url:target,projectId:input.projectId,executionId:input.executionId,interactions:input.interactions,commitSha:input.commitSha});}catch(error){lanes.playwrightCi={status:"unavailable",error:error instanceof Error?error.message:String(error)};}}else lanes.playwrightCi={status:"not-configured",reason:"GAME_SHOP_GITHUB_TOKEN or GITHUB_TOKEN is required for workflow dispatch."};}
 const deepRequested=input.queueChromeDiagnostics??errorCount>0;
 if(target&&deepRequested){if(githubConfigured()){try{lanes.chromeDevtools=await dispatchChromeDiagnostics({url:target,projectId:input.projectId,executionId:input.executionId,ref:"main",commitSha:input.commitSha});chromeQueued=true;}catch(error){lanes.chromeDevtools={status:"unavailable",error:error instanceof Error?error.message:String(error)};}}else lanes.chromeDevtools={status:"not-configured",reason:"GitHub workflow dispatch credential is required."};}
 let gate:QaGate;if(!target)gate="blocked";else if(errorCount>0||primary.status==="failed")gate="red";else if(requireCi&&!deterministicCovered)gate="provisional";else if(chromeQueued)gate="provisional";else gate="green";
 const confidence=gate==="green"?1:gate==="provisional"?.8:gate==="blocked"?.25:0;
 return{schemaVersion:"1.3",projectId:input.projectId,executionId:input.executionId??null,commitSha:input.commitSha??null,ref:primary.ref,url:target,gate,confidence,errorCount,lanes,release:{allowed:gate==="green",reason:gate==="green"?"QA release gate is green.":gate==="provisional"?"Live QA passed; deterministic/deep evidence remains pending or unavailable.":gate==="blocked"?"No preview/browser target is available.":"QA evidence contains errors; Chrome deep diagnostics is queued when available."},info:qaSwarmInfo()};
}
