import { getProject } from "./projects.js";
import { verifyProject, createRepairPlan, type VerificationCheck } from "./verification.js";
import { browserAdapterInfo, executeBrowserQa, type BrowserQaProvider } from "./browser-adapters.js";
import { createPreviewDeployment, previewDeploymentInfo } from "./preview-deployment.js";
export type { BrowserQaProvider } from "./browser-adapters.js";
export type QaFinding={kind:"console"|"network"|"visual"|"interaction"|"performance"|"structural"|"deployment";severity:"info"|"warning"|"error";message:string;evidence?:Record<string,unknown>};
export function qaWorkerInfo(){return{mode:"evidence-first-live",providers:browserAdapterInfo(),preview:previewDeploymentInfo(),policy:{repairsRequireApproval:true,writeGate:"GAME_SHOP_ALLOW_GITHUB_WRITES",maxRepairCycles:3},evidence:["structural","console","network","screenshots","interaction","performance","deployment"]};}
export async function runQa(input:{projectId:string;ref?:string;url?:string;provider?:BrowserQaProvider;checks?:VerificationCheck[];interactions?:string[];autoPreview?:boolean}){const project=getProject(input.projectId);const ref=input.ref??project.defaultBranch;const structural=await verifyProject({projectId:input.projectId,ref,checks:input.checks});const findings:QaFinding[]=[];if(structural.status!=="passed")for(const check of structural.checks.filter(c=>c.ok!==true))findings.push({kind:"structural",severity:"error",message:`Structural verification failed: ${String(check.path)}`,evidence:check});
 let url=input.url;let deployment:unknown=null;if(!url&&input.autoPreview&&ref.startsWith("gameshop/")){try{deployment=await createPreviewDeployment({projectId:input.projectId,branch:ref,waitMs:60000});const d=deployment as Record<string,unknown>;if(d.previewUrl)url=String(d.previewUrl);if(d.status==="failed")findings.push({kind:"deployment",severity:"error",message:"Preview deployment failed.",evidence:d});else if(!url)findings.push({kind:"deployment",severity:"warning",message:"Preview deployment is still pending.",evidence:d});}catch(error){findings.push({kind:"deployment",severity:"warning",message:`Preview discovery failed: ${error instanceof Error?error.message:String(error)}`});}}
 let browser:Awaited<ReturnType<typeof executeBrowserQa>>|null=null;if(url){try{browser=await executeBrowserQa({url,provider:input.provider,interactions:input.interactions});for(const error of browser.errors)findings.push({kind:"interaction",severity:"error",message:error});if(browser.console.length)findings.push({kind:"console",severity:"warning",message:"Browser console evidence was captured; inspect returned data for runtime errors.",evidence:{count:browser.console.length}});if(browser.network.length)findings.push({kind:"network",severity:"info",message:"Network evidence captured.",evidence:{count:browser.network.length}});if(browser.screenshots.length)findings.push({kind:"visual",severity:"info",message:"Screenshot evidence captured.",evidence:{count:browser.screenshots.length}});if(browser.performance)findings.push({kind:"performance",severity:"info",message:"Basic navigation/performance evidence captured."});}catch(error){findings.push({kind:"interaction",severity:"error",message:`Browser QA adapter failed: ${error instanceof Error?error.message:String(error)}`});}}else findings.push({kind:"interaction",severity:"warning",message:"No preview URL is available yet; browser execution is blocked."});
 const failed=findings.some(f=>f.severity==="error");const repair=failed?createRepairPlan({projectId:input.projectId,verification:structural}):undefined;return{projectId:input.projectId,ref,url:url??null,provider:input.provider??(process.env.BROWSERBASE_API_KEY?"browserbase":"playwright-mcp"),status:failed?"failed":url?"passed":"blocked",findings,structural,deployment,browser,repair,requiresApproval:failed};}
export function repairWorkerContract(input:{projectId:string;qa:Record<string,unknown>;approved:boolean}){if(!input.approved)return{status:"blocked",reason:"repair-approval-required"};return{status:"approved",projectId:input.projectId,maxCycles:3,strategy:"smallest-safe-patch",loop:["inspect-evidence","propose-explicit-file-replacements","approval","patch-gameshop-branch","preview-deploy","structural-qa","browser-qa","repeat-until-green"],writeGate:"GAME_SHOP_ALLOW_GITHUB_WRITES",qa:input.qa};}
