import { getProject } from "./projects.js";
import { verifyProject, createRepairPlan, type VerificationCheck } from "./verification.js";
import { browserAdapterInfo, executeBrowserQa, type BrowserAssertion, type BrowserQaProvider } from "./browser-adapters.js";
import { createPreviewDeployment, previewDeploymentInfo } from "./preview-deployment.js";
import { upsertQaEvidence } from "./qa-evidence.js";
export type { BrowserAssertion, BrowserQaProvider } from "./browser-adapters.js";
export type QaFinding={kind:"console"|"network"|"visual"|"interaction"|"performance"|"structural"|"deployment";severity:"info"|"warning"|"error";message:string;evidence?:Record<string,unknown>};
function errorKind(message:string):QaFinding["kind"]{const text=message.toLowerCase();if(/console|runtime|exception|uncaught/.test(text))return"console";if(/network|requestfailed|http|fetch|net::err|404|500|502|503/.test(text))return"network";if(/selector|canvas|visible|layout|element count/.test(text))return"visual";if(/deploy|preview/.test(text))return"deployment";return"interaction";}
export function qaWorkerInfo(){return{mode:"playwright-authoritative-evidence-first",providers:browserAdapterInfo(),preview:previewDeploymentInfo(),policy:{browserAuthority:"playwright-mcp",repairsRequireApproval:true,writeGate:"GAME_SHOP_ALLOW_GITHUB_WRITES",maxRepairCycles:3},evidence:["structural","console","network","screenshots","interaction","assertions","performance","deployment"]};}
export async function runQa(input:{projectId:string;ref?:string;url?:string;provider?:BrowserQaProvider;checks?:VerificationCheck[];interactions?:string[];assertions?:BrowserAssertion[];autoPreview?:boolean;executionId?:string;commitSha?:string}){
 const project=getProject(input.projectId);const ref=input.ref??project.defaultBranch;const structural=await verifyProject({projectId:input.projectId,ref,checks:input.checks});const findings:QaFinding[]=[];if(structural.status!=="passed")for(const check of structural.checks.filter(c=>c.ok!==true))findings.push({kind:"structural",severity:"error",message:`Structural verification failed: ${String(check.path)}`,evidence:check});
 await upsertQaEvidence({projectId:input.projectId,executionId:input.executionId,provider:"structural",commitSha:input.commitSha,status:structural.status==="passed"?"passed":"failed",evidence:{ref,checks:structural.checks}});
 let url=input.url;let deployment:unknown=null;if(!url&&input.autoPreview&&ref.startsWith("gameshop/")){try{deployment=await createPreviewDeployment({projectId:input.projectId,branch:ref,commitSha:input.commitSha,waitMs:60000});const d=deployment as Record<string,unknown>;if(d.previewUrl)url=String(d.previewUrl);if(d.status==="failed")findings.push({kind:"deployment",severity:"error",message:"Preview deployment failed.",evidence:d});else if(!url)findings.push({kind:"deployment",severity:"warning",message:"Preview deployment is still pending.",evidence:d});}catch(error){findings.push({kind:"deployment",severity:"warning",message:`Preview discovery failed: ${error instanceof Error?error.message:String(error)}`});}}
 const selectedProvider=input.provider??"playwright-mcp";const requiresPlaywright=["browser-game","website","web-app","interactive-experience"].includes(String(project.productKind??project.framework??""));let browser:Awaited<ReturnType<typeof executeBrowserQa>>|null=null;if(url){try{browser=await executeBrowserQa({url,provider:selectedProvider,interactions:input.interactions,assertions:input.assertions});for(const error of browser.errors)findings.push({kind:errorKind(error),severity:"error",message:error});if(browser.console.length)findings.push({kind:"console",severity:browser.judgement?.passed?"info":"warning",message:"Browser console evidence captured.",evidence:{count:browser.console.length}});if(browser.network.length)findings.push({kind:"network",severity:browser.judgement?.passed?"info":"warning",message:"Browser network evidence captured.",evidence:{count:browser.network.length}});if(browser.screenshots.length)findings.push({kind:"visual",severity:"info",message:"Screenshot evidence captured.",evidence:{count:browser.screenshots.length}});if(browser.assertions)findings.push({kind:"interaction",severity:browser.judgement?.passed?"info":"warning",message:"Structured browser assertions executed.",evidence:{assertions:input.assertions?.length??0}});if(browser.performance)findings.push({kind:"performance",severity:"info",message:"Navigation/performance evidence captured."});if(requiresPlaywright&&!browser.judgement?.authoritative)findings.push({kind:"interaction",severity:"error",message:"Playwright authoritative browser judgement is required for web/game completion."});if(browser.judgement?.authoritative&&!browser.judgement.passed&&!browser.errors.length)findings.push({kind:"interaction",severity:"error",message:"Playwright authoritative browser judgement failed."});}catch(error){findings.push({kind:"interaction",severity:"error",message:`Browser QA adapter failed: ${error instanceof Error?error.message:String(error)}`});}}else findings.push({kind:"interaction",severity:"warning",message:"No preview URL is available yet; browser execution is blocked."});
 const failed=findings.some(f=>f.severity==="error");const authoritativePass=Boolean(browser?.judgement?.authoritative&&browser.judgement.passed);const status=failed?"failed":url?(requiresPlaywright&&!authoritativePass?"blocked":"passed"):"blocked";await upsertQaEvidence({projectId:input.projectId,executionId:input.executionId,provider:selectedProvider,commitSha:input.commitSha,previewUrl:url,status,evidence:{ref,findings,browser,deployment,browserAuthority:{required:requiresPlaywright,provider:selectedProvider,authoritative:browser?.judgement?.authoritative??false,passed:authoritativePass}}});const repair=failed?createRepairPlan({projectId:input.projectId,verification:structural}):undefined;return{projectId:input.projectId,ref,url:url??null,provider:selectedProvider,status,findings,structural,deployment,browser,browserAuthority:{required:requiresPlaywright,authoritative:browser?.judgement?.authoritative??false,passed:authoritativePass},repair,requiresApproval:failed};
}
export function repairWorkerContract(input:{projectId:string;qa:Record<string,unknown>;approved:boolean}){if(!input.approved)return{status:"blocked",reason:"repair-approval-required"};return{status:"approved",projectId:input.projectId,maxCycles:3,strategy:"smallest-safe-patch",loop:["inspect-evidence","classify-failure","propose-explicit-file-replacements","approval","patch-gameshop-branch","preview-deploy","structural-qa","playwright-authoritative-qa","repeat-until-green"],writeGate:"GAME_SHOP_ALLOW_GITHUB_WRITES",qa:input.qa};}
