import { z } from "zod";
import { publicErrorMessage } from "./errors.js";
import { dispatchMissionHandoff, listMissionJobs, missionControlContext, missionControlInfo, missionJob, missionProjects, prepareMission, recordMissionVisualQa, transitionMission } from "./mission-control.js";

function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function fail(error:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(error){return fail(error);}};}
const projectId=z.string().min(1).max(120);
const executionId=z.string().min(8).max(140);
const phase=z.enum(["create","upgrade","fix","audit","release"]);
const preference=z.enum(["quality","speed","cost","bundle","open-source","balanced"]);
const permissions=z.object({read:z.boolean().optional(),plan:z.boolean().optional(),qa:z.boolean().optional(),execute:z.boolean().optional(),write:z.boolean().optional(),deploy:z.boolean().optional()});
export function registerMissionControlTools(server:any){
 server.registerTool("gameshop_mission_control_info",{title:"Mission Control",description:"Describe the project-aware Mission Control lifecycle, durable job model, handoff contract and QA/release gates.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(async()=>missionControlInfo()));
 server.registerTool("gameshop_mission_projects",{title:"Mission Control Projects",description:"List cross-product Game Shop projects across GitHub-backed and provider-backed sources, including canonical arcade games.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(async()=>missionProjects()));
 server.registerTool("gameshop_mission_context",{title:"Load Project Mission Context",description:"Load one project's source/runtime, deployment/preview records, recent QA, learned regressions, known issues, jobs, events and specialist lanes before routing work.",inputSchema:z.object({projectId}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},safe(({projectId}:any)=>missionControlContext(projectId)));
 server.registerTool("gameshop_plan_mission",{title:"Plan Project Mission",description:"Create a durable project-aware Mission Control job and structured specialist handoff packet. Planning persists state but does not execute specialists, write project source or deploy.",inputSchema:z.object({projectId,brief:z.string().min(3).max(6000),phase:phase.optional(),preference:preference.optional(),budgetUsd:z.number().min(0).max(100000).optional(),providerBudgets:z.record(z.string(),z.number().min(0)).optional(),permissions:permissions.optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(prepareMission));
 server.registerTool("gameshop_execute_mission_handoff",{title:"Dispatch Mission Specialist Handoff",description:"Dispatch the next or selected structured specialist task packet. Client/local specialists are explicitly returned as client-mediated handoffs rather than falsely claimed as server-executed.",inputSchema:z.object({executionId,handoffId:z.string().max(100).optional(),note:z.string().max(1000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},safe(dispatchMissionHandoff));
 server.registerTool("gameshop_mission_jobs",{title:"Mission Execution Dashboard",description:"List durable Mission Control jobs with stage, budget/cost, current specialist/provider, handoffs, artifacts, QA evidence, previews, errors and rollback information.",inputSchema:z.object({projectId:projectId.optional(),limit:z.number().int().min(1).max(100).optional()}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(listMissionJobs));
 server.registerTool("gameshop_mission_job",{title:"Mission Job",description:"Read one Mission Control job with execution, QA, preview, budget and rollback state.",inputSchema:z.object({executionId}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(({executionId}:any)=>missionJob(executionId)));
 server.registerTool("gameshop_record_visual_qa",{title:"Record Mission Visual QA",description:"Persist visual QA for one project/job, including before/after image URLs, Playwright findings, console errors, network errors and reviewer notes.",inputSchema:z.object({projectId,executionId:executionId.optional(),commitSha:z.string().max(64).optional(),previewUrl:z.string().url().optional(),status:z.enum(["queued","running","passed","failed","blocked"]),beforeUrl:z.string().url().optional(),afterUrl:z.string().url().optional(),findings:z.array(z.string().max(1000)).max(100).optional(),consoleErrors:z.array(z.string().max(2000)).max(100).optional(),networkErrors:z.array(z.string().max(2000)).max(100).optional(),playwright:z.record(z.string(),z.unknown()).optional(),notes:z.string().max(4000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(recordMissionVisualQa));
 server.registerTool("gameshop_execute_mission_start",{title:"Start Mission",description:"Move a planned Mission Control job into Running after execution permission is granted.",inputSchema:z.object({executionId,message:z.string().max(1000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(({executionId,message}:any)=>transitionMission({executionId,action:"start",message})));
 server.registerTool("gameshop_qa_mission",{title:"Move Mission to QA",description:"Move a Mission Control job into the QA stage while preserving durable execution history.",inputSchema:z.object({executionId,message:z.string().max(1000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(({executionId,message}:any)=>transitionMission({executionId,action:"qa",message})));
 server.registerTool("gameshop_repair_mission",{title:"Send Mission to Repair",description:"Move a Mission Control job into Repair after QA findings require another implementation cycle.",inputSchema:z.object({executionId,message:z.string().max(2000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(({executionId,message}:any)=>transitionMission({executionId,action:"repair",message})));
 server.registerTool("gameshop_approve_mission",{title:"Approve Mission as Ready",description:"Mark a mission Ready only when its persisted execution QA evidence is terminal and green.",inputSchema:z.object({executionId,message:z.string().max(1000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},safe(({executionId,message}:any)=>transitionMission({executionId,action:"approve",message})));
 server.registerTool("gameshop_release_mission",{title:"Evaluate and Release Mission",description:"Evaluate strict persisted release evidence and mark the mission Released only when the existing release governor returns green. This never bypasses deployment/provider authorization.",inputSchema:z.object({executionId,message:z.string().max(1000).optional()}),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}},safe(({executionId,message}:any)=>transitionMission({executionId,action:"release",message})));
 server.registerTool("gameshop_cancel_mission",{title:"Cancel Mission",description:"Cancel one durable Mission Control job.",inputSchema:z.object({executionId}),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:false}},safe(({executionId}:any)=>transitionMission({executionId,action:"cancel"})));
}
