import { z } from "zod";
import { ARTIFACT_STORE_SQL, artifactStoreInfo, createArtifact, getArtifact, listArtifacts, updateArtifact } from "./artifacts.js";
import { placeArtifactInProject } from "./artifact-placement.js";
import { artifactObjectStoreInfo, persistArtifactObject } from "./artifact-storage.js";
import { controlCenterSnapshot } from "./control-center.js";
import { publicErrorMessage } from "./errors.js";
import { cancelExecutionDurable, executionStoreInfo, resolveExecution, resolveExecutions } from "./execution-store.js";
import { elevenSpeech, elevenSpeechJob, externalEngineStatus, falJob, falSubmit, ludoDocs, ludoGenerate, ludoJob, meshyTask, meshyTextTo3D, replicatePredict, replicatePrediction, scenarioGenerate } from "./external-engines.js";
import { approveArtifactRepair, orchestrateArtifact, orchestrateReadyArtifacts, orchestrationSnapshot } from "./orchestrator.js";
import { createRepairPlan, verifyProject } from "./verification.js";
import { gameShopTaskCancel, gameShopTaskGet, taskBridgeInfo } from "./task-bridge.js";
import { qaWorkerInfo, repairWorkerContract, runQa } from "./qa-worker.js";
import { qaSwarmInfo, runQaSwarm } from "./qa-swarm.js";
import { browserFleetInfo, routeBrowserMission } from "./browser-fleet.js";
import { dispatchPlaywrightCi, listPlaywrightCiRuns, playwrightCiInfo } from "./playwright-ci.js";
import { discoverCapabilities, discoveryInfo } from "./capability-discovery.js";
import { applyApprovedPatch, patchWorkerInfo } from "./code-patch-worker.js";
import { createPreviewDeployment, previewDeploymentInfo } from "./preview-deployment.js";
import { approveCapability, CAPABILITY_TRUST_SQL, capabilityTrustInfo, discoverForTrust, inspectCapability, sandboxCapability, trustedCapabilities } from "./capability-trust.js";
import { QA_MEMORY_SQL, approveQaRecipe, createQaRecipe, listQaRecipes, qaMemoryInfo } from "./qa-memory.js";
import { qaReplayInfo, replayProjectRegressions, replayQaRecipe } from "./qa-replay.js";
import { evaluateRelease, releaseGovernorInfo } from "./release-governor.js";
import { chromeDiagnosticsInfo, dispatchChromeDiagnostics, listChromeDiagnosticsRuns } from "./chrome-diagnostics.js";
import { listQaEvidence, qaEvidenceInfo } from "./qa-evidence.js";

const checks=z.array(z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()})).max(25).optional();
const interactions=z.array(z.string().max(300)).max(8).optional();
const artifactKind=z.enum(["image","sprite","spritesheet","3d","video","audio","rive","document","code","archive","data","other"]);
const artifactPurpose=z.enum(["game","website","web-app","mobile-app","desktop-app","api-service","agent","automation","interactive-experience","digital-product","media-project","commerce","media","general","other"]);
const artifactContext=z.object({executionId:z.string().min(8).max(100),projectId:z.string().max(100).optional(),purpose:artifactPurpose.optional(),kind:artifactKind.optional(),name:z.string().max(300).optional(),targetPath:z.string().max(500).optional()}).optional();

function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function fail(error:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(error){return fail(error);}};}

export function registerPlatformTools(server:any){
  server.registerTool("gameshop_orchestration_status",{title:"Orchestration Status",description:"Read automatic persistence/place/verify orchestration state.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>orchestrationSnapshot()));
  server.registerTool("gameshop_orchestrate_artifact",{title:"Orchestrate Artifact",description:"Persist, place and verify a ready artifact through the Game Shop pipeline.",inputSchema:z.object({artifactId:z.string().min(8),branch:z.string().regex(/^gameshop\//).optional(),path:z.string().max(500).optional(),checks,autoPersist:z.boolean().optional(),autoPlace:z.boolean().optional(),autoVerify:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(async({artifactId,...policy}:any)=>orchestrateArtifact({artifactId,policy})));
  server.registerTool("gameshop_orchestrate_ready",{title:"Orchestrate Ready Artifacts",description:"Process ready artifacts awaiting orchestration.",inputSchema:z.object({executionId:z.string().max(100).optional(),projectId:z.string().max(100).optional(),limit:z.number().int().min(1).max(25).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(orchestrateReadyArtifacts));
  server.registerTool("gameshop_approve_repair",{title:"Approve Artifact Repair",description:"Approve or reject an artifact repair proposed after failed verification.",inputSchema:z.object({artifactId:z.string().min(8),approved:z.boolean()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(approveArtifactRepair));

  server.registerTool("gameshop_durable_execution_status",{title:"Durable Execution Status",description:"Resolve execution state from warm cache or durable storage.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(async({executionId}:any)=>({execution:await resolveExecution(executionId),store:executionStoreInfo()})));
  server.registerTool("gameshop_durable_executions",{title:"Durable Executions",description:"List persisted Game Shop executions.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>({executions:await resolveExecutions(),store:executionStoreInfo()})));
  server.registerTool("gameshop_cancel_durable_execution",{title:"Cancel Durable Execution",description:"Persist cancellation of an execution handle.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(async({executionId}:any)=>cancelExecutionDurable(executionId)));
  server.registerTool("gameshop_task_bridge",{title:"MCP Tasks Bridge",description:"Describe Game Shop alignment with MCP Tasks.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>taskBridgeInfo()));
  server.registerTool("gameshop_task_get",{title:"Task Status",description:"Represent an execution using MCP Task semantics.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(async({executionId}:any)=>gameShopTaskGet(executionId)));
  server.registerTool("gameshop_task_cancel",{title:"Cancel Task",description:"Cancel an execution through the Tasks bridge.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(async({executionId}:any)=>gameShopTaskCancel(executionId)));

  server.registerTool("gameshop_control_center",{title:"Game Shop Control Center",description:"Return the complete production-control snapshot.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>({snapshot:await controlCenterSnapshot(),storage:artifactObjectStoreInfo()})));
  server.registerTool("gameshop_object_store",{title:"Artifact Object Store",description:"Inspect permanent binary object storage.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>artifactObjectStoreInfo()));
  server.registerTool("gameshop_persist_artifact",{title:"Persist Artifact",description:"Copy a temporary provider artifact into permanent Game Shop object storage.",inputSchema:z.object({artifactId:z.string().min(8).max(100),fileName:z.string().max(180).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(persistArtifactObject));
  server.registerTool("gameshop_artifact_store",{title:"Artifact Store Status",description:"Describe the universal artifact store.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(async({includeSchema}:any)=>({store:artifactStoreInfo(),schema:includeSchema?ARTIFACT_STORE_SQL:undefined})));
  server.registerTool("gameshop_create_artifact",{title:"Register Artifact",description:"Attach a first-class artifact to an execution.",inputSchema:z.object({executionId:z.string().min(8).max(100),projectId:z.string().max(100).optional(),kind:artifactKind,purpose:artifactPurpose.default("general"),status:z.enum(["pending","ready","failed","archived"]).default("pending"),name:z.string().min(1).max(300),provider:z.string().max(100).optional(),providerJobId:z.string().max(300).optional(),mimeType:z.string().max(150).optional(),sourceUrl:z.string().url().max(2000).optional(),storageUrl:z.string().url().max(2000).optional(),metadata:z.record(z.string(),z.unknown()).default({})}),annotations:{readOnlyHint:false}},safe(createArtifact));
  server.registerTool("gameshop_artifact",{title:"Get Artifact",description:"Read one Game Shop artifact.",inputSchema:z.object({artifactId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(async({artifactId}:any)=>getArtifact(artifactId)));
  server.registerTool("gameshop_artifacts",{title:"List Artifacts",description:"List artifacts across products and executions.",inputSchema:z.object({executionId:z.string().max(100).optional(),projectId:z.string().max(100).optional(),kind:artifactKind.optional()}),annotations:{readOnlyHint:true}},safe(async(input:any)=>({artifacts:await listArtifacts(input),store:artifactStoreInfo()})));
  server.registerTool("gameshop_update_artifact",{title:"Update Artifact",description:"Update artifact lifecycle or storage metadata.",inputSchema:z.object({artifactId:z.string().min(8).max(100),status:z.enum(["pending","ready","failed","archived"]).optional(),providerJobId:z.string().max(300).optional(),mimeType:z.string().max(150).optional(),sourceUrl:z.string().url().max(2000).optional(),storageUrl:z.string().url().max(2000).optional(),metadata:z.record(z.string(),z.unknown()).optional()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(async({artifactId,...patch}:any)=>updateArtifact(artifactId,patch)));
  server.registerTool("gameshop_place_artifact",{title:"Place Artifact in Project",description:"Commit a ready artifact into a controlled Game Shop project branch.",inputSchema:z.object({artifactId:z.string().min(8),projectId:z.string().min(1),path:z.string().min(1).max(500),branch:z.string().regex(/^gameshop\//),message:z.string().max(300).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(placeArtifactInProject));

  server.registerTool("gameshop_verify_project",{title:"Verify Project",description:"Run project-scoped structural smoke checks against a GitHub ref.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),checks}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(verifyProject));
  server.registerTool("gameshop_plan_repair",{title:"Plan Repair",description:"Turn failed verification into a minimal repair plan.",inputSchema:z.object({projectId:z.string().min(1).max(100),verification:z.object({status:z.string(),checks:z.array(z.record(z.string(),z.unknown()))})}),annotations:{readOnlyHint:true}},safe(createRepairPlan));
  server.registerTool("gameshop_qa_worker",{title:"QA Worker",description:"Inspect live browser QA and repair policy.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>qaWorkerInfo()));
  server.registerTool("gameshop_run_qa",{title:"Run Product QA",description:"Run structural and live browser QA against a preview.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),checks,interactions,autoPreview:z.boolean().optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(runQa));
  server.registerTool("gameshop_qa_swarm_info",{title:"QA Swarm",description:"Describe the multi-lane QA release gate.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>qaSwarmInfo()));
  server.registerTool("gameshop_run_qa_swarm",{title:"Run QA Swarm",description:"Run live QA, fuse evidence and queue deterministic Playwright CI.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),url:z.string().url().optional(),checks,interactions,autoPreview:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(runQaSwarm));
  server.registerTool("gameshop_browser_fleet",{title:"Browser Fleet",description:"Describe the routed browser automation fleet.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>browserFleetInfo()));
  server.registerTool("gameshop_route_browser_mission",{title:"Route Browser Mission",description:"Choose the best browser engine for a QA mission.",inputSchema:z.object({mission:z.enum(["explore","regression","performance","repair-loop","visual-review"]),preferCloud:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(routeBrowserMission));
  server.registerTool("gameshop_playwright_ci_info",{title:"Playwright CI Lane",description:"Describe deterministic Playwright MCP CI.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>playwrightCiInfo()));
  server.registerTool("gameshop_queue_playwright_ci",{title:"Queue Playwright CI",description:"Queue deterministic Playwright QA for an HTTPS preview.",inputSchema:z.object({url:z.string().url(),projectId:z.string().max(100).optional(),executionId:z.string().max(100).optional(),interactions,ref:z.string().max(200).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(dispatchPlaywrightCi));
  server.registerTool("gameshop_playwright_ci_runs",{title:"Playwright CI Runs",description:"List recent deterministic Playwright QA runs.",inputSchema:z.object({limit:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(listPlaywrightCiRuns));
  server.registerTool("gameshop_chrome_diagnostics_info",{title:"Chrome Diagnostics",description:"Describe the Chrome DevTools deep-diagnostics lane.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>chromeDiagnosticsInfo()));
  server.registerTool("gameshop_queue_chrome_diagnostics",{title:"Queue Chrome Diagnostics",description:"Queue isolated Chrome DevTools diagnostics.",inputSchema:z.object({url:z.string().url(),projectId:z.string().max(100).optional(),executionId:z.string().max(100).optional(),ref:z.string().max(200).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(dispatchChromeDiagnostics));
  server.registerTool("gameshop_chrome_diagnostics_runs",{title:"Chrome Diagnostics Runs",description:"List Chrome diagnostics workflow runs.",inputSchema:z.object({limit:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(listChromeDiagnosticsRuns));
  server.registerTool("gameshop_repair_worker",{title:"Repair Worker",description:"Create an approval-gated iterative repair contract.",inputSchema:z.object({projectId:z.string().min(1).max(100),approved:z.boolean(),qa:z.record(z.string(),z.unknown())}),annotations:{readOnlyHint:false}},safe(repairWorkerContract));
  server.registerTool("gameshop_patch_worker",{title:"Code Patch Worker",description:"Inspect constrained patch-worker limits.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>patchWorkerInfo()));
  server.registerTool("gameshop_apply_patch",{title:"Apply Approved Patch",description:"Apply explicit replacement-file patches to a gameshop/* branch and verify scope safety.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().regex(/^gameshop\//),baseRef:z.string().max(200).optional(),approved:z.boolean(),title:z.string().max(300).optional(),operations:z.array(z.object({path:z.string().min(1).max(500),content:z.string().max(120000),expectedSha:z.string().optional(),reason:z.string().max(300).optional()})).min(1).max(8)}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(applyApprovedPatch));

  server.registerTool("gameshop_preview_info",{title:"Preview Deployment",description:"Describe preview deployment/discovery configuration.",inputSchema:z.object({projectId:z.string().max(100).optional()}),annotations:{readOnlyHint:true}},safe(async({projectId}:any)=>previewDeploymentInfo(projectId)));
  server.registerTool("gameshop_create_preview",{title:"Create Preview",description:"Trigger or discover a preview for a controlled gameshop/* branch.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().regex(/^gameshop\//),commitSha:z.string().optional(),waitMs:z.number().int().min(0).max(120000).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(createPreviewDeployment));

  server.registerTool("gameshop_discovery_info",{title:"Self Expansion",description:"Describe continuous MCP capability discovery.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>discoveryInfo()));
  server.registerTool("gameshop_discover_capabilities",{title:"Discover Capabilities",description:"Search the official MCP Registry for capability gaps.",inputSchema:z.object({query:z.string().min(2).max(200),limit:z.number().int().min(1).max(50).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(discoverCapabilities));
  server.registerTool("gameshop_trust_pipeline",{title:"Capability Trust Pipeline",description:"Describe discover → inspect → sandbox → score → approve/promote policy.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(async({includeSchema}:any)=>({trust:capabilityTrustInfo(),schema:includeSchema?CAPABILITY_TRUST_SQL:undefined,promoted:await trustedCapabilities()})));
  server.registerTool("gameshop_discover_for_trust",{title:"Discover for Trust",description:"Search the official MCP Registry and prepare trust candidates.",inputSchema:z.object({query:z.string().min(2).max(200),limit:z.number().int().min(1).max(50).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(discoverForTrust));
  server.registerTool("gameshop_inspect_capability",{title:"Inspect MCP Capability",description:"Validate a remote MCP endpoint before sandboxing.",inputSchema:z.object({name:z.string().min(1).max(200),description:z.string().max(1000).optional(),endpoint:z.string().url(),source:z.string().max(100).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(inspectCapability));
  server.registerTool("gameshop_sandbox_capability",{title:"Sandbox MCP Capability",description:"Initialize a candidate MCP and list its tools only.",inputSchema:z.object({name:z.string().min(1).max(200),description:z.string().max(1000).optional(),endpoint:z.string().url(),source:z.string().max(100).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(sandboxCapability));
  server.registerTool("gameshop_approve_capability",{title:"Approve MCP Capability",description:"Explicitly approve/reject a sandbox-passed MCP for the trusted arsenal.",inputSchema:z.object({name:z.string().min(1).max(200),approved:z.boolean()}),annotations:{readOnlyHint:false}},safe(approveCapability));

  const qaCheck=z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()});
  server.registerTool("gameshop_qa_memory",{title:"QA Memory",description:"Describe durable learned regression memory.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(async({includeSchema}:any)=>({memory:qaMemoryInfo(),replay:qaReplayInfo(),schema:includeSchema?QA_MEMORY_SQL:undefined})));
  server.registerTool("gameshop_create_qa_recipe",{title:"Create QA Recipe",description:"Create a reusable regression recipe.",inputSchema:z.object({projectId:z.string().min(1).max(100),name:z.string().min(1).max(200),description:z.string().max(1000).optional(),checks:z.array(qaCheck).max(25).optional(),interactions:z.array(z.string().max(300)).max(8).optional(),createdFromExecutionId:z.string().max(100).optional(),approved:z.boolean().optional()}),annotations:{readOnlyHint:false}},safe(createQaRecipe));
  server.registerTool("gameshop_qa_recipes",{title:"QA Recipes",description:"List learned regression recipes.",inputSchema:z.object({projectId:z.string().max(100).optional(),approvedOnly:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(async(input:any)=>({recipes:await listQaRecipes(input),memory:qaMemoryInfo()})));
  server.registerTool("gameshop_approve_qa_recipe",{title:"Approve QA Recipe",description:"Approve or reject a learned regression recipe.",inputSchema:z.object({recipeId:z.string().min(8).max(100),approved:z.boolean()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(async({recipeId,approved}:any)=>approveQaRecipe(recipeId,approved)));
  server.registerTool("gameshop_replay_qa_recipe",{title:"Replay QA Recipe",description:"Replay one approved regression recipe through the QA swarm.",inputSchema:z.object({recipeId:z.string().min(8).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),autoPreview:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(replayQaRecipe));
  server.registerTool("gameshop_replay_project_regressions",{title:"Replay Project Regressions",description:"Replay approved regression memory and return a composite gate.",inputSchema:z.object({projectId:z.string().min(1).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),limit:z.number().int().min(1).max(20).optional(),autoPreview:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(replayProjectRegressions));
  server.registerTool("gameshop_release_governor",{title:"Release Governor",description:"Describe the evidence and regression release gate.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>releaseGovernorInfo()));
  server.registerTool("gameshop_evaluate_release",{title:"Evaluate Release",description:"Evaluate project release readiness from orchestration and QA evidence.",inputSchema:z.object({projectId:z.string().min(1).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),runRegressions:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional(),commitSha:z.string().max(80).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(evaluateRelease));
  server.registerTool("gameshop_qa_evidence",{title:"QA Evidence Ledger",description:"List persisted terminal and in-flight QA evidence.",inputSchema:z.object({projectId:z.string().max(100).optional(),executionId:z.string().max(100).optional(),provider:z.string().max(100).optional(),limit:z.number().int().min(1).max(200).optional()}),annotations:{readOnlyHint:true}},safe(async(input:any)=>({info:qaEvidenceInfo(),evidence:await listQaEvidence(input)})));

  server.registerTool("gameshop_external_engines",{title:"External Engine Status",description:"Show callable external engines without exposing secrets.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>externalEngineStatus()));
  server.registerTool("gameshop_meshy_text_to_3d",{title:"Meshy Text to 3D",description:"Create a Meshy 3D task with artifact capture.",inputSchema:z.object({prompt:z.string().max(600).default(""),mode:z.enum(["preview","refine"]).optional(),previewTaskId:z.string().optional(),enablePbr:z.boolean().optional(),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(meshyTextTo3D));
  server.registerTool("gameshop_meshy_task",{title:"Meshy Task Status",description:"Read Meshy status and finalize matching artifacts.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(async({id}:any)=>meshyTask(id)));
  server.registerTool("gameshop_fal_submit",{title:"fal Queue Submit",description:"Submit fal inference with artifact capture.",inputSchema:z.object({model:z.string().min(3).max(200),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(falSubmit));
  server.registerTool("gameshop_fal_job",{title:"fal Job",description:"Poll fal and orchestrate completed artifacts.",inputSchema:z.object({jobId:z.string().min(1),statusUrl:z.string().url(),responseUrl:z.string().url().optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(falJob));
  server.registerTool("gameshop_replicate_predict",{title:"Replicate Prediction",description:"Create an async Replicate prediction with artifact capture.",inputSchema:z.object({version:z.string().min(3).max(300),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(replicatePredict));
  server.registerTool("gameshop_replicate_prediction",{title:"Replicate Prediction Status",description:"Read Replicate status and orchestrate completed artifacts.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(async({id}:any)=>replicatePrediction(id)));
  server.registerTool("gameshop_ludo_generate",{title:"Ludo Generate",description:"Call an allowlisted Ludo generator with artifact capture.",inputSchema:z.object({tool:z.string().min(3).max(100),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(ludoGenerate));
  server.registerTool("gameshop_ludo_job",{title:"Ludo Job",description:"Poll Ludo and orchestrate completed artifacts.",inputSchema:z.object({id:z.string().min(1),wait:z.number().int().min(0).max(60).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(ludoJob));
  server.registerTool("gameshop_ludo_docs",{title:"Ludo Generator Docs",description:"Read Ludo generator documentation.",inputSchema:z.object({doc:z.string().max(100).optional(),sections:z.string().max(500).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(ludoDocs));
  server.registerTool("gameshop_elevenlabs_speech",{title:"ElevenLabs Speech",description:"Start asynchronous ElevenLabs speech and capture an audio artifact.",inputSchema:z.object({text:z.string().min(1).max(5000),voice:z.string().min(1).max(200),modelId:z.string().max(100).optional(),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(elevenSpeech));
  server.registerTool("gameshop_elevenlabs_speech_job",{title:"ElevenLabs Speech Job",description:"Poll ElevenLabs and orchestrate completed audio.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(async({id}:any)=>elevenSpeechJob(id)));
  server.registerTool("gameshop_scenario_generate",{title:"Scenario Universal Generate",description:"Generate image, video, 3D or audio through Scenario.",inputSchema:z.object({modelId:z.string().min(3).max(200),body:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(scenarioGenerate));
}
