import { z } from "zod";
import { budgetStatus, governanceInfo, listEvents, listPreviews, markPreviewTested, recordPreview, reserveCost, setExecutionBudget, settleCost } from "./governance-ledger.js";
import { distributedRateLimitInfo } from "./distributed-rate-limit.js";
import { checkIntegrationHealth, checkIntegrationNetwork, integrationHealthInfo, routeHealthyIntegration } from "./integration-health.js";
import { getProjectV2, listProjectsV2, projectRegistryV2Info, registerProjectV2, removeProjectV2 } from "./project-registry-v2.js";
import { providerReconcilerInfo, reconcileArtifact, reconcilePendingProviders } from "./provider-reconciler.js";
import { approveCapabilityV2, evaluateCapabilityV2, reportCapabilityIncident, scoreCapabilityV2, trustPipelineV2Info, trustedCapabilityPortfolio } from "./trust-pipeline-v2.js";
import { continuousDiscoveryInfo, discoverCapabilityGap, discoverySweep } from "./continuous-discovery.js";
import { continuitySnapshot, handoffExecution, listHandoffs, multiAiContinuityInfo, verifyContinuity } from "./multi-ai-continuity.js";
import { controlCenterV2Info, controlCenterV2Snapshot } from "./control-center-v2.js";
import { scenarioDryRun, scenarioGenerateV2, scenarioJobV2, scenarioV2Info } from "./scenario-v2.js";

function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function fail(e:unknown){return{isError:true,content:[{type:"text" as const,text:`Game Shop request failed: ${e instanceof Error?e.message:String(e)}`}]};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(e){return fail(e);}};}
const ai=z.enum(["grok","chatgpt","codex","claude","cursor","other"]);
const trustSignals=z.object({officialRegistry:z.boolean().optional(),publisherVerified:z.boolean().optional(),repositoryVerified:z.boolean().optional(),releaseProvenance:z.boolean().optional(),packageIntegrity:z.boolean().optional(),oauth:z.boolean().optional(),toolCount:z.number().int().min(0).max(1000).optional(),riskyTools:z.array(z.string()).max(100).optional(),filesystem:z.boolean().optional(),subprocess:z.boolean().optional(),payment:z.boolean().optional(),latencyMs:z.number().min(0).optional(),errorRate:z.number().min(0).max(1).optional(),pricingKnown:z.boolean().optional(),incidents:z.number().int().min(0).optional()});
export function registerFutureTools(server:any){
 server.registerTool("gameshop_governance_info",{title:"Governance Ledger",description:"Inspect cost, event and preview governance storage.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>governanceInfo()));
 server.registerTool("gameshop_set_execution_budget",{title:"Authorize Execution Budget",description:"Set an execution-level USD budget and optional provider sub-budgets.",inputSchema:z.object({executionId:z.string().min(8).max(100),budgetUsd:z.number().min(0).max(100000),providerBudgets:z.record(z.string(),z.number().min(0)).optional()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(setExecutionBudget));
 server.registerTool("gameshop_budget_status",{title:"Budget Status",description:"Read remaining authorized execution budget.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(({executionId}:any)=>budgetStatus(executionId)));
 server.registerTool("gameshop_reserve_cost",{title:"Reserve Provider Cost",description:"Reserve estimated provider spend and hard-fail if it exceeds remaining authorized budget.",inputSchema:z.object({executionId:z.string().min(8).max(100),provider:z.string().min(1).max(100),estimatedUsd:z.number().min(0).max(100000)}),annotations:{readOnlyHint:false}},safe(reserveCost));
 server.registerTool("gameshop_settle_cost",{title:"Settle Provider Cost",description:"Settle actual provider cost and release a prior reservation.",inputSchema:z.object({executionId:z.string().min(8).max(100),provider:z.string().min(1).max(100),actualUsd:z.number().min(0).max(100000),reservedUsd:z.number().min(0).optional(),creditsUsed:z.number().min(0).optional()}),annotations:{readOnlyHint:false,idempotentHint:false}},safe(settleCost));
 server.registerTool("gameshop_events",{title:"Observability Ledger",description:"Read the forensic Game Shop event history; secret-bearing fields are redacted before persistence.",inputSchema:z.object({executionId:z.string().max(100).optional(),projectId:z.string().max(100).optional(),limit:z.number().int().min(1).max(100).optional()}),annotations:{readOnlyHint:true}},safe(listEvents));
 server.registerTool("gameshop_previews",{title:"Preview Registry",description:"Read commit-addressed preview deployment records.",inputSchema:z.object({projectId:z.string().max(100).optional(),limit:z.number().int().min(1).max(100).optional()}),annotations:{readOnlyHint:true}},safe(listPreviews));
 server.registerTool("gameshop_record_preview",{title:"Record Preview",description:"Register a preview with branch and commit binding.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(1).max(200),commitSha:z.string().max(64).optional(),provider:z.string().min(1).max(80),deploymentId:z.string().max(200).optional(),previewUrl:z.string().url().optional(),status:z.string().max(50)}),annotations:{readOnlyHint:false}},safe(recordPreview));
 server.registerTool("gameshop_mark_preview_tested",{title:"Mark Preview Tested",description:"Bind successful QA to the exact preview URL and commit SHA.",inputSchema:z.object({projectId:z.string().min(1).max(100),commitSha:z.string().min(7).max(64),previewUrl:z.string().url()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(markPreviewTested));
 server.registerTool("gameshop_rate_limit_policy",{title:"Distributed Rate Limit",description:"Describe distributed rate-limit classes and quotas.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>distributedRateLimitInfo()));
 server.registerTool("gameshop_integration_health_info",{title:"Integration Health Network",description:"Describe integration health states and routing policy.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>integrationHealthInfo()));
 server.registerTool("gameshop_check_integration_health",{title:"Check Integration Health",description:"Actively probe one registered integration for auth, reachability, protocol, tool-contract and latency health.",inputSchema:z.object({id:z.string().min(1).max(100)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(({id}:any)=>checkIntegrationHealth(id)));
 server.registerTool("gameshop_check_integration_network",{title:"Check Integration Network",description:"Probe a bounded set of remote integrations and summarize health.",inputSchema:z.object({ids:z.array(z.string().max(100)).max(20).optional(),limit:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(checkIntegrationNetwork));
 server.registerTool("gameshop_route_healthy_integration",{title:"Route Healthy Integration",description:"Rank candidate engines using latest health state and latency.",inputSchema:z.object({candidates:z.array(z.string().min(1).max(100)).min(1).max(20)}),annotations:{readOnlyHint:true}},safe(({candidates}:any)=>routeHealthyIntegration(candidates)));
 server.registerTool("gameshop_project_registry_v2",{title:"Project Registry V2",description:"Describe the dynamic database-backed project registry.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>projectRegistryV2Info()));
 server.registerTool("gameshop_projects_v2",{title:"List Projects V2",description:"List dynamic projects plus legacy fallbacks.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>listProjectsV2()));
 server.registerTool("gameshop_project_v2",{title:"Get Project V2",description:"Get one dynamic project registration.",inputSchema:z.object({projectId:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},safe(({projectId}:any)=>getProjectV2(projectId)));
 server.registerTool("gameshop_register_project_v2",{title:"Register Project V2",description:"Register or update a product without changing Game Shop source code.",inputSchema:z.object({projectId:z.string().min(1).max(100),name:z.string().min(1).max(200),productKind:z.string().min(1).max(80),repo:z.string().min(3).max(200),projectRoot:z.string().max(500),defaultBranch:z.string().min(1).max(200),framework:z.string().max(80).optional(),deploymentProvider:z.string().max(80).optional(),deploymentProject:z.string().max(200).optional(),artifactDestinations:z.record(z.string(),z.string()).optional(),qaPolicy:z.record(z.string(),z.unknown()).optional(),requiredRegressions:z.array(z.string().max(200)).max(50).optional(),permissionProfile:z.record(z.string(),z.unknown()).optional(),budgetProfile:z.record(z.string(),z.unknown()).optional(),brandContext:z.record(z.string(),z.unknown()).optional()}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(registerProjectV2));
 server.registerTool("gameshop_remove_project_v2",{title:"Remove Project V2",description:"Remove a dynamic project registration; legacy built-ins remain available as fallback.",inputSchema:z.object({projectId:z.string().min(1).max(100)}),annotations:{readOnlyHint:false,destructiveHint:true}},safe(({projectId}:any)=>removeProjectV2(projectId)));
 server.registerTool("gameshop_provider_reconciler",{title:"Provider Reconciler",description:"Describe automatic async provider reconciliation and finalization.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>providerReconcilerInfo()));
 server.registerTool("gameshop_reconcile_artifact",{title:"Reconcile Provider Artifact",description:"Poll the artifact provider job once, finalize terminal artifacts and continue orchestration.",inputSchema:z.object({artifactId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(({artifactId}:any)=>reconcileArtifact(artifactId)));
 server.registerTool("gameshop_reconcile_pending",{title:"Reconcile Pending Providers",description:"Reconcile a bounded batch of pending provider artifacts.",inputSchema:z.object({executionId:z.string().max(100).optional(),projectId:z.string().max(100).optional(),limit:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(reconcilePendingProviders));
 server.registerTool("gameshop_scenario_v2_info",{title:"Scenario Adapter V2",description:"Describe Scenario Basic-auth generation, dry-run cost preview and job reconciliation.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>scenarioV2Info()));
 server.registerTool("gameshop_scenario_dry_run",{title:"Scenario Cost Preview",description:"Run Scenario dry-run generation to inspect cost/validation without starting a paid generation job.",inputSchema:z.object({modelId:z.string().min(1).max(200),body:z.record(z.string(),z.unknown())}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(scenarioDryRun));
 server.registerTool("gameshop_scenario_generate_v2",{title:"Scenario Generate V2",description:"Start a Scenario generation job. Paid generation remains separately locked.",inputSchema:z.object({modelId:z.string().min(1).max(200),body:z.record(z.string(),z.unknown()),artifact:z.object({executionId:z.string().min(8).max(100),projectId:z.string().max(100).optional(),purpose:z.string().max(80).optional(),kind:z.string().max(80).optional(),name:z.string().max(300).optional(),targetPath:z.string().max(500).optional()}).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(scenarioGenerateV2));
 server.registerTool("gameshop_scenario_job_v2",{title:"Scenario Job V2",description:"Poll a Scenario job, finalize matching artifacts and continue orchestration.",inputSchema:z.object({jobId:z.string().min(1).max(300)}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(({jobId}:any)=>scenarioJobV2(jobId)));
 server.registerTool("gameshop_trust_pipeline_v2",{title:"Trust Pipeline V2",description:"Describe supply-chain aware capability trust scoring.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>trustPipelineV2Info()));
 server.registerTool("gameshop_score_capability_v2",{title:"Score Capability V2",description:"Score a candidate across provenance, integrity, auth, scope, reliability, cost and incident signals.",inputSchema:trustSignals,annotations:{readOnlyHint:true}},safe(scoreCapabilityV2));
 server.registerTool("gameshop_evaluate_capability_v2",{title:"Evaluate Capability V2",description:"Inspect and sandbox a remote MCP then apply Trust Pipeline V2 scoring.",inputSchema:z.object({name:z.string().min(1).max(200),description:z.string().max(1000).optional(),endpoint:z.string().url(),source:z.string().max(100).optional(),signals:trustSignals.optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(evaluateCapabilityV2));
 server.registerTool("gameshop_approve_capability_v2",{title:"Approve Capability V2",description:"Approve/reject a sandboxed capability only after V2 score clears threshold.",inputSchema:z.object({name:z.string().min(1).max(200),approved:z.boolean(),score:z.number().min(0).max(100)}),annotations:{readOnlyHint:false}},safe(approveCapabilityV2));
 server.registerTool("gameshop_report_capability_incident",{title:"Report Capability Incident",description:"Record a post-promotion incident and trigger rescore/quarantine recommendation.",inputSchema:z.object({name:z.string().min(1).max(200),severity:z.enum(["low","medium","high"]),message:z.string().min(1).max(500)}),annotations:{readOnlyHint:false}},safe(reportCapabilityIncident));
 server.registerTool("gameshop_trusted_portfolio",{title:"Trusted Capability Portfolio",description:"List trusted capabilities and incident counts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>trustedCapabilityPortfolio()));
 server.registerTool("gameshop_continuous_discovery",{title:"Continuous Capability Discovery",description:"Describe the continuous ecosystem-expansion policy.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>continuousDiscoveryInfo()));
 server.registerTool("gameshop_discover_gap",{title:"Discover Capability Gap",description:"Detect whether a requested capability is missing and search the official MCP Registry when needed.",inputSchema:z.object({capability:z.string().min(2).max(200),limit:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(discoverCapabilityGap));
 server.registerTool("gameshop_discovery_sweep",{title:"Discovery Sweep",description:"Check multiple capability needs and discover candidates for gaps.",inputSchema:z.object({capabilities:z.array(z.string().min(2).max(200)).min(1).max(12),limitPerGap:z.number().int().min(1).max(20).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(discoverySweep));
 server.registerTool("gameshop_multi_ai_continuity",{title:"Multi-AI Continuity",description:"Describe the shared authoritative state model across Grok, ChatGPT, Codex, Claude and Cursor.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>multiAiContinuityInfo()));
 server.registerTool("gameshop_handoff_execution",{title:"Handoff Execution",description:"Create a cross-AI handoff snapshot bound to one authoritative Game Shop execution.",inputSchema:z.object({executionId:z.string().min(8).max(100),from:ai,to:ai,note:z.string().max(500).optional()}),annotations:{readOnlyHint:false}},safe(handoffExecution));
 server.registerTool("gameshop_handoffs",{title:"List AI Handoffs",description:"List durable cross-AI handoff records.",inputSchema:z.object({executionId:z.string().max(100).optional(),limit:z.number().int().min(1).max(100).optional()}),annotations:{readOnlyHint:true}},safe(listHandoffs));
 server.registerTool("gameshop_continuity_snapshot",{title:"Continuity Snapshot",description:"Read execution, artifacts, QA evidence and event history as one cross-AI truth snapshot.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(({executionId}:any)=>continuitySnapshot(executionId)));
 server.registerTool("gameshop_verify_continuity",{title:"Verify Continuity",description:"Verify expected artifact/evidence identifiers survive an AI handoff.",inputSchema:z.object({executionId:z.string().min(8).max(100),expectedArtifactIds:z.array(z.string()).max(100).optional(),expectedEvidenceIds:z.array(z.string()).max(100).optional()}),annotations:{readOnlyHint:true}},safe(verifyContinuity));
 server.registerTool("gameshop_control_center_v2_info",{title:"Control Center V2",description:"Describe the human supervisory cockpit.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>controlCenterV2Info()));
 server.registerTool("gameshop_control_center_v2",{title:"Open Control Center V2",description:"Return the complete supervisory snapshot with costs, events, previews, health, trust and continuity.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>controlCenterV2Snapshot()));
}
