import { z } from "zod";
import { publicErrorMessage } from "./errors.js";
import { captureMissionQa, executeMissionAdapter, missionExecutionAdapterCatalog, repairAndRerunMissionQa } from "./mission-execution-adapters.js";
function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(error){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]};}};}
const executionId=z.string().min(8).max(140);const patch=z.array(z.object({path:z.string().min(1).max(500),content:z.string().max(120000),expectedSha:z.string().max(80).optional(),reason:z.string().max(500).optional()})).min(1).max(8);
export function registerMissionExecutionTools(server:any){
 server.registerTool("gameshop_mission_execution_adapters",{title:"Mission Execution Adapters",description:"Describe which Mission Control handoffs can execute server-side and which remain client/local bridges.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(async()=>missionExecutionAdapterCatalog()));
 server.registerTool("gameshop_execute_mission_adapter",{title:"Execute Mission Adapter",description:"Execute a server-direct GitHub inspection, browser QA, provider capability, or client/local bridge handoff. Source mutation is intentionally excluded and requires the separate Write+QA repair tool.",inputSchema:z.object({executionId,adapter:z.enum(["github-inspect","browser-qa","provider-capability","client-bridge"]),url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),baseRef:z.string().max(220).optional(),capability:z.enum(["model-inference","image-generation","video-generation","audio-generation","speech-generation","3d-generation","upscaling","asset-upload","asset-management"]).optional(),payloads:z.record(z.string(),z.record(z.string(),z.unknown())).optional(),preferredProvider:z.enum(["fal","replicate","elevenlabs","scenario","cloudinary"]).optional(),target:z.string().max(200).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},safe(executeMissionAdapter));
 server.registerTool("gameshop_qa_capture_mission",{title:"Capture Mission QA",description:"Automatically capture Mission Control structural/browser QA, including screenshots, console and network evidence, and persist a before/after visual record when consecutive screenshots are available.",inputSchema:z.object({executionId,url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},safe(captureMissionQa));
 server.registerTool("gameshop_qa_repair_and_rerun",{title:"Repair and Rerun Mission QA",description:"Move a mission into Repair and rerun automatic QA after an external/client repair is complete. This tool never writes project source.",inputSchema:z.object({executionId,url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),assumeRepairApplied:z.boolean().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},safe(repairAndRerunMissionQa));
 server.registerTool("gameshop_apply_patch_mission_and_rerun",{title:"Apply Mission Repair Patch and Rerun QA",description:"Apply an explicitly approved source-aware GitHub replacement patch on a gameshop/* branch, then automatically rerun Mission QA. Requires independent Write and QA authorization.",inputSchema:z.object({executionId,url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),branch:z.string().regex(/^gameshop\/[a-z0-9._/-]+$/i).optional(),operations:patch,title:z.string().max(500).optional()}),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}},safe(repairAndRerunMissionQa));
}
