import { z } from "zod";
import { publicErrorMessage } from "./errors.js";
import { captureMissionQa, executeMissionAdapter, missionExecutionAdapterCatalog, repairAndRerunMissionQa } from "./mission-execution-adapters.js";
function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(error){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]};}};}
const executionId=z.string().min(8).max(140);const patch=z.array(z.object({path:z.string().min(1).max(500),content:z.string().max(120000),expectedSha:z.string().max(80).optional(),reason:z.string().max(500).optional()})).max(8).optional();
export function registerMissionExecutionTools(server:any){
 server.registerTool("gameshop_mission_execution_adapters",{title:"Mission Execution Adapters",description:"Describe which Mission Control handoffs can execute server-side and which remain client/local bridges.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},safe(async()=>missionExecutionAdapterCatalog()));
 server.registerTool("gameshop_execute_mission_adapter",{title:"Execute Mission Adapter",description:"Execute one explicit server-direct Mission adapter (GitHub inspect/patch, browser QA, provider capability) or return a client/local bridge contract. Runtime credentials and Game Shop safety gates remain authoritative.",inputSchema:z.object({executionId,adapter:z.enum(["github-inspect","github-patch","browser-qa","provider-capability","client-bridge"]),url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),branch:z.string().max(220).optional(),baseRef:z.string().max(220).optional(),operations:patch,title:z.string().max(500).optional(),capability:z.enum(["model-inference","image-generation","video-generation","audio-generation","speech-generation","3d-generation","upscaling","asset-upload","asset-management"]).optional(),payloads:z.record(z.string(),z.record(z.string(),z.unknown())).optional(),preferredProvider:z.enum(["fal","replicate","elevenlabs","scenario","cloudinary"]).optional(),target:z.string().max(200).optional()}),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}},safe(executeMissionAdapter));
 server.registerTool("gameshop_qa_capture_mission",{title:"Capture Mission QA",description:"Automatically capture Mission Control structural/browser QA, including screenshots, console and network evidence, and persist a before/after visual record when consecutive screenshots are available.",inputSchema:z.object({executionId,url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},safe(captureMissionQa));
 server.registerTool("gameshop_qa_repair_and_rerun",{title:"Repair and Rerun Mission QA",description:"Move a mission into Repair, optionally apply an approved GitHub replacement patch, then rerun automatic QA. Client/local projects return an explicit bridge when server-side repair is impossible.",inputSchema:z.object({executionId,url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),branch:z.string().max(220).optional(),operations:patch,title:z.string().max(500).optional(),assumeRepairApplied:z.boolean().optional()}),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}},safe(repairAndRerunMissionQa));
}
