import { z } from "zod";
import { capabilityCatalog } from "./catalog.js";
import { publicErrorMessage } from "./errors.js";
import { prepareExecution } from "./execution.js";
import { cancelExecution, executionStoreInfo, getExecution, listExecutions } from "./execution-store.js";
import { executeGitHubPlan } from "./executor.js";
import { githubCreateProjectBranch, githubCreateProjectPullRequest, githubInspectProject, githubReadProjectFile, githubUpsertProjectFile, githubVerifyProjectBranch } from "./github-execution.js";
import { integrationRegistry, integrationStatus } from "./integrations.js";
import { integrationReadiness, invokeIntegration, orchestrateIntegrations } from "./integration-runtime.js";
import { routeMotion, motionRoutingMatrix } from "./motion-router.js";
import { routeMultiDomain, multiDomainMatrix } from "./multidomain-router.js";
import { createBuildPlan } from "./planner.js";
import { createProjectPlan } from "./project-planner.js";
import { listProjects, projectContext } from "./projects.js";
import { autoSpriteCreateCharacter, autoSpriteGenerateAnimations, autoSpriteGetJob, autoSpriteGetSpritesheet, providerStatus, spriteCookGenerate, spriteCookGetJob, spriteCookListModels } from "./providers.js";
import { routeCapability, routingMatrix } from "./router.js";
import { spendPolicy } from "./spend.js";
import { gameShopSystemAudit } from "./system-audit.js";

function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}};}
function fail(error:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]};}
function safe(fn:(input:any)=>unknown|Promise<unknown>){return async(input:any)=>{try{return result(await fn(input));}catch(error){return fail(error);}};}

const productKind=z.enum(["website","web-app","browser-game","mobile-app","desktop-app","api-service","agent","automation","interactive-experience","digital-product","media-project","commerce","other"]);
const buildGoal=z.enum(["premium","cinematic","playful","minimal","immersive","conversion","performance","reliable","secure","scalable"]);
const framework=z.enum(["react","vanilla","vue","phaser","three","node","python","expo","any"]);
const buildDomain=z.enum(["ui","motion","3d","shader","video","audio","backend","data","storage","auth","testing","deployment","commerce","observability","design-reference","agent-platform"]);
const buildInput={brief:z.string().min(3).max(4000),product:productKind,goals:z.array(buildGoal).max(10).optional(),framework:framework.optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),includeDomains:z.array(buildDomain).max(16).optional()};
const targetInput=z.object({repository:z.string().min(3).max(200).optional(),branch:z.string().min(1).max(200).optional(),project:z.string().min(1).max(100).optional(),environment:z.enum(["development","preview","production"]).optional()}).optional();
const operationInput=z.object({path:z.string().min(1).max(500),content:z.string().max(500000),message:z.string().min(3).max(200),sha:z.string().regex(/^[0-9a-f]{40}$/).optional()});
const integrationInvokeInput={id:z.string().min(1).max(100),mode:z.enum(["mcp-list-tools","mcp-call","api"]).optional(),tool:z.string().min(1).max(200).optional(),arguments:z.record(z.string(),z.unknown()).optional(),method:z.enum(["GET","POST","PUT","PATCH","DELETE"]).optional(),path:z.string().max(500).optional(),body:z.unknown().optional(),timeoutMs:z.number().int().min(1000).max(60000).optional()};

export function registerCoreTools(server:any){
  server.registerTool("gameshop_system_audit",{title:"Game Shop System Audit",description:"Inspect runtime posture, stores, projects, integrations, OAuth, GitHub, QA, preview and protocol readiness.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>gameShopSystemAudit()));
  server.registerTool("gameshop_list_providers",{title:"List Game Shop Providers",description:"List configured providers without exposing API keys.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>({spend:spendPolicy(),providers:providerStatus()})));
  server.registerTool("gameshop_spend_policy",{title:"Game Shop Spend Policy",description:"Show whether paid generation is allowed.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>spendPolicy()));
  server.registerTool("gameshop_capability_catalog",{title:"Game Shop Capability Catalog",description:"List build capabilities available to Game Shop agents.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>capabilityCatalog()));
  server.registerTool("gameshop_integrations",{title:"Game Shop Integration Registry",description:"List verified integration contracts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>integrationRegistry()));
  server.registerTool("gameshop_integration_status",{title:"Game Shop Integration Status",description:"Inspect one verified integration.",inputSchema:z.object({id:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},safe(({id}:any)=>integrationStatus(id)));
  server.registerTool("gameshop_integration_readiness",{title:"Integration Readiness",description:"Show which integrations are callable in this runtime.",inputSchema:z.object({id:z.string().min(1).max(100).optional()}),annotations:{readOnlyHint:true}},safe(({id}:any)=>integrationReadiness(id)));
  server.registerTool("gameshop_invoke_integration",{title:"Invoke Game Shop Integration",description:"Actively call a registered remote MCP tool or REST API endpoint behind execution/spend locks.",inputSchema:z.object(integrationInvokeInput),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},safe(invokeIntegration));
  server.registerTool("gameshop_orchestrate_integrations",{title:"Orchestrate Game Shop Integrations",description:"Execute up to ten registered MCP/API calls in order.",inputSchema:z.object({steps:z.array(z.object({...integrationInvokeInput,optional:z.boolean().optional()})).min(1).max(10)}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(({steps}:any)=>orchestrateIntegrations(steps)));

  server.registerTool("gameshop_route_capability",{title:"Route Game Art Capability",description:"Rank game-art providers.",inputSchema:z.object({capability:z.enum(["character","character-animation","spritesheet","pixel-art","ui-art","texture","tileset","background-removal","general-game-art"]),preference:z.enum(["quality","speed","cost","balanced"]).optional(),requireConfigured:z.boolean().optional(),requireImplemented:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(routeCapability));
  server.registerTool("gameshop_routing_matrix",{title:"Game Art Routing Matrix",description:"Inspect game-art routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>routingMatrix()));
  server.registerTool("gameshop_route_motion",{title:"Route UI and Motion Capability",description:"Choose a motion/UI engine.",inputSchema:z.object({capability:z.enum(["micro-interaction","react-animation","layout-animation","gesture","drag","scroll-triggered","scroll-linked","timeline","svg-animation","dom-animation","js-object-animation","game-hud","game-menu","component-effect"]),preference:z.enum(["quality","speed","bundle","react-native-fit","balanced"]).optional(),framework:z.enum(["react","vanilla","vue","phaser-overlay","any"]).optional()}),annotations:{readOnlyHint:true}},safe(routeMotion));
  server.registerTool("gameshop_motion_matrix",{title:"UI and Motion Routing Matrix",description:"Inspect motion routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>motionRoutingMatrix()));
  server.registerTool("gameshop_route_build",{title:"Route Universal Build Capability",description:"Route work across full-stack product domains.",inputSchema:z.object({domain:buildDomain,capability:z.string().min(1).max(100).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),framework:framework.optional(),requireInstallable:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(routeMultiDomain));
  server.registerTool("gameshop_build_matrix",{title:"Universal Build Matrix",description:"Inspect the universal product capability routing matrix.",inputSchema:z.object({domain:buildDomain.optional()}),annotations:{readOnlyHint:true}},safe(({domain}:any)=>multiDomainMatrix(domain)));
  server.registerTool("gameshop_plan_build",{title:"Plan Universal Multi-Engine Build",description:"Turn any supported digital-product brief into an ordered full-stack build plan.",inputSchema:z.object(buildInput),annotations:{readOnlyHint:true}},safe(createBuildPlan));
  server.registerTool("gameshop_prepare_execution",{title:"Prepare Game Shop Execution",description:"Compile a build plan into a safe execution contract.",inputSchema:z.object({...buildInput,target:targetInput,allowWrites:z.boolean().optional(),allowExternal:z.boolean().optional(),allowDeploy:z.boolean().optional()}),annotations:{readOnlyHint:true}},safe(prepareExecution));
  server.registerTool("gameshop_execute_github_plan",{title:"Execute GitHub Build Plan",description:"Dry-run or execute project-scoped file mutations on a controlled branch.",inputSchema:z.object({...buildInput,projectId:z.string().min(1).max(100),target:targetInput,allowWrites:z.boolean().optional(),allowExternal:z.boolean().optional(),allowDeploy:z.boolean().optional(),dryRun:z.boolean().optional(),executionId:z.string().min(8).max(100).optional(),operations:z.array(operationInput).min(1).max(25)}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(executeGitHubPlan));
  server.registerTool("gameshop_execution_status",{title:"Game Shop Execution Status",description:"Read one resumable execution handle.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},safe(({executionId}:any)=>({execution:getExecution(executionId),store:executionStoreInfo()})));
  server.registerTool("gameshop_list_executions",{title:"List Game Shop Executions",description:"List execution handles known to the current store.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>({executions:listExecutions(),store:executionStoreInfo()})));
  server.registerTool("gameshop_cancel_execution",{title:"Cancel Game Shop Execution",description:"Mark an execution cancelled so it cannot resume.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},safe(({executionId}:any)=>cancelExecution(executionId)));

  server.registerTool("gameshop_list_projects",{title:"List Game Shop Projects",description:"List registered product/project contexts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},safe(async()=>listProjects()));
  server.registerTool("gameshop_project_context",{title:"Get Project Context",description:"Get product kind, framework, repo, path and execution state.",inputSchema:z.object({projectId:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},safe(({projectId}:any)=>projectContext(projectId)));
  server.registerTool("gameshop_inspect_project",{title:"Inspect Project",description:"Inspect the registered project root on GitHub.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(githubInspectProject));
  server.registerTool("gameshop_plan_project",{title:"Plan Project Work",description:"Create a product-aware build plan using project context.",inputSchema:z.object({projectId:z.string().min(1).max(100),goal:z.string().min(3).max(2000),goals:z.array(buildGoal).max(10).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional()}),annotations:{readOnlyHint:true}},safe(createProjectPlan));
  server.registerTool("gameshop_github_read_file",{title:"Read Project File",description:"Read a file relative to the registered project root.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(githubReadProjectFile));
  server.registerTool("gameshop_create_project_branch",{title:"Create Safe Project Branch",description:"Create a gameshop/* branch for a registered project.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),fromRef:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(githubCreateProjectBranch));
  server.registerTool("gameshop_github_upsert_file",{title:"Controlled Project File Edit",description:"Create or update a file inside the registered project root on a gameshop/* branch.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),content:z.string().max(500000),message:z.string().min(3).max(200),branch:z.string().min(10).max(200),sha:z.string().regex(/^[0-9a-f]{40}$/).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(githubUpsertProjectFile));
  server.registerTool("gameshop_verify_project_branch",{title:"Verify Project Branch",description:"Compare a Game Shop branch to the project base and enforce project-root safety.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(githubVerifyProjectBranch));
  server.registerTool("gameshop_create_project_pr",{title:"Create Verified Project PR",description:"Open a pull request only after project verification passes.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),title:z.string().min(3).max(200),body:z.string().max(4000).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(githubCreateProjectPullRequest));

  server.registerTool("gameshop_generate_character",{title:"Generate Game Character",description:"Create a character using AutoSprite; paid generation remains locked by policy.",inputSchema:z.object({name:z.string().min(1).max(100),prompt:z.string().min(1).max(600),quality:z.enum(["turbo","pro"]).optional(),isHumanoid:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(autoSpriteCreateCharacter));
  server.registerTool("gameshop_generate_animation",{title:"Generate Character Animation",description:"Generate AutoSprite sprite-sheet animations; paid generation remains locked.",inputSchema:z.object({characterId:z.string().min(1),animations:z.array(z.object({kind:z.string().min(1),name:z.string().optional(),prompt:z.string().max(600).optional()})).min(1).max(10),videoTier:z.enum(["turbo","pro","ultra","max"]).optional(),frameCount:z.number().int().min(2).max(64).optional(),frameSize:z.number().int().min(32).max(512).optional(),removeBg:z.enum(["default","ultra"]).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(autoSpriteGenerateAnimations));
  server.registerTool("gameshop_generation_status",{title:"Check Generation Status",description:"Check an AutoSprite job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(({jobId}:any)=>autoSpriteGetJob(jobId)));
  server.registerTool("gameshop_get_spritesheet",{title:"Get Sprite Sheet",description:"Return existing AutoSprite spritesheet metadata.",inputSchema:z.object({spritesheetId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(({spritesheetId}:any)=>autoSpriteGetSpritesheet(spritesheetId)));
  server.registerTool("gameshop_spritecook_models",{title:"List SpriteCook Models",description:"List SpriteCook models.",inputSchema:z.object({}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(async()=>spriteCookListModels()));
  server.registerTool("gameshop_spritecook_generate",{title:"Generate Game Art with SpriteCook",description:"Start SpriteCook generation; paid generation remains locked.",inputSchema:z.object({prompt:z.string().min(1).max(2000),mode:z.enum(["assets","texture","ui"]).optional(),model:z.string().min(1).optional(),resolution:z.enum(["1K","2K","4K"]).optional(),quality:z.enum(["low","medium","high"]).optional(),colors:z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).max(64).optional(),referenceAssetId:z.string().optional(),editAssetId:z.string().optional(),projectId:z.string().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},safe(spriteCookGenerate));
  server.registerTool("gameshop_spritecook_status",{title:"Check SpriteCook Job",description:"Check a SpriteCook job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},safe(({jobId}:any)=>spriteCookGetJob(jobId)));
}
