import { assertPaidGenerationAllowed } from "./spend.js";
import { createArtifact, listArtifacts, updateArtifact, type ArtifactKind, type ArtifactPurpose } from "./artifacts.js";
import { orchestrateArtifact } from "./orchestrator.js";

type ArtifactContext={executionId?:string;projectId?:string;purpose?:ArtifactPurpose;kind?:ArtifactKind;name?:string;targetPath?:string};
function credentials(){const key=process.env.SCENARIO_API_KEY?.trim();const secret=process.env.SCENARIO_API_SECRET?.trim();if(!key||!secret)throw new Error("SCENARIO_API_KEY and SCENARIO_API_SECRET are required.");return Buffer.from(`${key}:${secret}`).toString("base64");}
function headers(){return{Authorization:`Basic ${credentials()}`,"content-type":"application/json",accept:"application/json"};}
async function json(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...headers(),...(init.headers||{})},signal:AbortSignal.timeout(30000)});const text=await r.text();let body:unknown=text;try{body=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(`Scenario request failed (${r.status}).`);return body;}
function record(value:unknown){return value&&typeof value==="object"?value as Record<string,unknown>:{};}
function jobId(data:unknown){const root=record(data);const job=record(root.job);return String(job.jobId??job.id??root.jobId??root.id??"")||undefined;}
function firstUrl(value:unknown):string|undefined{if(typeof value==="string"&&/^https:\/\//.test(value))return value;if(Array.isArray(value)){for(const v of value){const u=firstUrl(v);if(u)return u;}}if(value&&typeof value==="object"){for(const v of Object.values(value as Record<string,unknown>)){const u=firstUrl(v);if(u)return u;}}return undefined;}
export function scenarioV2Info(){return{provider:"scenario",base:"https://api.cloud.scenario.com/v1",auth:"Basic base64(API_KEY:API_SECRET)",configured:Boolean(process.env.SCENARIO_API_KEY&&process.env.SCENARIO_API_SECRET),supports:["dry-run-cost-preview","custom-model-generation","job-status","artifact-finalization","orchestration"]};}
export async function scenarioDryRun(input:{modelId:string;body:Record<string,unknown>}){if(!/^[a-zA-Z0-9_-]+$/.test(input.modelId))throw new Error("Invalid Scenario model id.");const url=new URL(`https://api.cloud.scenario.com/v1/generate/custom/${encodeURIComponent(input.modelId)}`);url.searchParams.set("dryRun","true");return json(url.toString(),{method:"POST",body:JSON.stringify(input.body)});}
export async function scenarioGenerateV2(input:{modelId:string;body:Record<string,unknown>;artifact?:ArtifactContext}){assertPaidGenerationAllowed("Scenario generation");if(!/^[a-zA-Z0-9_-]+$/.test(input.modelId))throw new Error("Invalid Scenario model id.");const data=await json(`https://api.cloud.scenario.com/v1/generate/custom/${encodeURIComponent(input.modelId)}`,{method:"POST",body:JSON.stringify(input.body)});const id=jobId(data);let artifact=null;if(input.artifact?.executionId){artifact=await createArtifact({executionId:input.artifact.executionId,projectId:input.artifact.projectId,kind:input.artifact.kind??"other",purpose:input.artifact.purpose??"general",status:"pending",name:input.artifact.name??`Scenario ${input.modelId} output`,provider:"scenario",providerJobId:id,metadata:{providerResponse:data,...(input.artifact.targetPath?{orchestration:{targetPath:input.artifact.targetPath,state:"waiting"}}:{})}});}return{result:data,artifact};}
export async function scenarioJobV2(id:string){const data=await json(`https://api.cloud.scenario.com/v1/jobs/${encodeURIComponent(id)}`,{method:"GET"});const root=record(data);const job=record(root.job);const status=String(job.status??root.status??"unknown").toLowerCase();const terminal=/success|succeeded|complete/.test(status)?"ready":/fail|cancel|error/.test(status)?"failed":null;const sourceUrl=firstUrl(job.output??job.metadata??data);const artifacts=(await listArtifacts()).filter(a=>a.provider==="scenario"&&a.providerJobId===id);const orchestration=[];for(const a of artifacts){const updated=await updateArtifact(a.artifactId,{status:terminal??a.status,sourceUrl:sourceUrl??a.sourceUrl,metadata:{providerResponse:data,providerStatus:status}});if(terminal==="ready"&&updated)orchestration.push(await orchestrateArtifact({artifactId:a.artifactId}));}return{result:data,status:terminal??"pending",artifactsUpdated:artifacts.length,orchestration};}
