import { inspectCapability, sandboxCapability, approveCapability, resolveTrustedCapabilities } from "./capability-trust.js";
import { logEvent } from "./governance-ledger.js";
export type TrustSignal={name:string;weight:number;value:number;detail?:string};
type Incident={incidentId:string;name:string;severity:"low"|"medium"|"high";message:string;at:string};
const incidents=new Map<string,Incident[]>();
function config(){const url=process.env.GAME_SHOP_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.GAME_SHOP_SUPABASE_SERVICE_ROLE_KEY;return url&&key?{url,key}:null;}
async function store(path:string,init:RequestInit={}){const c=config();if(!c)return null;const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"content-type":"application/json",Prefer:"return=representation",...(init.headers||{})},signal:AbortSignal.timeout(10000)});const text=await r.text();if(!r.ok)throw new Error(`Trust V2 store failed (${r.status}).`);return text?JSON.parse(text):null;}
async function incidentRows(name:string){const data=await store(`game_shop_capability_incidents?capability_name=eq.${encodeURIComponent(name)}&order=created_at.desc&limit=100`);if(Array.isArray(data))return data.map((r:any)=>({incidentId:String(r.incident_id),name:String(r.capability_name),severity:r.severity as Incident["severity"],message:String(r.message),at:String(r.created_at)}));return incidents.get(name)??[];}
export function trustPipelineV2Info(){return{version:"2.0",durableIncidents:Boolean(config()),signals:["official-registry-provenance","publisher-verification","repository-ownership","release-provenance","package-integrity","auth-model","tool-annotations","schema-risk","network-scope","filesystem-scope","subprocess-scope","destructive-capabilities","sandbox-behavior","latency","error-rate","pricing","post-promotion-incidents"],lifecycle:["discover","inspect","sandbox","score","human-approve","promote","observe","rescore","retain-or-quarantine"],promotionThreshold:75,quarantineThreshold:45,approvalRequired:true};}
export function scoreCapabilityV2(input:{officialRegistry?:boolean;publisherVerified?:boolean;repositoryVerified?:boolean;releaseProvenance?:boolean;packageIntegrity?:boolean;oauth?:boolean;toolCount?:number;riskyTools?:string[];filesystem?:boolean;subprocess?:boolean;payment?:boolean;latencyMs?:number;errorRate?:number;pricingKnown?:boolean;incidents?:number}){const signals:TrustSignal[]=[];const add=(name:string,weight:number,value:number,detail?:string)=>signals.push({name,weight,value,detail});add("official-registry-provenance",12,input.officialRegistry?1:0);add("publisher-verification",10,input.publisherVerified?1:0);add("repository-ownership",8,input.repositoryVerified?1:0);add("release-provenance",8,input.releaseProvenance?1:0);add("package-integrity",8,input.packageIntegrity?1:0);add("auth-model",6,input.oauth?1:.5);add("tool-introspection",8,Math.min(1,(input.toolCount??0)/10));const risk=(input.riskyTools?.length??0)+(input.filesystem?2:0)+(input.subprocess?3:0)+(input.payment?3:0);add("capability-risk",18,Math.max(0,1-risk/10),`${risk} weighted risk points`);add("latency",6,input.latencyMs==null?.5:input.latencyMs<1000?1:input.latencyMs<3000?.7:.3);add("reliability",8,input.errorRate==null?.5:Math.max(0,1-input.errorRate));add("pricing-transparency",4,input.pricingKnown?1:.5);const incidentCount=input.incidents??0;add("post-promotion-incidents",4,Math.max(0,1-incidentCount*.35));const weighted=signals.reduce((n,s)=>n+s.weight*s.value,0);const total=signals.reduce((n,s)=>n+s.weight,0);const score=Math.round(weighted/total*100);return{score,decision:score>=75?"eligible-for-approval":score<45?"quarantine":"needs-review",signals};}
export async function evaluateCapabilityV2(input:{name:string;description?:string;endpoint:string;source?:string;signals?:Parameters<typeof scoreCapabilityV2>[0]}){await inspectCapability(input);const sandbox:any=await sandboxCapability(input);const existingIncidents=await incidentRows(input.name);const baseSignals={officialRegistry:input.source==="official-mcp-registry",toolCount:sandbox?.tools?.length??sandbox?.capability?.tools?.length??0,incidents:existingIncidents.length,...(input.signals??{})};const score=scoreCapabilityV2(baseSignals);return{sandbox,score,incidents:existingIncidents.length,policy:trustPipelineV2Info()};}
export async function approveCapabilityV2(input:{name:string;approved:boolean;score:number}){if(input.approved&&input.score<75)throw new Error("Trust Pipeline V2 requires score >= 75 before approval.");const result=await approveCapability({name:input.name,approved:input.approved});await logEvent({type:input.approved?"trust.promoted":"trust.rejected",data:{name:input.name,score:input.score}}).catch(()=>{});return result;}
export async function reportCapabilityIncident(input:{name:string;severity:"low"|"medium"|"high";message:string}){const incident:Incident={incidentId:`inc_${crypto.randomUUID()}`,name:input.name,severity:input.severity,message:input.message.slice(0,500),at:new Date().toISOString()};const rows=incidents.get(input.name)??[];rows.push(incident);incidents.set(input.name,rows);await store("game_shop_capability_incidents",{method:"POST",body:JSON.stringify({incident_id:incident.incidentId,capability_name:incident.name,severity:incident.severity,message:incident.message,created_at:incident.at})});await logEvent({type:"trust.incident",data:{name:input.name,severity:input.severity,message:incident.message}}).catch(()=>{});const all=await incidentRows(input.name);return{name:input.name,incidentCount:all.length,recommendation:input.severity==="high"?"quarantine-and-review":"rescore",incident};}
export async function trustedCapabilityPortfolio(){const trusted=await resolveTrustedCapabilities();const items=[];for(const item of trusted){const rows=await incidentRows(item.name);const high=rows.filter(r=>r.severity==="high").length;items.push({id:item.id,name:item.name,score:item.score,incidentCount:rows.length,highIncidents:high,state:high?"quarantine-recommended":item.state});}return{count:trusted.length,items};}
