import { inspectCapability, sandboxCapability, approveCapability, resolveTrustedCapabilities } from "./capability-trust.js";
export type TrustSignal={name:string;weight:number,value:number;detail?:string};
const incidents=new Map<string,Array<{severity:"low"|"medium"|"high";message:string;at:string}>>();
export function trustPipelineV2Info(){return{version:"2.0",signals:["official-registry-provenance","publisher-verification","repository-ownership","release-provenance","package-integrity","auth-model","tool-annotations","schema-risk","network-scope","filesystem-scope","subprocess-scope","destructive-capabilities","sandbox-behavior","latency","error-rate","pricing","post-promotion-incidents"],lifecycle:["discover","inspect","sandbox","score","human-approve","promote","observe","rescore","retain-or-quarantine"],promotionThreshold:75,quarantineThreshold:45,approvalRequired:true};}
export function scoreCapabilityV2(input:{officialRegistry?:boolean;publisherVerified?:boolean;repositoryVerified?:boolean;releaseProvenance?:boolean;packageIntegrity?:boolean;oauth?:boolean;toolCount?:number;riskyTools?:string[];filesystem?:boolean;subprocess?:boolean;payment?:boolean;latencyMs?:number;errorRate?:number;pricingKnown?:boolean;incidents?:number}){const signals:TrustSignal[]=[];const add=(name:string,weight:number,value:number,detail?:string)=>signals.push({name,weight,value,detail});add("official-registry-provenance",12,input.officialRegistry?1:0);add("publisher-verification",10,input.publisherVerified?1:0);add("repository-ownership",8,input.repositoryVerified?1:0);add("release-provenance",8,input.releaseProvenance?1:0);add("package-integrity",8,input.packageIntegrity?1:0);add("auth-model",6,input.oauth?1:.5);add("tool-introspection",8,Math.min(1,(input.toolCount??0)/10));const risk=(input.riskyTools?.length??0)+(input.filesystem?2:0)+(input.subprocess?3:0)+(input.payment?3:0);add("capability-risk",18,Math.max(0,1-risk/10),`${risk} weighted risk points`);add("latency",6,input.latencyMs==null?.5:input.latencyMs<1000?1:input.latencyMs<3000?.7:.3);add("reliability",8,input.errorRate==null?.5:Math.max(0,1-input.errorRate));add("pricing-transparency",4,input.pricingKnown?1:.5);const incidentCount=input.incidents??0;add("post-promotion-incidents",4,Math.max(0,1-incidentCount*.35));const weighted=signals.reduce((n,s)=>n+s.weight*s.value,0);const total=signals.reduce((n,s)=>n+s.weight,0);const score=Math.round(weighted/total*100);return{score,decision:score>=75?"eligible-for-approval":score<45?"quarantine":"needs-review",signals};}
export async function evaluateCapabilityV2(input:{name:string;description?:string;endpoint:string;source?:string;signals?:Parameters<typeof scoreCapabilityV2>[0]}){await inspectCapability(input);const sandbox=await sandboxCapability(input);const baseSignals={officialRegistry:input.source==="official-mcp-registry",toolCount:(sandbox as any).tools?.length??(sandbox as any).capability?.tools?.length??0,incidents:incidents.get(input.name)?.length??0,...(input.signals??{})};const score=scoreCapabilityV2(baseSignals);return{sandbox,score,policy:trustPipelineV2Info()};}
export async function approveCapabilityV2(input:{name:string;approved:boolean;score:number}){if(input.approved&&input.score<75)throw new Error("Trust Pipeline V2 requires score >= 75 before approval.");return approveCapability({name:input.name,approved:input.approved});}
export async function reportCapabilityIncident(input:{name:string;severity:"low"|"medium"|"high";message:string}){const rows=incidents.get(input.name)??[];rows.push({severity:input.severity,message:input.message.slice(0,500),at:new Date().toISOString()});incidents.set(input.name,rows);return{name:input.name,incidentCount:rows.length,recommendation:input.severity==="high"?"quarantine-and-review":"rescore"};}
export async function trustedCapabilityPortfolio(){const trusted=await resolveTrustedCapabilities();return{count:trusted.length,items:trusted.map(item=>({id:item.id,name:item.name,score:item.score,incidentCount:incidents.get(item.name)?.length??0,state:item.state}))};}
