import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { publicErrorMessage } from "../src/errors.js";
import { cancelExecutionDurable, executionStoreInfo, resolveExecution, resolveExecutions } from "../src/execution-store.js";
import { externalEngineStatus, falSubmit, ludoDocs, meshyTask, meshyTextTo3D, replicatePredict, replicatePrediction } from "../src/external-engines.js";
import { createRepairPlan, verifyProject } from "../src/verification.js";
import { authorizeRequest, enforceRateLimit } from "../src/security.js";
function asResult(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}
function fail(error:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]}}
const handler=createMcpHandler(server=>{
 server.registerTool("gameshop_durable_execution_status",{title:"Durable Execution Status",description:"Resolve execution state from warm cache or durable storage.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},async({executionId})=>asResult({execution:await resolveExecution(executionId),store:executionStoreInfo()}));
 server.registerTool("gameshop_durable_executions",{title:"Durable Executions",description:"List persisted Game Shop executions.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({executions:await resolveExecutions(),store:executionStoreInfo()}));
 server.registerTool("gameshop_cancel_durable_execution",{title:"Cancel Durable Execution",description:"Persist cancellation of an execution handle.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},async({executionId})=>asResult(await cancelExecutionDurable(executionId)));
 server.registerTool("gameshop_verify_project",{title:"Verify Project",description:"Run project-scoped smoke checks against a GitHub ref.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),checks:z.array(z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()})).max(25).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await verifyProject(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_plan_repair",{title:"Plan Repair",description:"Turn failed verification checks into a minimal read-only repair plan.",inputSchema:z.object({projectId:z.string().min(1).max(100),verification:z.object({status:z.string(),checks:z.array(z.record(z.string(),z.unknown()))})}),annotations:{readOnlyHint:true}},async input=>asResult(createRepairPlan(input)));
 server.registerTool("gameshop_external_engines",{title:"External Engine Status",description:"Show callable external generation engines without exposing secrets.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(externalEngineStatus()));
 server.registerTool("gameshop_meshy_text_to_3d",{title:"Meshy Text to 3D",description:"Create a Meshy preview/refine task. Paid generation lock applies.",inputSchema:z.object({prompt:z.string().max(600).default(""),mode:z.enum(["preview","refine"]).optional(),previewTaskId:z.string().optional(),enablePbr:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await meshyTextTo3D(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_meshy_task",{title:"Meshy Task Status",description:"Read a Meshy Text-to-3D task.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({id})=>{try{return asResult(await meshyTask(id))}catch(e){return fail(e)}});
 server.registerTool("gameshop_fal_submit",{title:"fal Queue Submit",description:"Submit inference to fal's durable queue. Paid generation lock applies.",inputSchema:z.object({model:z.string().min(3).max(200),input:z.record(z.string(),z.unknown())}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await falSubmit(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replicate_predict",{title:"Replicate Prediction",description:"Create an asynchronous Replicate prediction. Paid generation lock applies.",inputSchema:z.object({version:z.string().min(3).max(300),input:z.record(z.string(),z.unknown())}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await replicatePredict(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replicate_prediction",{title:"Replicate Prediction Status",description:"Read a Replicate prediction.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({id})=>{try{return asResult(await replicatePrediction(id))}catch(e){return fail(e)}});
 server.registerTool("gameshop_ludo_docs",{title:"Ludo Generator Docs",description:"Read Ludo's free agent-facing generator documentation before composing generation calls.",inputSchema:z.object({doc:z.string().max(100).optional(),sections:z.string().max(500).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await ludoDocs(input))}catch(e){return fail(e)}});
});
async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status,headers:{"content-type":"application/json"}});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429,headers:{"content-type":"application/json","retry-after":String(rate.retryAfter)}});return handler(request)}
export{route as GET,route as POST,route as DELETE};
