import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { ARTIFACT_STORE_SQL, artifactStoreInfo, createArtifact, getArtifact, listArtifacts, updateArtifact } from "../src/artifacts.js";
import { placeArtifactInProject } from "../src/artifact-placement.js";
import { controlCenterAppInfo, controlCenterSnapshot } from "../src/control-center.js";
import { publicErrorMessage } from "../src/errors.js";
import { cancelExecutionDurable, executionStoreInfo, resolveExecution, resolveExecutions } from "../src/execution-store.js";
import { elevenSpeech, elevenSpeechJob, externalEngineStatus, falJob, falSubmit, ludoDocs, ludoGenerate, ludoJob, meshyTask, meshyTextTo3D, replicatePredict, replicatePrediction, scenarioGenerate } from "../src/external-engines.js";
import { createRepairPlan, verifyProject } from "../src/verification.js";
import { authorizeRequest, enforceRateLimit } from "../src/security.js";
import { gameShopTaskCancel, gameShopTaskGet, taskBridgeInfo } from "../src/task-bridge.js";
function asResult(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}
function fail(error:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]}}
const artifactKind=z.enum(["image","sprite","spritesheet","3d","video","audio","rive","document","code","archive","data","other"]);
const artifactPurpose=z.enum(["game","website","web-app","mobile-app","interactive-experience","digital-product","media","general"]);
const artifactContext=z.object({executionId:z.string().min(8).max(100),projectId:z.string().max(100).optional(),purpose:artifactPurpose.optional(),kind:artifactKind.optional(),name:z.string().max(300).optional()}).optional();
const handler=createMcpHandler(server=>{
 server.registerTool("gameshop_durable_execution_status",{title:"Durable Execution Status",description:"Resolve execution state from warm cache or durable storage.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},async({executionId})=>asResult({execution:await resolveExecution(executionId),store:executionStoreInfo()}));
 server.registerTool("gameshop_durable_executions",{title:"Durable Executions",description:"List persisted Game Shop executions.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({executions:await resolveExecutions(),store:executionStoreInfo()}));
 server.registerTool("gameshop_cancel_durable_execution",{title:"Cancel Durable Execution",description:"Persist cancellation of an execution handle.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},async({executionId})=>asResult(await cancelExecutionDurable(executionId)));
 server.registerTool("gameshop_task_bridge",{title:"MCP Tasks Bridge",description:"Describe Game Shop alignment with the MCP Tasks extension.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(taskBridgeInfo()));
 server.registerTool("gameshop_task_get",{title:"Task Status",description:"Represent a durable Game Shop execution using MCP Tasks state semantics.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},async({executionId})=>asResult(await gameShopTaskGet(executionId)));
 server.registerTool("gameshop_task_cancel",{title:"Cancel Task",description:"Cancel a Game Shop execution through the Tasks compatibility bridge.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,idempotentHint:true}},async({executionId})=>asResult(await gameShopTaskCancel(executionId)));
 server.registerTool("gameshop_control_center",{title:"Game Shop Control Center",description:"Return the data model for the MCP Apps control center: executions, tasks, artifacts, engines and integrations.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({app:controlCenterAppInfo(),snapshot:await controlCenterSnapshot()}));
 server.registerTool("gameshop_artifact_store",{title:"Artifact Store Status",description:"Describe Game Shop's universal artifact store.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},async({includeSchema})=>asResult({store:artifactStoreInfo(),schema:includeSchema?ARTIFACT_STORE_SQL:undefined}));
 server.registerTool("gameshop_create_artifact",{title:"Register Artifact",description:"Attach a first-class artifact to any Game Shop execution.",inputSchema:z.object({executionId:z.string().min(8).max(100),projectId:z.string().max(100).optional(),kind:artifactKind,purpose:artifactPurpose.default("general"),status:z.enum(["pending","ready","failed","archived"]).default("pending"),name:z.string().min(1).max(300),provider:z.string().max(100).optional(),providerJobId:z.string().max(300).optional(),mimeType:z.string().max(150).optional(),sourceUrl:z.string().url().max(2000).optional(),storageUrl:z.string().url().max(2000).optional(),metadata:z.record(z.string(),z.unknown()).default({})}),annotations:{readOnlyHint:false}},async input=>{try{return asResult(await createArtifact(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_artifact",{title:"Get Artifact",description:"Read one Game Shop artifact.",inputSchema:z.object({artifactId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},async({artifactId})=>asResult(await getArtifact(artifactId)));
 server.registerTool("gameshop_artifacts",{title:"List Artifacts",description:"List artifacts across games, websites, apps, media and other products.",inputSchema:z.object({executionId:z.string().max(100).optional(),projectId:z.string().max(100).optional(),kind:artifactKind.optional()}),annotations:{readOnlyHint:true}},async input=>asResult({artifacts:await listArtifacts(input),store:artifactStoreInfo()}));
 server.registerTool("gameshop_update_artifact",{title:"Update Artifact",description:"Update artifact lifecycle or storage metadata.",inputSchema:z.object({artifactId:z.string().min(8).max(100),status:z.enum(["pending","ready","failed","archived"]).optional(),providerJobId:z.string().max(300).optional(),mimeType:z.string().max(150).optional(),sourceUrl:z.string().url().max(2000).optional(),storageUrl:z.string().url().max(2000).optional(),metadata:z.record(z.string(),z.unknown()).optional()}),annotations:{readOnlyHint:false,idempotentHint:true}},async({artifactId,...patch})=>{try{return asResult(await updateArtifact(artifactId,patch))}catch(e){return fail(e)}});
 server.registerTool("gameshop_place_artifact",{title:"Place Artifact in Project",description:"Download a ready artifact and commit it into a controlled Game Shop project branch.",inputSchema:z.object({artifactId:z.string().min(8),projectId:z.string().min(1),path:z.string().min(1).max(500),branch:z.string().regex(/^gameshop\//),message:z.string().max(300).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await placeArtifactInProject(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_verify_project",{title:"Verify Project",description:"Run project-scoped smoke checks against a GitHub ref.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),checks:z.array(z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()})).max(25).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await verifyProject(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_plan_repair",{title:"Plan Repair",description:"Turn failed verification into a minimal repair plan.",inputSchema:z.object({projectId:z.string().min(1).max(100),verification:z.object({status:z.string(),checks:z.array(z.record(z.string(),z.unknown()))})}),annotations:{readOnlyHint:true}},async input=>asResult(createRepairPlan(input)));
 server.registerTool("gameshop_external_engines",{title:"External Engine Status",description:"Show callable external engines without exposing secrets.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(externalEngineStatus()));
 server.registerTool("gameshop_meshy_text_to_3d",{title:"Meshy Text to 3D",description:"Create a Meshy 3D task with artifact capture.",inputSchema:z.object({prompt:z.string().max(600).default(""),mode:z.enum(["preview","refine"]).optional(),previewTaskId:z.string().optional(),enablePbr:z.boolean().optional(),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await meshyTextTo3D(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_meshy_task",{title:"Meshy Task Status",description:"Read Meshy status and finalize matching artifacts.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({id})=>{try{return asResult(await meshyTask(id))}catch(e){return fail(e)}});
 server.registerTool("gameshop_fal_submit",{title:"fal Queue Submit",description:"Submit fal inference with artifact capture.",inputSchema:z.object({model:z.string().min(3).max(200),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await falSubmit(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_fal_job",{title:"fal Job",description:"Poll a fal queue job and finalize its artifact when complete.",inputSchema:z.object({jobId:z.string().min(1),statusUrl:z.string().url(),responseUrl:z.string().url().optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await falJob(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replicate_predict",{title:"Replicate Prediction",description:"Create an async Replicate prediction with artifact capture.",inputSchema:z.object({version:z.string().min(3).max(300),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await replicatePredict(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replicate_prediction",{title:"Replicate Prediction Status",description:"Read Replicate status and finalize matching artifacts.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({id})=>{try{return asResult(await replicatePrediction(id))}catch(e){return fail(e)}});
 server.registerTool("gameshop_ludo_generate",{title:"Ludo Generate",description:"Call an allowlisted Ludo MCP generator for image, sprite, 3D, animation, audio or video and capture its artifact.",inputSchema:z.object({tool:z.string().min(3).max(100),input:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await ludoGenerate(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_ludo_job",{title:"Ludo Job",description:"Poll Ludo getApiJob and finalize matching artifacts.",inputSchema:z.object({id:z.string().min(1),wait:z.number().int().min(0).max(60).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await ludoJob(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_ludo_docs",{title:"Ludo Generator Docs",description:"Read Ludo generator documentation.",inputSchema:z.object({doc:z.string().max(100).optional(),sections:z.string().max(500).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return asResult(await ludoDocs(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_elevenlabs_speech",{title:"ElevenLabs Speech",description:"Start an asynchronous ElevenLabs speech Flow and capture it as an audio artifact.",inputSchema:z.object({text:z.string().min(1).max(5000),voice:z.string().min(1).max(200),modelId:z.string().max(100).optional(),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await elevenSpeech(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_elevenlabs_speech_job",{title:"ElevenLabs Speech Job",description:"Poll an ElevenLabs speech Flow and finalize its audio artifact.",inputSchema:z.object({id:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({id})=>{try{return asResult(await elevenSpeechJob(id))}catch(e){return fail(e)}});
 server.registerTool("gameshop_scenario_generate",{title:"Scenario Universal Generate",description:"Generate image, video, 3D or audio through Scenario's universal generation endpoint with artifact capture.",inputSchema:z.object({modelId:z.string().min(3).max(200),body:z.record(z.string(),z.unknown()),artifact:artifactContext}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return asResult(await scenarioGenerate(input))}catch(e){return fail(e)}});
});
async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status,headers:{"content-type":"application/json"}});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429,headers:{"content-type":"application/json","retry-after":String(rate.retryAfter)}});return handler(request)}
export{route as GET,route as POST,route as DELETE};
