import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { controlCenterV2Snapshot } from "../src/control-center-v2.js";
import { artifactObjectStoreInfo } from "../src/artifact-storage.js";
import { routeMcp } from "../src/mcp-route.js";
const URI="ui://game-shop/control-center.html";const MIME="text/html;profile=mcp-app";
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game Shop</title><style>body{margin:0;background:#08090b;color:#f8fafc;font:14px system-ui}.shell{padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:18px 0}.card,.row{border:1px solid #27272a;border-radius:16px;padding:16px;background:#111318}.n{font-size:28px;font-weight:800}.muted{color:#9ca3af}.pill{padding:6px 10px;border:1px solid #3f3f46;border-radius:999px}.list{display:grid;gap:8px}.ok{color:#86efac}.warn{color:#fde68a}.bad{color:#fca5a5}h2{margin-top:28px}</style></head><body><main class="shell"><div class="top"><div><h1>THE GAME SHOP</h1><div class="muted">Universal digital production supervisory cockpit</div></div><span class="pill">MCP App · v2</span></div><section id="app"><div class="card">Loading Game Shop…</div></section></main><script type="module">const root=document.querySelector('#app');const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));function render(d){const s=d?.snapshot||d||{};const b=s.base||{};const sum=b.summary||{};const sup=s.supervision||{};const systems=s.systems||{};const ev=sup.events||[];const pv=sup.previews||[];const projects=sup.projects||[];const trust=sup.trust||{};root.innerHTML='<div class="grid">'+[['Projects',projects.length],['Executions',sum.executions||0],['Artifacts',sum.artifacts||0],['Integrations',sum.integrations||0],['Trusted MCPs',trust.count||0],['Events',ev.length],['Previews',pv.length],['Posture',sum.platformPosture||'unknown']].map(([a,b])=>'<div class="card"><div class="muted">'+esc(a)+'</div><div class="n">'+esc(b)+'</div></div>').join('')+'</div><h2>Systems</h2><div class="list">'+Object.entries(systems).map(([k,v])=>'<div class="row"><b>'+esc(k)+'</b><div class="muted">'+esc(JSON.stringify(v))+'</div></div>').join('')+'</div><h2>Recent events</h2><div class="list">'+ev.slice(0,20).map(x=>'<div class="row"><b>'+esc(x.type||x.action||'event')+'</b><div class="muted">'+esc(x.created_at||x.createdAt||'')+'</div></div>').join('')+'</div>'}window.addEventListener('message',e=>{const p=e.data?.params;if(p?.structuredContent)render(p.structuredContent)});parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',params:{}},'*');</script></body></html>`;
function result(data:unknown){return{content:[{type:"text" as const,text:"Game Shop Control Center v2 ready."}],structuredContent:data as Record<string,unknown>};}
const handler=createMcpHandler(server=>{server.registerResource("Game Shop Control Center",URI,{title:"Game Shop Control Center",description:"Executions, artifacts, costs, previews, evidence, health, trust and continuity.",mimeType:MIME},async()=>({contents:[{uri:URI,mimeType:MIME,text:html,_meta:{ui:{}}}]}));server.registerTool("gameshop_open_control_center",{title:"Open Game Shop",description:"Open the Game Shop v2 supervisory cockpit.",inputSchema:z.object({}),annotations:{readOnlyHint:true},_meta:{ui:{resourceUri:URI,visibility:["model"]},"ui/resourceUri":URI}},async()=>result({snapshot:await controlCenterV2Snapshot(),storage:artifactObjectStoreInfo()}));});
async function route(request:Request){return routeMcp(request,handler)}export{route as GET,route as POST,route as DELETE};
