import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { controlCenterSnapshot } from "../src/control-center.js";
import { artifactObjectStoreInfo } from "../src/artifact-storage.js";
import { authorizeRequest, enforceRateLimit } from "../src/security.js";

const URI="ui://game-shop/control-center.html";
const MIME="text/html;profile=mcp-app";
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game Shop</title><style>body{margin:0;background:#09090b;color:#fafafa;font:14px system-ui}.shell{padding:24px}.top{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:18px}.card{border:1px solid #27272a;border-radius:16px;padding:16px;background:#111113}.n{font-size:28px;font-weight:800}.muted{color:#a1a1aa}.pill{padding:6px 10px;border:1px solid #3f3f46;border-radius:999px}.list{margin-top:16px;display:grid;gap:8px}.row{padding:12px;border:1px solid #27272a;border-radius:12px}</style></head><body><main class="shell"><div class="top"><div><h1>THE GAME SHOP</h1><div class="muted">Universal digital production control center</div></div><span class="pill">MCP App</span></div><section id="app"><div class="card">Loading Game Shop…</div></section></main><script type="module">const root=document.querySelector('#app');function render(d){const s=d?.snapshot||d||{};const ex=s.executions||[];const ar=s.artifacts||[];const engines=s.engines||{};const ints=s.integrations||{};root.innerHTML='<div class="grid"><div class="card"><div class="muted">Executions</div><div class="n">'+ex.length+'</div></div><div class="card"><div class="muted">Artifacts</div><div class="n">'+ar.length+'</div></div><div class="card"><div class="muted">Engines</div><div class="n">'+Object.keys(engines).length+'</div></div><div class="card"><div class="muted">Integrations</div><div class="n">'+(ints.total||0)+'</div></div></div><div class="list">'+ex.slice(0,12).map(x=>'<div class="row"><b>'+String(x.executionId||'execution')+'</b><div class="muted">'+String(x.status||'unknown')+'</div></div>').join('')+'</div>'}window.addEventListener('message',e=>{const p=e.data?.params;if(p?.structuredContent)render(p.structuredContent)});parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',params:{}},'*');</script></body></html>`;
function result(data:unknown){return{content:[{type:"text" as const,text:"Game Shop Control Center ready."}],structuredContent:data as Record<string,unknown>};}
const handler=createMcpHandler(server=>{
 server.registerResource("Game Shop Control Center",URI,{title:"Game Shop Control Center",description:"Live executions, artifacts, engines and integrations.",mimeType:MIME},async()=>({contents:[{uri:URI,mimeType:MIME,text:html,_meta:{ui:{}}}]}));
 server.registerTool("gameshop_open_control_center",{title:"Open Game Shop",description:"Open the interactive Game Shop production control center.",inputSchema:z.object({}),annotations:{readOnlyHint:true},_meta:{ui:{resourceUri:URI,visibility:["model"]},"ui/resourceUri":URI}},async()=>result({snapshot:await controlCenterSnapshot(),storage:artifactObjectStoreInfo()}));
});
async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status,headers:{"content-type":"application/json"}});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429,headers:{"content-type":"application/json","retry-after":String(rate.retryAfter)}});return handler(request)}
export{route as GET,route as POST,route as DELETE};
