import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { QA_MEMORY_SQL,approveQaRecipe,createQaRecipe,listQaRecipes,qaMemoryInfo } from "../src/qa-memory.js";
import { qaReplayInfo,replayProjectRegressions,replayQaRecipe } from "../src/qa-replay.js";
import { evaluateRelease,releaseGovernorInfo } from "../src/release-governor.js";
import { authorizeRequest,enforceRateLimit } from "../src/security.js";
import { publicErrorMessage } from "../src/errors.js";
function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}
function fail(e:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(e)}]}}
const check=z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()});
const handler=createMcpHandler(server=>{
 server.registerTool("gameshop_qa_memory",{title:"QA Memory",description:"Describe durable learned regression memory.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},async({includeSchema})=>result({memory:qaMemoryInfo(),replay:qaReplayInfo(),schema:includeSchema?QA_MEMORY_SQL:undefined}));
 server.registerTool("gameshop_create_qa_recipe",{title:"Create QA Recipe",description:"Create a reusable regression recipe from approved checks and interaction intents. New recipes are not approved by default.",inputSchema:z.object({projectId:z.string().min(1).max(100),name:z.string().min(1).max(200),description:z.string().max(1000).optional(),checks:z.array(check).max(25).optional(),interactions:z.array(z.string().max(300)).max(8).optional(),createdFromExecutionId:z.string().max(100).optional(),approved:z.boolean().optional()}),annotations:{readOnlyHint:false}},async input=>{try{return result(await createQaRecipe(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_qa_recipes",{title:"QA Recipes",description:"List learned regression recipes for a project.",inputSchema:z.object({projectId:z.string().max(100).optional(),approvedOnly:z.boolean().optional()}),annotations:{readOnlyHint:true}},async input=>{try{return result({recipes:await listQaRecipes(input),memory:qaMemoryInfo()})}catch(e){return fail(e)}});
 server.registerTool("gameshop_approve_qa_recipe",{title:"Approve QA Recipe",description:"Approve or reject a learned regression recipe before automatic replay.",inputSchema:z.object({recipeId:z.string().min(8).max(100),approved:z.boolean()}),annotations:{readOnlyHint:false,idempotentHint:true}},async input=>{try{return result(await approveQaRecipe(input.recipeId,input.approved))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replay_qa_recipe",{title:"Replay QA Recipe",description:"Replay one approved regression recipe through the QA swarm and record a terminal pass/fail.",inputSchema:z.object({recipeId:z.string().min(8).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),autoPreview:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return result(await replayQaRecipe(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_replay_project_regressions",{title:"Replay Project Regressions",description:"Replay approved regression memory for a project and return a composite release gate.",inputSchema:z.object({projectId:z.string().min(1).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),limit:z.number().int().min(1).max(20).optional(),autoPreview:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return result(await replayProjectRegressions(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_release_governor",{title:"Release Governor",description:"Describe the learned-regression and orchestration release gate.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>result(releaseGovernorInfo()));
 server.registerTool("gameshop_evaluate_release",{title:"Evaluate Release",description:"Evaluate project release readiness using orchestration blockers and approved regression memory. This tool does not promote production deployments.",inputSchema:z.object({projectId:z.string().min(1).max(100),url:z.string().url().optional(),ref:z.string().max(200).optional(),runRegressions:z.boolean().optional(),queuePlaywrightCi:z.boolean().optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return result(await evaluateRelease(input))}catch(e){return fail(e)}});
});
async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429});return handler(request)}
export{route as GET,route as POST,route as DELETE};
