import { createAuthorizationCode, createDynamicClient, exchangeAuthorizationCode, normalizeResource, normalizeScope, oauthBase, oauthMetadata, ownerSecret, ownerSecretMatches, protectedResourceMetadata, refreshAccessToken, validateOAuthClient } from "../src/oauth.js";
import { oauthReadiness } from "../src/oauth-readiness.js";
import { recordOAuthConsent } from "../src/oauth-store.js";

function json(data:unknown,status=200,cache="no-store"){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":cache,"pragma":"no-cache"}})}
function html(body:string,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})}
function esc(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));}
function parse(url:URL){return{clientId:url.searchParams.get("client_id")||"",redirectUri:url.searchParams.get("redirect_uri")||"",responseType:url.searchParams.get("response_type")||"",scope:normalizeScope(url.searchParams.get("scope")||undefined),state:url.searchParams.get("state")||"",codeChallenge:url.searchParams.get("code_challenge")||"",method:url.searchParams.get("code_challenge_method")||"",resource:url.searchParams.get("resource")||""};}
function validate(input:ReturnType<typeof parse>,base:string){if(!validateOAuthClient(input.clientId,input.redirectUri,base))return"Unknown OAuth client or redirect URI.";if(input.responseType!=="code")return"Only authorization_code is supported.";if(input.method!=="S256"||!input.codeChallenge)return"PKCE S256 is required.";try{normalizeResource(input.resource||undefined,base);}catch(error){return error instanceof Error?error.message:"Invalid OAuth resource.";}if(!ownerSecret())return"OAuth owner approval secret is not configured.";return null;}

async function authorizeGet(request:Request){const base=oauthBase(request);const input=parse(new URL(request.url));const error=validate(input,base);if(error)return html(`<h1>Game Shop OAuth</h1><p>${esc(error)}</p>`,400);const resource=normalizeResource(input.resource||undefined,base);return html(`<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>Authorize Game Shop</title><style>body{font-family:system-ui;background:#09090b;color:#fafafa;display:grid;place-items:center;min-height:100vh;margin:0}.card{width:min(560px,90vw);background:#18181b;padding:28px;border-radius:18px;border:1px solid #27272a}input{width:100%;box-sizing:border-box;padding:12px;margin:8px 0 16px;border-radius:10px;border:1px solid #3f3f46;background:#09090b;color:#fff}button{padding:12px 18px;border:0;border-radius:10px;font-weight:700}.scope{color:#a1a1aa;font-family:ui-monospace,monospace;word-break:break-word}.muted{color:#a1a1aa}</style></head><body><div class="card"><h1>Authorize Game Shop</h1><p>ChatGPT or another approved AI client is requesting access to Game Shop.</p><p class="scope">Scopes: ${esc(input.scope)}</p><p class="muted">Resource: ${esc(resource)}</p><form method="post"><input type="hidden" name="client_id" value="${esc(input.clientId)}"><input type="hidden" name="redirect_uri" value="${esc(input.redirectUri)}"><input type="hidden" name="scope" value="${esc(input.scope)}"><input type="hidden" name="state" value="${esc(input.state)}"><input type="hidden" name="code_challenge" value="${esc(input.codeChallenge)}"><input type="hidden" name="code_challenge_method" value="S256"><input type="hidden" name="resource" value="${esc(resource)}"><label>Owner approval secret</label><input type="password" name="owner_secret" autocomplete="current-password" required><button type="submit">Approve & Connect</button></form></div></body></html>`);}
async function authorizePost(request:Request){const form=await request.formData();const base=oauthBase(request);const input={clientId:String(form.get("client_id")||""),redirectUri:String(form.get("redirect_uri")||""),scope:normalizeScope(String(form.get("scope")||"")),state:String(form.get("state")||""),codeChallenge:String(form.get("code_challenge")||""),method:String(form.get("code_challenge_method")||""),resource:String(form.get("resource")||""),responseType:"code"};const error=validate(input,base);if(error)return html(`<h1>Game Shop OAuth</h1><p>${esc(error)}</p>`,400);const resource=normalizeResource(input.resource||undefined,base);const approved=ownerSecretMatches(String(form.get("owner_secret")||""));await recordOAuthConsent({clientId:input.clientId,subject:"game-shop-owner",scope:input.scope,approved});if(!approved)return html("<h1>Authorization denied</h1><p>Owner secret did not match.</p>",403);const code=createAuthorizationCode({issuer:base,clientId:input.clientId,redirectUri:input.redirectUri,scope:input.scope,codeChallenge:input.codeChallenge,resource});const redirect=new URL(input.redirectUri);redirect.searchParams.set("code",code);if(input.state)redirect.searchParams.set("state",input.state);redirect.searchParams.set("iss",base);return Response.redirect(redirect.toString(),302);}
async function registerPost(request:Request){try{const body=await request.json() as {redirect_uris?:unknown};const redirectUris=Array.isArray(body.redirect_uris)?body.redirect_uris.filter((v):v is string=>typeof v==="string"):[];return json(createDynamicClient({issuer:oauthBase(request),redirectUris}),201);}catch(error){return json({error:"invalid_client_metadata",error_description:error instanceof Error?error.message:"Client registration failed."},400);}}
async function tokenPost(request:Request){try{const form=await request.formData();const grant=String(form.get("grant_type")||"");const clientId=String(form.get("client_id")||"");const resource=String(form.get("resource")||"");if(grant==="refresh_token"){const refreshToken=String(form.get("refresh_token")||"");if(!clientId||!refreshToken)return json({error:"invalid_request"},400);return json(refreshAccessToken({refreshToken,clientId,issuer:oauthBase(request),resource:resource||undefined,scope:String(form.get("scope")||"")||undefined}));}if(grant!=="authorization_code")return json({error:"unsupported_grant_type"},400);const code=String(form.get("code")||"");const redirectUri=String(form.get("redirect_uri")||"");const verifier=String(form.get("code_verifier")||"");if(!code||!clientId||!redirectUri||!verifier)return json({error:"invalid_request"},400);return json(await exchangeAuthorizationCode({code,clientId,redirectUri,codeVerifier:verifier,issuer:oauthBase(request),resource:resource||undefined}));}catch(error){return json({error:"invalid_grant",error_description:error instanceof Error?error.message:"Token exchange failed."},400);}}
function routeOf(request:Request){return new URL(request.url).searchParams.get("route")||"";}
export async function GET(request:Request){const route=routeOf(request);if(route==="authorize")return authorizeGet(request);if(route==="status")return json(oauthReadiness(request),200);if(route==="metadata"){const base=oauthBase(request);const kind=new URL(request.url).searchParams.get("kind");return json(kind==="protected"?protectedResourceMetadata(base):oauthMetadata(base),200,"public, max-age=300");}if(route==="token"||route==="register")return json({error:"method_not_allowed"},405);return json({error:"not_found"},404);}
export async function POST(request:Request){const route=routeOf(request);if(route==="authorize")return authorizePost(request);if(route==="token")return tokenPost(request);if(route==="register")return registerPost(request);return json({error:"method_not_allowed"},405);}
