import { createMcpHandler } from "mcp-handler";import { z } from "zod";
import { qaWorkerInfo,repairWorkerContract,runQa } from "../src/qa-worker.js";
import { discoverCapabilities,discoveryInfo } from "../src/capability-discovery.js";
import { applyApprovedPatch,patchWorkerInfo } from "../src/code-patch-worker.js";
import { createPreviewDeployment,previewDeploymentInfo } from "../src/preview-deployment.js";
import { approveCapability,CAPABILITY_TRUST_SQL,capabilityTrustInfo,discoverForTrust,inspectCapability,sandboxCapability,trustedCapabilities } from "../src/capability-trust.js";
import { authorizeRequest,enforceRateLimit } from "../src/security.js";import { publicErrorMessage } from "../src/errors.js";
function result(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}function fail(e:unknown){return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(e)}]}}
const checks=z.array(z.object({path:z.string().min(1).max(500),required:z.boolean().optional(),contains:z.string().max(500).optional()})).max(25).optional();
const handler=createMcpHandler(server=>{
 server.registerTool("gameshop_qa_worker",{title:"QA Worker",description:"Inspect live browser QA and repair policy.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>result(qaWorkerInfo()));
 server.registerTool("gameshop_run_qa",{title:"Run Product QA",description:"Run structural checks and execute Browserbase/Playwright browser evidence against a preview URL, optionally discovering a Vercel preview first.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().max(200).optional(),url:z.string().url().optional(),provider:z.enum(["browserbase","playwright-mcp"]).optional(),checks,interactions:z.array(z.string().max(300)).max(8).optional(),autoPreview:z.boolean().optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return result(await runQa(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_repair_worker",{title:"Repair Worker",description:"Create an approval-gated iterative repair contract from QA evidence.",inputSchema:z.object({projectId:z.string().min(1).max(100),approved:z.boolean(),qa:z.record(z.string(),z.unknown())}),annotations:{readOnlyHint:false}},async input=>result(repairWorkerContract(input)));
 server.registerTool("gameshop_patch_worker",{title:"Code Patch Worker",description:"Inspect constrained patch-worker limits.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>result(patchWorkerInfo()));
 server.registerTool("gameshop_apply_patch",{title:"Apply Approved Patch",description:"Apply explicit replacement-file patches only to a gameshop/* branch, then verify scope safety.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().regex(/^gameshop\//),baseRef:z.string().max(200).optional(),approved:z.boolean(),title:z.string().max(300).optional(),operations:z.array(z.object({path:z.string().min(1).max(500),content:z.string().max(120000),expectedSha:z.string().optional(),reason:z.string().max(300).optional()})).min(1).max(8)}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return result(await applyApprovedPatch(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_preview_info",{title:"Preview Deployment",description:"Describe Vercel preview deployment/discovery configuration.",inputSchema:z.object({projectId:z.string().max(100).optional()}),annotations:{readOnlyHint:true}},async({projectId})=>result(previewDeploymentInfo(projectId)));
 server.registerTool("gameshop_create_preview",{title:"Create Preview",description:"Trigger or discover a Vercel preview for a controlled gameshop/* branch.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().regex(/^gameshop\//),commitSha:z.string().optional(),waitMs:z.number().int().min(0).max(120000).optional()}),annotations:{readOnlyHint:false,openWorldHint:true}},async input=>{try{return result(await createPreviewDeployment(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_discovery_info",{title:"Self Expansion",description:"Describe continuous MCP capability discovery.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>result(discoveryInfo()));
 server.registerTool("gameshop_discover_capabilities",{title:"Discover Capabilities",description:"Search the official MCP Registry for capability gaps.",inputSchema:z.object({query:z.string().min(2).max(200),limit:z.number().int().min(1).max(50).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return result(await discoverCapabilities(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_trust_pipeline",{title:"Capability Trust Pipeline",description:"Describe discover → inspect → sandbox-test → score → approve/promote policy.",inputSchema:z.object({includeSchema:z.boolean().optional()}),annotations:{readOnlyHint:true}},async({includeSchema})=>result({trust:capabilityTrustInfo(),schema:includeSchema?CAPABILITY_TRUST_SQL:undefined,promoted:trustedCapabilities()}));
 server.registerTool("gameshop_discover_for_trust",{title:"Discover for Trust",description:"Search the official MCP Registry and prepare candidates for trust evaluation.",inputSchema:z.object({query:z.string().min(2).max(200),limit:z.number().int().min(1).max(50).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return result(await discoverForTrust(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_inspect_capability",{title:"Inspect MCP Capability",description:"Validate an HTTPS MCP endpoint before sandboxing.",inputSchema:z.object({name:z.string().min(1).max(200),description:z.string().max(1000).optional(),endpoint:z.string().url(),source:z.string().max(100).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return result(await inspectCapability(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_sandbox_capability",{title:"Sandbox MCP Capability",description:"Initialize a candidate MCP and list its tools only; no candidate tools are executed. Produces a trust score.",inputSchema:z.object({name:z.string().min(1).max(200),description:z.string().max(1000).optional(),endpoint:z.string().url(),source:z.string().max(100).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async input=>{try{return result(await sandboxCapability(input))}catch(e){return fail(e)}});
 server.registerTool("gameshop_approve_capability",{title:"Approve MCP Capability",description:"Explicitly approve/reject a sandbox-passed MCP for Game Shop's dynamic trusted arsenal.",inputSchema:z.object({name:z.string().min(1).max(200),approved:z.boolean()}),annotations:{readOnlyHint:false}},async input=>{try{return result(await approveCapability(input))}catch(e){return fail(e)}});
});
async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429});return handler(request)}export{route as GET,route as POST,route as DELETE};
