import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { capabilityCatalog } from "../src/catalog.js";
import { publicErrorMessage } from "../src/errors.js";
import { prepareExecution } from "../src/execution.js";
import { cancelExecution, executionStoreInfo, getExecution, listExecutions } from "../src/execution-store.js";
import { executeGitHubPlan } from "../src/executor.js";
import { githubCreateProjectBranch, githubCreateProjectPullRequest, githubInspectProject, githubReadProjectFile, githubUpsertProjectFile, githubVerifyProjectBranch } from "../src/github-execution.js";
import { integrationRegistry, integrationStatus } from "../src/integrations.js";
import { integrationReadiness, invokeIntegration, orchestrateIntegrations } from "../src/integration-runtime.js";
import { routeMotion, motionRoutingMatrix } from "../src/motion-router.js";
import { routeMultiDomain, multiDomainMatrix } from "../src/multidomain-router.js";
import { createBuildPlan } from "../src/planner.js";
import { createProjectPlan } from "../src/project-planner.js";
import { listProjects, projectContext } from "../src/projects.js";
import { autoSpriteCreateCharacter, autoSpriteGenerateAnimations, autoSpriteGetJob, autoSpriteGetSpritesheet, providerStatus, spriteCookGenerate, spriteCookGetJob, spriteCookListModels } from "../src/providers.js";
import { routeCapability, routingMatrix } from "../src/router.js";
import { authorizeMcpToolRequest, authorizeRequest, enforceRateLimit, oauthChallenge } from "../src/security.js";
import { spendPolicy } from "../src/spend.js";
import { gameShopSystemAudit } from "../src/system-audit.js";

function asResult(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}
function errorResult(error:unknown){console.error("Game Shop tool failed",error instanceof Error?{name:error.name,message:error.message}:{error:String(error)});return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]}}
const productKind=z.enum(["website","web-app","browser-game","mobile-app","desktop-app","api-service","agent","automation","interactive-experience","digital-product","media-project","commerce","other"]);
const buildGoal=z.enum(["premium","cinematic","playful","minimal","immersive","conversion","performance","reliable","secure","scalable"]);
const framework=z.enum(["react","vanilla","vue","phaser","three","node","python","expo","any"]);
const buildDomain=z.enum(["ui","motion","3d","shader","video","audio","backend","data","storage","auth","testing","deployment","commerce","observability","design-reference","agent-platform"]);
const buildInput={brief:z.string().min(3).max(4000),product:productKind,goals:z.array(buildGoal).max(10).optional(),framework:framework.optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),includeDomains:z.array(buildDomain).max(16).optional()};
const targetInput=z.object({repository:z.string().min(3).max(200).optional(),branch:z.string().min(1).max(200).optional(),project:z.string().min(1).max(100).optional(),environment:z.enum(["development","preview","production"]).optional()}).optional();
const operationInput=z.object({path:z.string().min(1).max(500),content:z.string().max(500000),message:z.string().min(3).max(200),sha:z.string().regex(/^[0-9a-f]{40}$/).optional()});
const integrationInvokeInput={id:z.string().min(1).max(100),mode:z.enum(["mcp-list-tools","mcp-call","api"]).optional(),tool:z.string().min(1).max(200).optional(),arguments:z.record(z.string(),z.unknown()).optional(),method:z.enum(["GET","POST","PUT","PATCH","DELETE"]).optional(),path:z.string().max(500).optional(),body:z.unknown().optional(),timeoutMs:z.number().int().min(1000).max(60000).optional()};

const handler=createMcpHandler((server)=>{
server.registerTool("gameshop_system_audit",{title:"Game Shop System Audit",description:"Inspect Game Shop runtime posture, stores, projects, integrations, OAuth, GitHub, QA, preview and protocol readiness without exposing secrets.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(gameShopSystemAudit()));
server.registerTool("gameshop_list_providers",{title:"List Game Shop Providers",description:"List configured providers without exposing API keys.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({spend:spendPolicy(),providers:providerStatus()}));
server.registerTool("gameshop_spend_policy",{title:"Game Shop Spend Policy",description:"Show whether paid generation is allowed.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(spendPolicy()));
server.registerTool("gameshop_capability_catalog",{title:"Game Shop Capability Catalog",description:"List build capabilities available to Game Shop agents.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(capabilityCatalog()));
server.registerTool("gameshop_integrations",{title:"Game Shop Integration Registry",description:"List verified integration contracts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(integrationRegistry()));
server.registerTool("gameshop_integration_status",{title:"Game Shop Integration Status",description:"Inspect one verified integration.",inputSchema:z.object({id:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},async({id})=>asResult(integrationStatus(id)));
server.registerTool("gameshop_integration_readiness",{title:"Integration Readiness",description:"Show which registered MCP/API integrations are actually callable in this runtime, including missing environment configuration and execution locks.",inputSchema:z.object({id:z.string().min(1).max(100).optional()}),annotations:{readOnlyHint:true}},async({id})=>asResult(integrationReadiness(id)));
server.registerTool("gameshop_invoke_integration",{title:"Invoke Game Shop Integration",description:"Actively call a registered remote MCP tool or REST API endpoint. Live external calls require GAME_SHOP_ALLOW_EXTERNAL_INTEGRATIONS=true; potentially billable operations also require paid-generation opt-in.",inputSchema:z.object(integrationInvokeInput),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await invokeIntegration(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_orchestrate_integrations",{title:"Orchestrate Game Shop Integrations",description:"Execute up to ten registered MCP/API calls in order, stopping on the first required-step failure. External-call and spend locks still apply to every step.",inputSchema:z.object({steps:z.array(z.object({...integrationInvokeInput,optional:z.boolean().optional()})).min(1).max(10)}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async({steps})=>{try{return asResult(await orchestrateIntegrations(steps))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_route_capability",{title:"Route Game Art Capability",description:"Rank game-art providers.",inputSchema:z.object({capability:z.enum(["character","character-animation","spritesheet","pixel-art","ui-art","texture","tileset","background-removal","general-game-art"]),preference:z.enum(["quality","speed","cost","balanced"]).optional(),requireConfigured:z.boolean().optional(),requireImplemented:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeCapability(input)));
server.registerTool("gameshop_routing_matrix",{title:"Game Art Routing Matrix",description:"Inspect game-art routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(routingMatrix()));
server.registerTool("gameshop_route_motion",{title:"Route UI and Motion Capability",description:"Choose a motion/UI engine.",inputSchema:z.object({capability:z.enum(["micro-interaction","react-animation","layout-animation","gesture","drag","scroll-triggered","scroll-linked","timeline","svg-animation","dom-animation","js-object-animation","game-hud","game-menu","component-effect"]),preference:z.enum(["quality","speed","bundle","react-native-fit","balanced"]).optional(),framework:z.enum(["react","vanilla","vue","phaser-overlay","any"]).optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeMotion(input)));
server.registerTool("gameshop_motion_matrix",{title:"UI and Motion Routing Matrix",description:"Inspect motion routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(motionRoutingMatrix()));
server.registerTool("gameshop_route_build",{title:"Route Universal Build Capability",description:"Route work across UI, motion, media, backend, data, storage, auth, testing, deployment, commerce, observability and agent infrastructure.",inputSchema:z.object({domain:buildDomain,capability:z.string().min(1).max(100).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),framework:framework.optional(),requireInstallable:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeMultiDomain(input)));
server.registerTool("gameshop_build_matrix",{title:"Universal Build Matrix",description:"Inspect Game Shop's universal product capability routing matrix.",inputSchema:z.object({domain:buildDomain.optional()}),annotations:{readOnlyHint:true}},async({domain})=>asResult(multiDomainMatrix(domain)));
server.registerTool("gameshop_plan_build",{title:"Plan Universal Multi-Engine Build",description:"Turn any supported digital-product brief into an ordered full-stack multi-engine build plan.",inputSchema:z.object(buildInput),annotations:{readOnlyHint:true}},async(input)=>asResult(createBuildPlan(input)));
server.registerTool("gameshop_prepare_execution",{title:"Prepare Game Shop Execution",description:"Compile a build plan into a safe execution contract.",inputSchema:z.object({...buildInput,target:targetInput,allowWrites:z.boolean().optional(),allowExternal:z.boolean().optional(),allowDeploy:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(prepareExecution(input)));
server.registerTool("gameshop_execute_github_plan",{title:"Execute GitHub Build Plan",description:"Dry-run or execute an ordered batch of project-scoped file mutations. Real writes require a gameshop/ branch, explicit approval and write opt-in.",inputSchema:z.object({...buildInput,projectId:z.string().min(1).max(100),target:targetInput,allowWrites:z.boolean().optional(),allowExternal:z.boolean().optional(),allowDeploy:z.boolean().optional(),dryRun:z.boolean().optional(),executionId:z.string().min(8).max(100).optional(),operations:z.array(operationInput).min(1).max(25)}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await executeGitHubPlan(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_execution_status",{title:"Game Shop Execution Status",description:"Read one resumable execution handle and current progress.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:true}},async({executionId})=>asResult({execution:getExecution(executionId),store:executionStoreInfo()}));
server.registerTool("gameshop_list_executions",{title:"List Game Shop Executions",description:"List execution handles known to the current execution store.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({executions:listExecutions(),store:executionStoreInfo()}));
server.registerTool("gameshop_cancel_execution",{title:"Cancel Game Shop Execution",description:"Mark an execution handle cancelled so it cannot resume.",inputSchema:z.object({executionId:z.string().min(8).max(100)}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},async({executionId})=>asResult(cancelExecution(executionId)));

server.registerTool("gameshop_list_projects",{title:"List Game Shop Projects",description:"List registered product/project contexts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(listProjects()));
server.registerTool("gameshop_project_context",{title:"Get Project Context",description:"Get product kind, framework, repo, path and execution state for a registered project.",inputSchema:z.object({projectId:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},async({projectId})=>{try{return asResult(projectContext(projectId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_inspect_project",{title:"Inspect Project",description:"Inspect the registered project root on GitHub without leaving its scoped directory.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubInspectProject(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_plan_project",{title:"Plan Project Work",description:"Create a product-aware build plan using registered project context and execution constraints.",inputSchema:z.object({projectId:z.string().min(1).max(100),goal:z.string().min(3).max(2000),goals:z.array(buildGoal).max(10).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional()}),annotations:{readOnlyHint:true}},async(input)=>{try{return asResult(createProjectPlan(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_github_read_file",{title:"Read Project File",description:"Read a file relative to the registered project root.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubReadProjectFile(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_create_project_branch",{title:"Create Safe Project Branch",description:"Create a gameshop/ branch for a registered project. Requires GitHub write opt-in.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),fromRef:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubCreateProjectBranch(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_github_upsert_file",{title:"Controlled Project File Edit",description:"Create or update a file relative to the registered project root on an existing gameshop/ branch.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),content:z.string().max(500000),message:z.string().min(3).max(200),branch:z.string().min(10).max(200),sha:z.string().regex(/^[0-9a-f]{40}$/).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubUpsertProjectFile(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_verify_project_branch",{title:"Verify Project Branch",description:"Compare a Game Shop branch to the project base and fail verification if any changed file escapes the registered project root.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200)}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubVerifyProjectBranch(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_create_project_pr",{title:"Create Verified Project PR",description:"Open a pull request only after branch verification passes. Requires GitHub write opt-in.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),title:z.string().min(3).max(200),body:z.string().max(4000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubCreateProjectPullRequest(input))}catch(e){return errorResult(e)}});

server.registerTool("gameshop_generate_character",{title:"Generate Game Character",description:"Create a character using AutoSprite; paid generation remains locked by policy.",inputSchema:z.object({name:z.string().min(1).max(100),prompt:z.string().min(1).max(600),quality:z.enum(["turbo","pro"]).optional(),isHumanoid:z.boolean().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await autoSpriteCreateCharacter(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_generate_animation",{title:"Generate Character Animation",description:"Generate AutoSprite sprite-sheet animations; paid generation remains locked by policy.",inputSchema:z.object({characterId:z.string().min(1),animations:z.array(z.object({kind:z.string().min(1),name:z.string().optional(),prompt:z.string().max(600).optional()})).min(1).max(10),videoTier:z.enum(["turbo","pro","ultra","max"]).optional(),frameCount:z.number().int().min(2).max(64).optional(),frameSize:z.number().int().min(32).max(512).optional(),removeBg:z.enum(["default","ultra"]).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await autoSpriteGenerateAnimations(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_generation_status",{title:"Check Generation Status",description:"Check an AutoSprite job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({jobId})=>{try{return asResult(await autoSpriteGetJob(jobId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_get_spritesheet",{title:"Get Sprite Sheet",description:"Return existing AutoSprite spritesheet metadata.",inputSchema:z.object({spritesheetId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({spritesheetId})=>{try{return asResult(await autoSpriteGetSpritesheet(spritesheetId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_models",{title:"List SpriteCook Models",description:"List SpriteCook models.",inputSchema:z.object({}),annotations:{readOnlyHint:true,openWorldHint:true}},async()=>{try{return asResult(await spriteCookListModels())}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_generate",{title:"Generate Game Art with SpriteCook",description:"Start SpriteCook generation; paid generation remains locked by policy.",inputSchema:z.object({prompt:z.string().min(1).max(2000),mode:z.enum(["assets","texture","ui"]).optional(),model:z.string().min(1).optional(),resolution:z.enum(["1K","2K","4K"]).optional(),quality:z.enum(["low","medium","high"]).optional(),colors:z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).max(64).optional(),referenceAssetId:z.string().optional(),editAssetId:z.string().optional(),projectId:z.string().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await spriteCookGenerate(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_status",{title:"Check SpriteCook Job",description:"Check a SpriteCook job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({jobId})=>{try{return asResult(await spriteCookGetJob(jobId))}catch(e){return errorResult(e)}});
});

async function route(request:Request){
  let auth=authorizeRequest(request);
  if(auth.ok)auth=await authorizeMcpToolRequest(request,auth);
  if(!auth.ok){
    const headers:Record<string,string>={"content-type":"application/json"};
    if(auth.status===401)headers["www-authenticate"]=oauthChallenge(request);
    if(auth.status===403&&auth.requiredScopes?.length)headers["www-authenticate"]=`${oauthChallenge(request)}, scope="${auth.requiredScopes.join(" ")}"`;
    return new Response(JSON.stringify({error:auth.error,requiredScopes:auth.requiredScopes??undefined}),{status:auth.status,headers});
  }
  const rate=enforceRateLimit(request);
  if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429,headers:{"content-type":"application/json","retry-after":String(rate.retryAfter)}});
  return handler(request);
}
export{route as GET,route as POST,route as DELETE};
