import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { capabilityCatalog } from "../src/catalog.js";
import { publicErrorMessage } from "../src/errors.js";
import { prepareExecution } from "../src/execution.js";
import { githubCreateProjectBranch, githubCreateProjectPullRequest, githubInspectProject, githubReadProjectFile, githubUpsertProjectFile, githubVerifyProjectBranch } from "../src/github-execution.js";
import { integrationRegistry, integrationStatus } from "../src/integrations.js";
import { routeMotion, motionRoutingMatrix } from "../src/motion-router.js";
import { routeMultiDomain, multiDomainMatrix } from "../src/multidomain-router.js";
import { createBuildPlan } from "../src/planner.js";
import { createProjectPlan } from "../src/project-planner.js";
import { listProjects, projectContext } from "../src/projects.js";
import { autoSpriteCreateCharacter, autoSpriteGenerateAnimations, autoSpriteGetJob, autoSpriteGetSpritesheet, providerStatus, spriteCookGenerate, spriteCookGetJob, spriteCookListModels } from "../src/providers.js";
import { routeCapability, routingMatrix } from "../src/router.js";
import { authorizeRequest, enforceRateLimit } from "../src/security.js";
import { spendPolicy } from "../src/spend.js";

function asResult(data:unknown){return{content:[{type:"text" as const,text:JSON.stringify(data,null,2)}],structuredContent:typeof data==="object"&&data!==null?data as Record<string,unknown>:{value:data}}}
function errorResult(error:unknown){console.error("Game Shop tool failed",error instanceof Error?{name:error.name,message:error.message}:{error:String(error)});return{isError:true,content:[{type:"text" as const,text:publicErrorMessage(error)}]}}
const buildInput={brief:z.string().min(3).max(4000),product:z.enum(["website","web-app","browser-game","mobile-app","interactive-experience","digital-product"]),goals:z.array(z.enum(["premium","cinematic","playful","minimal","immersive","conversion","performance"])).max(7).optional(),framework:z.enum(["react","vanilla","vue","phaser","three","any"]).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),includeDomains:z.array(z.enum(["ui","motion","3d","shader","video","design-reference","agent-platform"])).max(7).optional()};

const handler=createMcpHandler((server)=>{
server.registerTool("gameshop_list_providers",{title:"List Game Shop Providers",description:"List configured providers without exposing API keys.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult({spend:spendPolicy(),providers:providerStatus()}));
server.registerTool("gameshop_spend_policy",{title:"Game Shop Spend Policy",description:"Show whether paid generation is allowed.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(spendPolicy()));
server.registerTool("gameshop_capability_catalog",{title:"Game Shop Capability Catalog",description:"List build capabilities available to Game Shop agents.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(capabilityCatalog()));
server.registerTool("gameshop_integrations",{title:"Game Shop Integration Registry",description:"List verified integration contracts.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(integrationRegistry()));
server.registerTool("gameshop_integration_status",{title:"Game Shop Integration Status",description:"Inspect one verified integration.",inputSchema:z.object({id:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},async({id})=>asResult(integrationStatus(id)));
server.registerTool("gameshop_route_capability",{title:"Route Game Art Capability",description:"Rank game-art providers.",inputSchema:z.object({capability:z.enum(["character","character-animation","spritesheet","pixel-art","ui-art","texture","tileset","background-removal","general-game-art"]),preference:z.enum(["quality","speed","cost","balanced"]).optional(),requireConfigured:z.boolean().optional(),requireImplemented:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeCapability(input)));
server.registerTool("gameshop_routing_matrix",{title:"Game Art Routing Matrix",description:"Inspect game-art routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(routingMatrix()));
server.registerTool("gameshop_route_motion",{title:"Route UI and Motion Capability",description:"Choose a motion/UI engine.",inputSchema:z.object({capability:z.enum(["micro-interaction","react-animation","layout-animation","gesture","drag","scroll-triggered","scroll-linked","timeline","svg-animation","dom-animation","js-object-animation","game-hud","game-menu","component-effect"]),preference:z.enum(["quality","speed","bundle","react-native-fit","balanced"]).optional(),framework:z.enum(["react","vanilla","vue","phaser-overlay","any"]).optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeMotion(input)));
server.registerTool("gameshop_motion_matrix",{title:"UI and Motion Routing Matrix",description:"Inspect motion routing.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(motionRoutingMatrix()));
server.registerTool("gameshop_route_build",{title:"Route Multi-Domain Build Capability",description:"Route multi-domain work.",inputSchema:z.object({domain:z.enum(["ui","motion","3d","shader","video","design-reference","agent-platform"]),capability:z.string().min(1).max(100).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional(),framework:z.enum(["react","vanilla","vue","phaser","three","any"]).optional(),requireInstallable:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(routeMultiDomain(input)));
server.registerTool("gameshop_build_matrix",{title:"Multi-Domain Build Matrix",description:"Inspect multi-domain routing.",inputSchema:z.object({domain:z.enum(["ui","motion","3d","shader","video","design-reference","agent-platform"]).optional()}),annotations:{readOnlyHint:true}},async({domain})=>asResult(multiDomainMatrix(domain)));
server.registerTool("gameshop_plan_build",{title:"Plan Multi-Engine Build",description:"Turn a product brief into an ordered multi-engine build plan.",inputSchema:z.object(buildInput),annotations:{readOnlyHint:true}},async(input)=>asResult(createBuildPlan(input)));
server.registerTool("gameshop_prepare_execution",{title:"Prepare Game Shop Execution",description:"Compile a build plan into a safe prepare-only execution contract.",inputSchema:z.object({...buildInput,target:z.object({repository:z.string().min(3).max(200).optional(),branch:z.string().min(1).max(200).optional(),project:z.string().min(1).max(100).optional(),environment:z.enum(["development","preview","production"]).optional()}).optional(),allowWrites:z.boolean().optional(),allowExternal:z.boolean().optional(),allowDeploy:z.boolean().optional()}),annotations:{readOnlyHint:true}},async(input)=>asResult(prepareExecution(input)));

server.registerTool("gameshop_list_projects",{title:"List Game Shop Projects",description:"List registered project contexts, including core Game Shop titles.",inputSchema:z.object({}),annotations:{readOnlyHint:true}},async()=>asResult(listProjects()));
server.registerTool("gameshop_project_context",{title:"Get Game Project Context",description:"Get framework, repo, path and execution state for a registered project.",inputSchema:z.object({projectId:z.string().min(1).max(100)}),annotations:{readOnlyHint:true}},async({projectId})=>{try{return asResult(projectContext(projectId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_inspect_project",{title:"Inspect Game Project",description:"Inspect the registered game root on GitHub without leaving its scoped directory.",inputSchema:z.object({projectId:z.string().min(1).max(100),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubInspectProject(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_plan_project",{title:"Plan Game Project Work",description:"Create a project-aware build plan using registered game context and execution constraints.",inputSchema:z.object({projectId:z.string().min(1).max(100),goal:z.string().min(3).max(2000),goals:z.array(z.enum(["premium","cinematic","playful","minimal","immersive","conversion","performance"])).max(7).optional(),preference:z.enum(["quality","speed","cost","bundle","open-source","balanced"]).optional()}),annotations:{readOnlyHint:true}},async(input)=>{try{return asResult(createProjectPlan(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_github_read_file",{title:"Read Project File",description:"Read a file relative to the registered game root.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),ref:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubReadProjectFile(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_create_project_branch",{title:"Create Safe Game Branch",description:"Create a gameshop/ branch for a registered project. Requires GitHub write opt-in.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),fromRef:z.string().min(1).max(200).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubCreateProjectBranch(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_github_upsert_file",{title:"Controlled Project File Edit",description:"Create or update a file relative to the registered game root on an existing gameshop/ branch.",inputSchema:z.object({projectId:z.string().min(1).max(100),path:z.string().min(1).max(500),content:z.string().max(500000),message:z.string().min(3).max(200),branch:z.string().min(10).max(200),sha:z.string().regex(/^[0-9a-f]{40}$/).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubUpsertProjectFile(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_verify_project_branch",{title:"Verify Game Branch",description:"Compare a Game Shop branch to the project base and fail verification if any changed file escapes the registered game root.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200)}),annotations:{readOnlyHint:true,openWorldHint:true}},async(input)=>{try{return asResult(await githubVerifyProjectBranch(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_create_project_pr",{title:"Create Verified Game PR",description:"Open a pull request only after branch verification passes. Requires GitHub write opt-in.",inputSchema:z.object({projectId:z.string().min(1).max(100),branch:z.string().min(10).max(200),title:z.string().min(3).max(200),body:z.string().max(4000).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await githubCreateProjectPullRequest(input))}catch(e){return errorResult(e)}});

server.registerTool("gameshop_generate_character",{title:"Generate Game Character",description:"Create a character using AutoSprite; paid generation remains locked by policy.",inputSchema:z.object({name:z.string().min(1).max(100),prompt:z.string().min(1).max(600),quality:z.enum(["turbo","pro"]).optional(),isHumanoid:z.boolean().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await autoSpriteCreateCharacter(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_generate_animation",{title:"Generate Character Animation",description:"Generate AutoSprite sprite-sheet animations; paid generation remains locked by policy.",inputSchema:z.object({characterId:z.string().min(1),animations:z.array(z.object({kind:z.string().min(1),name:z.string().optional(),prompt:z.string().max(600).optional()})).min(1).max(10),videoTier:z.enum(["turbo","pro","ultra","max"]).optional(),frameCount:z.number().int().min(2).max(64).optional(),frameSize:z.number().int().min(32).max(512).optional(),removeBg:z.enum(["default","ultra"]).optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await autoSpriteGenerateAnimations(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_generation_status",{title:"Check Generation Status",description:"Check an AutoSprite job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({jobId})=>{try{return asResult(await autoSpriteGetJob(jobId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_get_spritesheet",{title:"Get Sprite Sheet",description:"Return existing AutoSprite spritesheet metadata.",inputSchema:z.object({spritesheetId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({spritesheetId})=>{try{return asResult(await autoSpriteGetSpritesheet(spritesheetId))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_models",{title:"List SpriteCook Models",description:"List SpriteCook models.",inputSchema:z.object({}),annotations:{readOnlyHint:true,openWorldHint:true}},async()=>{try{return asResult(await spriteCookListModels())}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_generate",{title:"Generate Game Art with SpriteCook",description:"Start SpriteCook generation; paid generation remains locked by policy.",inputSchema:z.object({prompt:z.string().min(1).max(2000),mode:z.enum(["assets","texture","ui"]).optional(),model:z.string().min(1).optional(),resolution:z.enum(["1K","2K","4K"]).optional(),quality:z.enum(["low","medium","high"]).optional(),colors:z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).max(64).optional(),referenceAssetId:z.string().optional(),editAssetId:z.string().optional(),projectId:z.string().optional()}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:true}},async(input)=>{try{return asResult(await spriteCookGenerate(input))}catch(e){return errorResult(e)}});
server.registerTool("gameshop_spritecook_status",{title:"Check SpriteCook Job",description:"Check a SpriteCook job.",inputSchema:z.object({jobId:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({jobId})=>{try{return asResult(await spriteCookGetJob(jobId))}catch(e){return errorResult(e)}});
});

async function route(request:Request){const auth=authorizeRequest(request);if(!auth.ok)return new Response(JSON.stringify({error:auth.error}),{status:auth.status,headers:{"content-type":"application/json"}});const rate=enforceRateLimit(request);if(!rate.ok)return new Response(JSON.stringify({error:"Rate limit exceeded"}),{status:429,headers:{"content-type":"application/json","retry-after":String(rate.retryAfter)}});return handler(request)}
export{route as GET,route as POST,route as DELETE};
