import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { capabilityCatalog } from "../src/catalog.js";
import { routeCapability, routingMatrix } from "../src/router.js";
import { routeMotion, motionRoutingMatrix } from "../src/motion-router.js";
import { autoSpriteCreateCharacter, autoSpriteGenerateAnimations, autoSpriteGetJob, autoSpriteGetSpritesheet, providerStatus, spriteCookGenerate, spriteCookGetJob, spriteCookListModels } from "../src/providers.js";
import { spendPolicy } from "../src/spend.js";

function asResult(data: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }], structuredContent: typeof data === "object" && data !== null ? data as Record<string, unknown> : { value: data } }; }
function errorResult(error: unknown) { return { isError: true, content: [{ type: "text" as const, text: error instanceof Error ? error.message : String(error) }] }; }

const handler = createMcpHandler((server) => {
  server.registerTool("gameshop_list_providers", { title: "List Game Shop Providers", description: "List configured Game Shop providers without exposing API keys.", inputSchema: z.object({}), annotations: { readOnlyHint: true } }, async () => asResult({ spend: spendPolicy(), providers: providerStatus() }));
  server.registerTool("gameshop_spend_policy", { title: "Game Shop Spend Policy", description: "Show whether paid generation is allowed.", inputSchema: z.object({}), annotations: { readOnlyHint: true } }, async () => asResult(spendPolicy()));
  server.registerTool("gameshop_capability_catalog", { title: "Game Shop Capability Catalog", description: "List build capabilities available to Game Shop agents.", inputSchema: z.object({}), annotations: { readOnlyHint: true } }, async () => asResult(capabilityCatalog()));

  server.registerTool("gameshop_route_capability", { title: "Route Game Art Capability", description: "Rank game-art providers for a requested capability.", inputSchema: z.object({ capability: z.enum(["character","character-animation","spritesheet","pixel-art","ui-art","texture","tileset","background-removal","general-game-art"]), preference: z.enum(["quality","speed","cost","balanced"]).optional(), requireConfigured: z.boolean().optional(), requireImplemented: z.boolean().optional() }), annotations: { readOnlyHint: true } }, async (input) => asResult(routeCapability(input)));
  server.registerTool("gameshop_routing_matrix", { title: "Game Art Routing Matrix", description: "Inspect game-art provider routing coverage and weights.", inputSchema: z.object({}), annotations: { readOnlyHint: true } }, async () => asResult(routingMatrix()));

  server.registerTool("gameshop_route_motion", { title: "Route UI and Motion Capability", description: "Choose the best motion/UI engine—Anime.js, Motion, GSAP, React Bits or CSS—for the requested interaction.", inputSchema: z.object({ capability: z.enum(["micro-interaction","react-animation","layout-animation","gesture","drag","scroll-triggered","scroll-linked","timeline","svg-animation","dom-animation","js-object-animation","game-hud","game-menu","component-effect"]), preference: z.enum(["quality","speed","bundle","react-native-fit","balanced"]).optional(), framework: z.enum(["react","vanilla","vue","phaser-overlay","any"]).optional() }), annotations: { readOnlyHint: true } }, async (input) => asResult(routeMotion(input)));
  server.registerTool("gameshop_motion_matrix", { title: "UI and Motion Routing Matrix", description: "Inspect the motion engine capability matrix and routing weights.", inputSchema: z.object({}), annotations: { readOnlyHint: true } }, async () => asResult(motionRoutingMatrix()));

  server.registerTool("gameshop_generate_character", { title: "Generate Game Character", description: "Create a character using AutoSprite. Paid generation remains blocked unless explicitly enabled.", inputSchema: z.object({ name: z.string().min(1).max(100), prompt: z.string().min(1).max(600), quality: z.enum(["turbo","pro"]).optional(), isHumanoid: z.boolean().optional() }), annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async (input) => { try { return asResult(await autoSpriteCreateCharacter(input)); } catch (e) { return errorResult(e); } });
  server.registerTool("gameshop_generate_animation", { title: "Generate Character Animation", description: "Generate AutoSprite sprite-sheet animations. Paid generation remains blocked unless explicitly enabled.", inputSchema: z.object({ characterId: z.string().min(1), animations: z.array(z.object({ kind: z.string().min(1), name: z.string().optional(), prompt: z.string().max(600).optional() })).min(1).max(10), videoTier: z.enum(["turbo","pro","ultra","max"]).optional(), frameCount: z.number().int().min(2).max(64).optional(), frameSize: z.number().int().min(32).max(512).optional(), removeBg: z.enum(["default","ultra"]).optional() }), annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async (input) => { try { return asResult(await autoSpriteGenerateAnimations(input)); } catch (e) { return errorResult(e); } });
  server.registerTool("gameshop_generation_status", { title: "Check Generation Status", description: "Check an AutoSprite generation job.", inputSchema: z.object({ jobId: z.string().min(1) }), annotations: { readOnlyHint: true, openWorldHint: true } }, async ({jobId}) => { try { return asResult(await autoSpriteGetJob(jobId)); } catch(e) { return errorResult(e); } });
  server.registerTool("gameshop_get_spritesheet", { title: "Get Sprite Sheet", description: "Return existing AutoSprite spritesheet metadata and URLs.", inputSchema: z.object({ spritesheetId: z.string().min(1) }), annotations: { readOnlyHint: true, openWorldHint: true } }, async ({spritesheetId}) => { try { return asResult(await autoSpriteGetSpritesheet(spritesheetId)); } catch(e) { return errorResult(e); } });
  server.registerTool("gameshop_spritecook_models", { title: "List SpriteCook Models", description: "List SpriteCook generation models.", inputSchema: z.object({}), annotations: { readOnlyHint: true, openWorldHint: true } }, async () => { try { return asResult(await spriteCookListModels()); } catch(e) { return errorResult(e); } });
  server.registerTool("gameshop_spritecook_generate", { title: "Generate Game Art with SpriteCook", description: "Start a SpriteCook generation job. Paid generation remains blocked unless explicitly enabled.", inputSchema: z.object({ prompt: z.string().min(1).max(2000), mode: z.enum(["assets","texture","ui"]).optional(), model: z.string().min(1).optional(), resolution: z.enum(["1K","2K","4K"]).optional(), quality: z.enum(["low","medium","high"]).optional(), colors: z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)).max(64).optional(), referenceAssetId: z.string().optional(), editAssetId: z.string().optional(), projectId: z.string().optional() }), annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async (input) => { try { return asResult(await spriteCookGenerate(input)); } catch(e) { return errorResult(e); } });
  server.registerTool("gameshop_spritecook_status", { title: "Check SpriteCook Job", description: "Check a SpriteCook generation job.", inputSchema: z.object({ jobId: z.string().min(1) }), annotations: { readOnlyHint: true, openWorldHint: true } }, async ({jobId}) => { try { return asResult(await spriteCookGetJob(jobId)); } catch(e) { return errorResult(e); } });
});

function isAuthorized(request: Request) { const token = process.env.GAME_SHOP_MCP_TOKEN; if (!token) return true; return request.headers.get("authorization") === `Bearer ${token}`; }
async function route(request: Request) { if (!isAuthorized(request)) return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "content-type": "application/json" } }); return handler(request); }
export { route as GET, route as POST, route as DELETE };
