import { diagnosticsRoute } from "../src/http/diagnostics-route.js";
import { storageRoute } from "../src/http/storage-route.js";
import { tasksRoute } from "../src/http/tasks-route.js";

function html(title:string,body:string){return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font:16px/1.6 system-ui,-apple-system,sans-serif;max-width:820px;margin:48px auto;padding:0 20px;color:#171717}h1,h2{line-height:1.2}a{color:inherit}</style></head><body>${body}</body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=300"}});}

function privacyRoute(){return html("Game Shop Privacy Policy",`<h1>Game Shop Privacy Policy</h1><p>Last updated: September 13, 2026.</p><p>Game Shop is an AI-assisted game-development service operated by The Grei Show. It connects approved AI clients to registered game-development projects and tools through a remote MCP server.</p><h2>Data we process</h2><p>Depending on the tools you choose to use, Game Shop may process account authorization information, project and repository identifiers, game-development prompts and instructions, execution metadata, QA results, provider job identifiers, preview and deployment metadata, and technical logs needed to operate and secure the service. Game Shop is designed not to expose API keys, access tokens, service-role credentials, or other server-side secrets in tool responses.</p><h2>How we use data</h2><p>We use data to authenticate requests, inspect and improve registered projects, execute authorized workflows, route work to approved integrations, verify results, prevent abuse, enforce project and spending controls, troubleshoot failures, and maintain service reliability.</p><h2>Third parties</h2><p>When you explicitly authorize a workflow that uses an external provider, relevant task data may be sent to that provider to perform the requested operation. GitHub may receive project read or write operations when GitHub access is enabled. Other external providers are invoked only through allowlisted operations and remain subject to Game Shop's independent integration and spending controls.</p><h2>Retention</h2><p>Operational logs, execution history, project metadata, and provider-job records may be retained for as long as reasonably necessary to provide the service, maintain security and auditability, resolve disputes, and comply with legal obligations. Provider services may apply their own retention terms to data sent to them.</p><h2>Your controls</h2><p>You control whether Game Shop may perform GitHub writes, call external integrations, or use paid generation. These permissions are independently gated. You may stop using Game Shop at any time and may contact us about access, correction, or deletion requests where applicable.</p><h2>Contact</h2><p>Questions about this policy can be sent through <a href="https://thegreishow.com/contact">thegreishow.com/contact</a>.</p>`);}

function termsRoute(){return html("Game Shop Terms of Use",`<h1>Game Shop Terms of Use</h1><p>Last updated: September 13, 2026.</p><p>By using Game Shop, you agree to use it only for projects, repositories, accounts, assets, and services that you are authorized to access.</p><h2>Authorized actions</h2><p>Game Shop may inspect projects, create plans, run QA, call approved integrations, create project-scoped branches, edit files, create pull requests, or prepare deployments only when the relevant server-side permissions and caller authorization allow those actions.</p><h2>Costs</h2><p>External generation or other paid provider operations are not enabled merely by connecting Game Shop. Paid generation is controlled separately and may be blocked unless explicitly enabled. You remain responsible for charges incurred through provider accounts you authorize.</p><h2>Project safety</h2><p>Game Shop restricts autonomous project writes to registered project roots and controlled branches. You are responsible for reviewing proposed code, assets, pull requests, previews, and releases before relying on or publishing them.</p><h2>No warranty</h2><p>Game Shop is provided on an as-available basis. AI-generated plans, code, assets, tests, and recommendations can contain errors and should be reviewed before production use.</p><h2>Acceptable use</h2><p>You may not use Game Shop to obtain secrets, bypass authorization, access projects you do not control, evade provider restrictions, or perform unlawful activity.</p><h2>Contact</h2><p>Support is available through <a href="https://thegreishow.com/contact">thegreishow.com/contact</a>.</p>`);}

function challengeRoute(){const token=(process.env.OPENAI_APPS_CHALLENGE_TOKEN||"").trim();if(!token)return new Response("OpenAI Apps challenge token is not configured",{status:404,headers:{"content-type":"text/plain; charset=utf-8"}});return new Response(token,{headers:{"content-type":"text/plain; charset=utf-8","cache-control":"no-store"}});}

async function route(request:Request){
  const url=new URL(request.url);
  const target=url.searchParams.get("route")||"";
  if(target==="diagnostics")return diagnosticsRoute(request);
  if(target==="storage")return storageRoute(request);
  if(target==="tasks")return tasksRoute(request);
  if(target==="privacy")return privacyRoute();
  if(target==="terms")return termsRoute();
  if(target==="openai-apps-challenge")return challengeRoute();
  return new Response(JSON.stringify({error:"Unknown utility route"}),{status:404,headers:{"content-type":"application/json"}});
}

export { route as GET, route as POST, route as DELETE };
